force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <description>Track Credit/Debit card details of clients</description>
    <label>Card</label>
    <nameField>
        <displayFormat>CARD-{000000}</displayFormat>
        <label>Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Stripe_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Id__c</fullName>
    <label>Stripe Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/Stripe_Transaction__c.object-meta.xml
<CustomObject>
    <label>Stripe Transaction</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Stripe Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/StripeManualChargeExtensionTest.cls
/*****************************************************************************************
 * @Purpose      : Unit test for StripeManualChargeExtension
 * @Created Date : 14 August 2019
 * @Author       : Madhura Priyadarshana 
 *****************************************************************************************/
@isTest
private class StripeManualChargeExtensionTest {
    
    @testSetup
    static void setupTestData() {
        Test.startTest();
        Contact contactWithStripeId = new Contact(
          FirstName = 'Test',
            LastName = 'User',
            Stripe_Id__c = 'tk_dsfj324'
        );
        insert contactWithStripeId;
        
        Card__c card = new Card__c(
          Card_Number__c = 'Test Card',
            Contact__c = contactWithStripeId.Id
        );
        insert card;
        
        Test.stopTest();        
    }
    
    @isTest
    static void makeSuccessCharge() {
        Test.startTest();
        Contact con = [SELECT Id, Stripe_Id__c FROM Contact LIMIT 1];
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(con);
        StripeManualChargeExtension ctrl = new StripeManualChargeExtension(stdCtrl);
        ctrl.stripeTransaction.Total_Amount__c = 52.50;
        ctrl.serviceChargeIncluded = true;
        
        Test.setMock(System.HttpCalloutMock.class, new MockHttpResponseGenerator());
        ctrl.chargeCustomer();
        Test.stopTest();
        
        System.assert(NULL != [SELECT Id FROM Stripe_Transaction__c]);
    }

}