force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <description>Track Credit/Debit card details of clients</description>
    <label>Card</label>
    <nameField>
        <displayFormat>CARD-{000000}</displayFormat>
        <label>Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Card_Holder__c.field-meta.xml
<CustomField>
    <fullName>Card_Holder__c</fullName>
    <label>Card Holder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Security_Code__c.field-meta.xml
<CustomField>
    <fullName>Security_Code__c</fullName>
    <label>Security Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CardService.cls
public without sharing class CardService {
    /**
     * creates Card record to related contact
     * @param fieldVals fieldValues that sent by call out response
     * @param contId related contactId
     */
    public static void createCardRecord(List<EsignEmbedService.FieldValue> fieldVals, Id contId) {
        Map<String, String> valuesByFieldName = new Map<String, String>();

        for(EsignEmbedService.FieldValue field: fieldVals){
            if(String.isNotEmpty(field.name)) {
                valuesByFieldName.put(field.name, field.value);
            }
        }
        try {
            insert new Card__c(
                Contact__c = contId,
                Card_Holder__c = valuesByFieldName.get('Signer Name'),
                Card_Number__c = valuesByFieldName.get('Card Number'),
                Expiration_Date__c = Date.newInstance(2000 + Integer.valueOf(valuesByFieldName.get('Expiration Year')), Integer.valueOf(valuesByFieldName.get('Expiration Month')), 1),
                Security_Code__c = valuesByFieldName.get('Security Code')
            );
        }
        catch(Exception ex) {
            throw new EsignEmbedService.EmbedServiceException(ex.getMessage());
        }
    }
}