force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <description>Track Credit/Debit card details of clients</description>
    <label>Card</label>
    <nameField>
        <displayFormat>CARD-{000000}</displayFormat>
        <label>Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Stripe_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Id__c</fullName>
    <label>Stripe Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StripeAuthorizeCardExtensionTest.cls
/*****************************************************************************************
 * @Purpose      : Unit test for StripeAuthorizeCardExtension
 * @Created Date : 27 August 2019
 * @Author       : Madhura Priyadarshana 
 *****************************************************************************************/
@isTest
private class StripeAuthorizeCardExtensionTest {

    @testSetup
    static void setupTestData() {
        Contact con = new Contact(
        	FirstName = 'Stripe',
            LastName = 'User',
            Email = 'stripe@user.com',
            Stripe_Id__c = ''
        );
        insert con;
        
        Card__c card = new Card__c(
        	Contact__c = con.Id
        );
        insert card;
    }
    
    @isTest static void testCreateCustomer() {
        Test.startTest();
        Card__c card = [SELECT Id, Contact__c FROM Card__c LIMIT 1];
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(card);
        StripeAuthorizeCardExtension ctrl = new StripeAuthorizeCardExtension(stdCtrl);
        
        Test.setMock(System.HttpCalloutMock.class, new MockHttpResponseGenerator());
        ctrl.createCustomer();
        
        Contact con = [SELECT Id, Stripe_Id__c FROM Contact WHERE Id =: card.Contact__c LIMIT 1];
        System.assert(con.Stripe_Id__c != NULL);
        Test.stopTest();
    }
}