force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <description>Track Credit/Debit card details of clients</description>
    <label>Card</label>
    <nameField>
        <displayFormat>CARD-{000000}</displayFormat>
        <label>Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Card_Holder__c.field-meta.xml
<CustomField>
    <fullName>Card_Holder__c</fullName>
    <label>Card Holder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visa</fullName>
                <default>true</default>
                <label>Visa</label>
            </value>
            <value>
                <fullName>Master Card</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>American Express</fullName>
            </value>
            <value>
                <fullName>JCB Card</fullName>
            </value>
            <value>
                <fullName>Diners Club</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Card__c/fields/Security_Code__c.field-meta.xml
<CustomField>
    <fullName>Security_Code__c</fullName>
    <label>Security Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Check__c/Check__c.object-meta.xml
<CustomObject>
    <label>Check</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Check__c/fields/Bank_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Routing_Number__c</fullName>
    <label>Bank Routing Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Checking_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Checking_Account_Number__c</fullName>
    <label>Checking Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Checks</relationshipLabel>
    <relationshipName>Checks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Issuing_Bank__c.field-meta.xml
<CustomField>
    <fullName>Issuing_Bank__c</fullName>
    <label>Issuing Bank</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Check__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name on Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BN_Portal_Cards_Controller.cls
public class BN_Portal_Cards_Controller extends BN_Portal_Template_Controller {
    
    public Contact contact {get; set;}
    
    public List<Card__c> cards {get; set;}
    public Card__c card {get; set;}
    public String cardId {get; set;}
    public String cardName {get; set;}
    public String cardNumber {get; set;}
    public String cardCvv {get; set;}
    public String cardExpDate {get; set;}
    
    public List<Check__c> checks {get; set;}
    public Check__c check {get; set;}
    public String checkId {get; set;}
    public String nameOnAccount {get; set;}
    public String bankRoutingNumber {get; set;}
    public String checkingAccountNumber {get; set;}
    public String issuingBank {get; set;}
    
    public BN_Portal_Cards_Controller() {
        
        String bnUserId = BN_Portal_UserUtils.getCurrBNUserId();
        
        contact = BN_Portal_UserUtils.getContactByBNUserId(bnUserId);
        
        cards = getCardsByContactId(contact.Id);
        checks = getChecksByContactId(contact.Id);
        
        cardName = '';
        cardNumber = '';
        cardCvv = '';
        cardExpDate = '';
        
        nameOnAccount = '';
        bankRoutingNumber = '';
        checkingAccountNumber = '';
        issuingBank = '';
    }
    
    private List<Card__c> getCardsByContactId(String contactId)
    {
        return [SELECT Id, Name, Card_Holder__c, Card_Number__c, Card_Type__c, Expiration_Date__c, Security_Code__c, CreatedDate FROM Card__c WHERE Contact__c = :contactId ORDER BY CreatedDate DESC];
    }
    
    private List<Check__c> getChecksByContactId(String contactId)
    {
        return [SELECT Id, Name, Name__c, Bank_Routing_Number__c, Checking_Account_Number__c, Issuing_Bank__c, Contact__c, CreatedDate FROM Check__c WHERE Contact__c = :contactId ORDER BY CreatedDate DESC];
    }
        
    public PageReference addCard()
    {
        try {
            // convert card exp to date
            String month = cardExpDate.substring(0,2);
            String year = cardExpDate.substring(5);  
            Date cardExp = Date.newInstance(integer.valueOf(year), integer.valueOf(month), 1);
            System.Debug('cardExp: ' +  cardExp);
            
            card = new Card__c();
            card.Contact__c = contact.Id;
            card.Card_Holder__c = cardName;
            card.Card_Number__c = cardNumber;
            card.Security_Code__c = cardCvv;
            card.Expiration_Date__c = cardExp;
            insert card;
            
            // send email notif
            sendEmailNotif(card.Id);
            
            PageReference pageRef = new PageReference('/portal/cards');
            pageRef.setRedirect(true);
            return pageRef;
        }
        catch(Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, e.getMessage()));
            return null;
        }
    }
    
    public PageReference addCheck()
    {        
        try {
            check = new Check__c();
            check.Name__c = nameOnAccount;
            check.Bank_Routing_Number__c = bankRoutingNumber;
            check.Checking_Account_Number__c = checkingAccountNumber;
            check.Issuing_Bank__c = issuingBank;
            check.Contact__c = contact.Id;
            insert check;
            
            // send email notif
            sendEmailNotif(check.Id);
            
            PageReference pageRef = new PageReference('/portal/cards');
            pageRef.setRedirect(true);
            return pageRef;
        }
        catch(Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, e.getMessage()));
            return null;
        }
    }
    
    public void deleteCard()
    {
        Card__c cardDel = [SELECT Id, Name FROM Card__c WHERE Id = :cardId];
        delete cardDel;
        
        // reset
        cards = getCardsByContactId(contact.Id);
    }
    
    public void deleteCheck()
    {
        Check__c checkDel = [SELECT Id, Name FROM Check__c WHERE Id = :checkId];
        delete checkDel;
        
        // reset
        checks = getChecksByContactId(contact.Id);
    }
    
    private void sendEmailNotif(String id)
    {
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.toAddresses = new String[] { 'david@bookingninjas.com' };
        message.optOutPolicy = 'FILTER';
        message.subject = 'You have new client\'s additional card/check';
        message.setHtmlBody('See record <a href="https://bookingninjas.my.salesforce.com/' + id + '">here</a>. <br/><br/> Best regards, <br/> David M. Harroch <br/> Founder and CEO <br/> Booking Ninjas');
        Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
        Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
    }
}