force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <description>Track Credit/Debit card details of clients</description>
    <label>Card</label>
    <nameField>
        <displayFormat>CARD-{000000}</displayFormat>
        <label>Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Stripe_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Id__c</fullName>
    <label>Stripe Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/Stripe_Transaction__c.object-meta.xml
<CustomObject>
    <label>Stripe Transaction</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Stripe Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Transaction__c/fields/Guest_Contact__c.field-meta.xml
<CustomField>
    <fullName>Guest_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Stripe Transactions</relationshipLabel>
    <relationshipName>Stripe_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Stripe_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Transaction_Id__c</fullName>
    <description>Track the stripe transaction id for any kind of back tracking</description>
    <label>Stripe Transaction Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StripeRefundExtensionTest.cls
@isTest
private class StripeRefundExtensionTest {
    
    @testSetup
    static void setupTestData() {
        Test.startTest();
        Contact contactWithStripeId = new Contact(
          FirstName = 'Test',
            LastName = 'User',
            Stripe_Id__c = 'tk_dsfj324'
        );
        insert contactWithStripeId;
        
        Card__c card = new Card__c(
          Card_Number__c = 'Test Card',
            Contact__c = contactWithStripeId.Id
        );
        insert card;
        
        Stripe_Transaction__c st = new Stripe_Transaction__c(
            Guest_Contact__c = contactWithStripeId.Id,
            Stripe_Transaction_Id__c = 'ch_1EpZcpLJXa2cEwUA312DoOLM',
            Total_Amount__c = 1
        );
        insert st;
        
        Test.stopTest();        
    }
    
    @isTest
    static void makeSuccessRefund() {
        Test.startTest();
        Stripe_Transaction__c trans = [SELECT Id, Guest_Contact__c, Stripe_Transaction_Id__c,Total_Amount__c FROM Stripe_Transaction__c LIMIT 1];
        
        PageReference pageRef = Page.StripeRefund;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', trans.Id);
        
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(trans);
        StripeRefundExtension ctrl = new StripeRefundExtension(stdCtrl);
        
        Test.setMock(System.HttpCalloutMock.class, new MockHttpResponseGenerator());
        ctrl.doRefund();
        Test.stopTest();
    }

}