force-app/main/default/objects/Career__c/Career__c.object-meta.xml
<CustomObject>
    <label>Career</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Applicant No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Careers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Career__c/fields/Linkedin__c.field-meta.xml
<CustomField>
    <fullName>Linkedin__c</fullName>
    <label>Linkedin</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Career__c/fields/RelatedVacancy__c.field-meta.xml
<CustomField>
    <fullName>RelatedVacancy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Vacancy</label>
    <referenceTo>Vacancy__c</referenceTo>
    <relationshipLabel>Submitted Applications</relationshipLabel>
    <relationshipName>SubmittedApplications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Describe what the position entails.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/DetailBannerArt__c.field-meta.xml
<CustomField>
    <fullName>DetailBannerArt__c</fullName>
    <description>The artwork that is displayed in the banner of the detail page.</description>
    <label>Detail Banner Art</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VacancyDetailArt</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/IconArt__c.field-meta.xml
<CustomField>
    <fullName>IconArt__c</fullName>
    <label>Icon Art</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VacancyIconArt</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Intro__c.field-meta.xml
<CustomField>
    <fullName>Intro__c</fullName>
    <description>Short text to describe the position on the grid.</description>
    <label>Intro</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/IsOpen__c.field-meta.xml
<CustomField>
    <fullName>IsOpen__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If unchecked, this job will not be visible to guests.</description>
    <label>Is Open</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Control the order in which the vacancies are rendered on the website.</description>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/OtherInformation__c.field-meta.xml
<CustomField>
    <fullName>OtherInformation__c</fullName>
    <description>Any other information like extra credits goes here.</description>
    <label>Other Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Overview__c.field-meta.xml
<CustomField>
    <fullName>Overview__c</fullName>
    <description>What does the position entail? Each line is rendered as a bullet point.</description>
    <label>Overview</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Qualifications__c.field-meta.xml
<CustomField>
    <fullName>Qualifications__c</fullName>
    <description>List the requirements for the role. Each line is displayed as a bullet point.</description>
    <label>Qualifications</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BN_VacancyController_Test.cls
@isTest
private class BN_VacancyController_Test {

    private static void insertVacancyRecords(Integer y){
        for(Integer x = 0; x < y; x++){
            Vacancy__c v = new Vacancy__c(
                Name ='Vacancy '+ x, 
                Intro__c='Something',
                DetailBannerArt__c='https://d1b89zc79exfxt.cloudfront.net/img/Account_Executives.png',
                IconArt__c='https://d1b89zc79exfxt.cloudfront.net/img/career-monitor.png',
                Description__c='Something',
                Order__c = x,
                OtherInformation__c = 'Other information',
                Qualifications__c = 'Qualifications',
                Overview__c = 'Overview',
                IsOpen__c = (Math.mod(x, 2) > 0)
            );

            insert v;
        }
    }
    
    @isTest static void testGetVacanciesMethod() 
    {
        insertVacancyRecords(10);

        List<Vacancy__c> vacancies = BN_VacancyController.getVacancies();
        System.assertEquals(vacancies.size(), 5); // only open requests are returned.        
    }
    
    @isTest static void testGetSingleVacancyMethod() 
    {
        insertVacancyRecords(3);
        Vacancy__c v = [SELECT Id, Name FROM Vacancy__c LIMIT 1];

        Vacancy__c vacancy = BN_VacancyController.getSingleVacancy(v.Id);
        System.assert(vacancy != null);
        if(vacancy != null){
            System.assertEquals(vacancy.Name, v.Name);
        }
    }

    @isTest static void testSubmitApplication(){
        insertVacancyRecords(3);
        List<Vacancy__c> vacancies = BN_VacancyController.getVacancies();

        BN_VacancyController.submitApplication(new Career__c(
            Name__c = 'Kolade Ige', 
            RelatedVacancy__c = vacancies[0].Id, 
            Email__c = 'kolade.ige@gmail.com',
            Phone__c = '08088473115',
            LinkedIn__c = 'https://www.linkedin.com/in/koladeige/')
        );

        Career__c career = [SELECT Name, Id, RelatedVacancy__c FROM Career__c LIMIT 1];
        System.assert(career != null);
        if(career != null){
            System.assertEquals(vacancies[0].Id, career.RelatedVacancy__c);
        }
    }
    
}