force-app/main/default/objects/Career__c/Career__c.object-meta.xml
<CustomObject>
    <label>Career</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Applicant No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Careers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Describe what the position entails.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/DetailBannerArt__c.field-meta.xml
<CustomField>
    <fullName>DetailBannerArt__c</fullName>
    <description>The artwork that is displayed in the banner of the detail page.</description>
    <label>Detail Banner Art</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VacancyDetailArt</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Intro__c.field-meta.xml
<CustomField>
    <fullName>Intro__c</fullName>
    <description>Short text to describe the position on the grid.</description>
    <label>Intro</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/OtherInformation__c.field-meta.xml
<CustomField>
    <fullName>OtherInformation__c</fullName>
    <description>Any other information like extra credits goes here.</description>
    <label>Other Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Overview__c.field-meta.xml
<CustomField>
    <fullName>Overview__c</fullName>
    <description>What does the position entail? Each line is rendered as a bullet point.</description>
    <label>Overview</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Qualifications__c.field-meta.xml
<CustomField>
    <fullName>Qualifications__c</fullName>
    <description>List the requirements for the role. Each line is displayed as a bullet point.</description>
    <label>Qualifications</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Questions__c.field-meta.xml
<CustomField>
    <fullName>Questions__c</fullName>
    <description>Exactly what it means.</description>
    <label>Questions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/VacancyID__c.field-meta.xml
<CustomField>
    <fullName>VacancyID__c</fullName>
    <displayFormat>JD-{00000}</displayFormat>
    <label>Vacancy ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/BN_VacancyPageController.cls
public without sharing class BN_VacancyPageController {
    private final Vacancy__c vacancy;    
    public Career__c career {get; set;}
        
    public BN_VacancyPageController(){      
        vacancy = [
            SELECT Id,DetailBannerArt__c,Name,VacancyID__c,Intro__c, Description__c,OtherInformation__c,Overview__c,Qualifications__c,Questions__c 
            FROM Vacancy__c 
            WHERE Id =: ApexPages.currentPage().getParameters().get('id')
        ];     
    }

    public String getRoleName(){
        if(vacancy.Name != null) {
            return vacancy.Name;
        }
        return '';
    }

    public String[] getOverview(){
        if(vacancy.Overview__c != null){
            return vacancy.Overview__c.split('[\n\r]+');
        }
        return new String[]{};
    }

    public String[] getDescription(){
        if(vacancy.Description__c != null){
            return vacancy.Description__c.split('[\n\r]+');
        }
        return new String[]{};
    }

    public String getIntro(){
        if(vacancy.Intro__c != null){
            return vacancy.Intro__c;
        }
        return '';
    }

    public String[] getQualifications(){
        if(vacancy.Qualifications__c != null){
            return vacancy.Qualifications__c.split('[\n\r]+');
        }
        return new String[]{};
    }

    public String[] getQuestions(){
        if(vacancy.Questions__c != null){
            return vacancy.Questions__c.split('[\n\r]+');
        }
        return new String[]{};
    }

    public String getOtherInformation(){
        if(vacancy.OtherInformation__c != null){
            return vacancy.OtherInformation__c;
        }
        return '';
    }

    public String getVacancyID(){
        return vacancy.VacancyID__c;
    }

    public String getDetailArt(){
        if(vacancy.DetailBannerArt__c == null){
            return 'https://d1b89zc79exfxt.cloudfront.net/img/career-bnr1.png';
        }
        
        return vacancy.DetailBannerArt__c;
    }

    public Vacancy__c getVacancy() {
        return vacancy;
    }
}