force-app/main/default/objects/Career__c/Career__c.object-meta.xml
<CustomObject>
    <label>Career</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Applicant No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Careers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Career__c/fields/RelatedVacancy__c.field-meta.xml
<CustomField>
    <fullName>RelatedVacancy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Vacancy</label>
    <referenceTo>Vacancy__c</referenceTo>
    <relationshipLabel>Submitted Applications</relationshipLabel>
    <relationshipName>SubmittedApplications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Describe what the position entails.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/IconArt__c.field-meta.xml
<CustomField>
    <fullName>IconArt__c</fullName>
    <label>Icon Art</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VacancyIconArt</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Intro__c.field-meta.xml
<CustomField>
    <fullName>Intro__c</fullName>
    <description>Short text to describe the position on the grid.</description>
    <label>Intro</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/IsOpen__c.field-meta.xml
<CustomField>
    <fullName>IsOpen__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If unchecked, this job will not be visible to guests.</description>
    <label>Is Open</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Control the order in which the vacancies are rendered on the website.</description>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/OtherInformation__c.field-meta.xml
<CustomField>
    <fullName>OtherInformation__c</fullName>
    <description>Any other information like extra credits goes here.</description>
    <label>Other Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Overview__c.field-meta.xml
<CustomField>
    <fullName>Overview__c</fullName>
    <description>What does the position entail? Each line is rendered as a bullet point.</description>
    <label>Overview</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Qualifications__c.field-meta.xml
<CustomField>
    <fullName>Qualifications__c</fullName>
    <description>List the requirements for the role. Each line is displayed as a bullet point.</description>
    <label>Qualifications</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Questions__c.field-meta.xml
<CustomField>
    <fullName>Questions__c</fullName>
    <description>Exactly what it means.</description>
    <label>Questions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/VacancyID__c.field-meta.xml
<CustomField>
    <fullName>VacancyID__c</fullName>
    <displayFormat>JD-{00000}</displayFormat>
    <label>Vacancy ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/BN_VacancyController.cls
public without sharing class BN_VacancyController {    
    @AuraEnabled(cacheable=true)
    public static Vacancy__c getSingleVacancy(String vacancyId) {
        return [
            SELECT OwnerId,Id,Name,VacancyID__c,Intro__c, Description__c,OtherInformation__c,Overview__c,Qualifications__c,Questions__c 
            FROM Vacancy__c 
            WHERE Id =: vacancyId
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Vacancy__c> getVacancies() {
        return [
            SELECT Id,Name,VacancyID__c,Intro__c,IconArt__c
            FROM Vacancy__c
            WHERE IsOpen__c =: TRUE   
            ORDER BY Order__c       
        ];
    }

    @AuraEnabled
    public static String submitApplication(Career__c career) 
    {
        BN_VacancyController.APIResponse response = new BN_VacancyController.APIResponse();
        response.Status = 'success';

        Vacancy__c vacancy = [SELECT Id, OwnerId FROM Vacancy__c WHERE Id =: career.RelatedVacancy__c];

        try{
            insert career;
            sendAcknowledgement(career);
        } catch (Exception e){
            response.Status = 'failure';
            response.Message = e.getMessage();
        }

        return JSON.serialize(response);
    }

    private static void sendAcknowledgement(Career__c career){
        EmailTemplate lstEmailTemplates = [SELECT Id, Body, Markup, HtmlValue, Subject, EnhancedLetterheadId, TemplateStyle, TemplateType, RelatedEntityType, BrandTemplateId, Encoding FROM EmailTemplate WHERE DeveloperName = 'BN_CareerApplicationConfirmation' LIMIT 1];
        Vacancy__c vacancy = [SELECT Id, OwnerId FROM Vacancy__c WHERE Id =: career.RelatedVacancy__c LIMIT 1];

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTemplateId(lstEmailTemplates.Id);
        mail.setSaveAsActivity(false);
        mail.setTreatTargetObjectAsRecipient(false);
        mail.setTargetObjectId(vacancy.OwnerId); // Any contact or User id of your record
        mail.setToAddresses(new list<string>{career.Email__c});

        mail.setWhatId(career.Id); // Enter your record Id whose merge field you want to add in template
        Messaging.SendEmailResult[] resultMail = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });        
    }

    class APIResponse {
        public String Status = 'failure';
        public String Message = '';
        public String MessageCode = '';
        public object OtherInfo = null;        
    }
}