force-app/main/default/objects/Campaign_Report__c/Campaign_Report__c.object-meta.xml
<CustomObject>
    <description>Campaign report created automatically by BookingNinjas.email</description>
    <label>Campaign Activity</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Report__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Campaign_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CampaignReportTriggerTest.cls
@isTest
public class CampaignReportTriggerTest {
    
    @testSetup static void setup() {
        Contact ct = new Contact(LastName = 'Teguh', Email = 'teguh@bookingninjas.com');
        insert ct;
        insert new Campaign_Report__c(Name = 'New Campaign', Contact__c = ct.Id);
    }

    static testmethod void testOpportunityFromTrialForm() {
        Contact ct = [SELECT Id FROM Contact WHERE Email = 'teguh@bookingninjas.com'];

        Test.StartTest();
        insert new Campaign_Report__c(Name = 'New Campaign', Contact__c = ct.Id);
        Test.StopTest();

        System.assertEquals(1, [SELECT count() FROM Campaign_Report__c WHERE Contact__c = :ct.Id]);
    }

}