force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <label>Article</label>
    <nameField>
        <label>Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Meta_Description__c.field-meta.xml
<CustomField>
    <fullName>Meta_Description__c</fullName>
    <label>Meta Description</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Meta_Title__c.field-meta.xml
<CustomField>
    <fullName>Meta_Title__c</fullName>
    <label>Meta Title</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Total_Views__c.field-meta.xml
<CustomField>
    <fullName>Total_Views__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total_Views</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Article_Views__c/Article_Views__c.object-meta.xml
<CustomObject>
    <label>Article Views</label>
    <nameField>
        <displayFormat>AV-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article_Views__c/fields/Article__c.field-meta.xml
<CustomField>
    <fullName>Article__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Article Views</relationshipLabel>
    <relationshipName>Article_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article_Views__c/fields/ArticleId__c.field-meta.xml
<CustomField>
    <fullName>ArticleId__c</fullName>
    <label>ArticleId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ArticleViewsTriggerTest.cls
@isTest
public class ArticleViewsTriggerTest {
    
    static testmethod void testArticleView() {
        
        Article__c art = new Article__c();
        art.Name = 'Article Title';
        art.Meta_Title__c = 'Article Title';
        art.Meta_Description__c = 'Article description';
        insert art;
           
        Article_Views__c av = new Article_Views__c();
        av.ArticleId__c = art.Id;
        av.IP_Address__c = '192.168.1.1';
        insert av;
        
        Article__c artRecord = [SELECT Id FROM Article__c LIMIT 1];
        Article_Views__c avRecord = [SELECT ArticleId__c FROM Article_Views__c LIMIT 1];
        
        Test.StartTest();
        System.assertEquals(avRecord.ArticleId__c, artRecord.Id);
        Test.StopTest();
    }
    
    static testmethod void testArticleViewExist() {
        
        Article__c art = new Article__c();
        art.Name = 'Article Title';
        art.Meta_Title__c = 'Article Title';
        art.Meta_Description__c = 'Article description';
        insert art;
        
        Article_Views__c av1 = new Article_Views__c();
        av1.ArticleId__c = art.Id;
        av1.IP_Address__c = '192.168.1.1';
        insert av1;
           
        Article_Views__c av2 = new Article_Views__c();
        av2.ArticleId__c = art.Id;
        av2.IP_Address__c = '192.168.1.1';
        insert av2;
        
        Article__c artRecord = [SELECT Id, Total_Views__c FROM Article__c LIMIT 1];
        Article_Views__c avRecord = [SELECT ArticleId__c FROM Article_Views__c LIMIT 1];
        
        Test.StartTest();
        System.assertEquals(avRecord.ArticleId__c, artRecord.Id);
        System.assertEquals(artRecord.Total_Views__c, 1);
        Test.StopTest();
    }
    
}