force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <label>Article</label>
    <nameField>
        <label>Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Article_Link__c.field-meta.xml
<CustomField>
    <fullName>Article_Link__c</fullName>
    <inlineHelpText>You may leave it blank</inlineHelpText>
    <label>Article Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Publish__c.field-meta.xml
<CustomField>
    <fullName>Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SitemapController.cls
/*
 * Dynamic sitemap links generator for blogs, etc.
 * 
 * @author: <mustafasahin.mshn@gmail.com>
 * 
 * Tester: SitemapControllerTest
 */
public with sharing class SitemapController {

    public List<String> blogPages {get; set;}

    public SitemapController(){
        this.blogPages = new List<String>();
        for(Article__c art : [SELECT Article_Link__c FROM Article__c WHERE Publish__c = true]){
            blogPages.add(art.Article_Link__c);
        }
    }

}