force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <label>Article</label>
    <nameField>
        <label>Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Article_Link__c.field-meta.xml
<CustomField>
    <fullName>Article_Link__c</fullName>
    <inlineHelpText>You may leave it blank</inlineHelpText>
    <label>Article Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Article_Preview__c.field-meta.xml
<CustomField>
    <fullName>Article_Preview__c</fullName>
    <inlineHelpText>Summary / tldr of the article,</inlineHelpText>
    <label>Article Preview</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Article_Region__c.field-meta.xml
<CustomField>
    <fullName>Article_Region__c</fullName>
    <description>Choose article language/region</description>
    <label>Article Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>(BR) Brazil</fullName>
            </value>
            <value>
                <fullName>(EN) English</fullName>
                <default>true</default>
                <label>(EN) English</label>
            </value>
            <value>
                <fullName>(FR) France</fullName>
            </value>
            <value>
                <fullName>(DE) Germany</fullName>
            </value>
            <value>
                <fullName>(PT) Portugal</fullName>
            </value>
            <value>
                <fullName>(ES) Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Article__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Author</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Articles</relationshipLabel>
    <relationshipName>Articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Featured</fullName>
            </value>
            <value>
                <fullName>Trends</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Property Management</fullName>
            </value>
            <value>
                <fullName>Self Storage</fullName>
            </value>
            <value>
                <fullName>Restaurants</fullName>
            </value>
            <value>
                <fullName>CoWorking</fullName>
                <label>Coworking</label>
            </value>
            <value>
                <fullName>Student Housing</fullName>
            </value>
            <value>
                <fullName>Villas</fullName>
            </value>
            <value>
                <fullName>Vacation Rental</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Hostel</fullName>
            </value>
            <value>
                <fullName>Tendencias</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Article__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Cover_Photo__c.field-meta.xml
<CustomField>
    <fullName>Cover_Photo__c</fullName>
    <label>Cover Photo (URL)</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/HTML_Content__c.field-meta.xml
<CustomField>
    <fullName>HTML_Content__c</fullName>
    <label>HTML Content</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Publish__c.field-meta.xml
<CustomField>
    <fullName>Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Scheduled_Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Publish_Date__c</fullName>
    <label>Scheduled Publish Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Tags__c.field-meta.xml
<CustomField>
    <fullName>Tags__c</fullName>
    <label>Tags (separated by comma)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Total_Views__c.field-meta.xml
<CustomField>
    <fullName>Total_Views__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total_Views</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Article_Views__c/Article_Views__c.object-meta.xml
<CustomObject>
    <label>Article Views</label>
    <nameField>
        <displayFormat>AV-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article_Views__c/fields/Article__c.field-meta.xml
<CustomField>
    <fullName>Article__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Article Views</relationshipLabel>
    <relationshipName>Article_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article_Views__c/fields/Article_Link__c.field-meta.xml
<CustomField>
    <fullName>Article_Link__c</fullName>
    <formula>Article__r.Article_Link__c</formula>
    <label>Article Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article_Views__c/fields/ArticleId__c.field-meta.xml
<CustomField>
    <fullName>ArticleId__c</fullName>
    <label>ArticleId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BNES_ArticleController.cls
public without sharing class BNES_ArticleController {
    public String articleId { get; set; }

    public BNES_ArticleController() {
        articleId = ApexPages.currentPage().getParameters().get('id');
    }

    public Article__c getArticle() {
        return [
            SELECT
                Id,
                Name,
                Author__r.Name,
                Article_Link__c,
                Author__r.Username__c,
                Author__r.Profile_Picture__c,
                Author__r.Show_Author_Page__c,
                Total_Views__c,
                Category__c,
                Cover_Photo__c,
                HTML_Content__c,
                Content__c,
                Tags__c,
                Scheduled_Publish_Date__c,
                CreatedDate,
                CreatedBy.Name,
                (SELECT Id FROM Article_Views__r)
            FROM Article__c
            WHERE Id = :articleId
        ];
    }

    public List<Article__c> getTrendingArticles() {
        return [
            SELECT
                Id,
                Name,
                Author__c,
                Author__r.Name,
                Author__r.Username__c,
                Article_Link__c,
                Author__r.Profile_Picture__c,
                Author__r.Show_Author_Page__c,
                Cover_Photo__c,
                Article_Preview__c,
                HTML_Content__c,
                Content__c,
                Scheduled_Publish_Date__c,
                CreatedDate
            FROM Article__c
            WHERE Publish__c = TRUE
            AND Scheduled_Publish_Date__c = LAST_N_DAYS:7
            AND Article_Region__c = '(ES) Spain'
            ORDER BY Total_Views__c DESC
            LIMIT 3
        ];
    }

    public void saveArticleView() {
        String ipAddress = getUserIPAddress();
        List<String> location = getUserLocation(ipAddress);
        Article_Views__c av = new Article_Views__c();
        av.IP_Address__c = ipAddress;
        av.ArticleId__c = articleId;
        av.City__c = location[0];
        av.Country__c = location[1];
        insert av;
    }

    public static String getUserIPAddress() {
        String ipAddress = ApexPages.currentPage().getHeaders().get('True-Client-IP');

        // X-Salesforce-SIP has the value when no caching integration or via secure URL.
        if (ipAddress == '' || ipAddress == null) {
            ipAddress = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');
        } 

        // get IP address when no caching (sandbox, dev, secure urls)        
        if (ipAddress == '' || ipAddress == null) {
            ipAddress = ApexPages.currentPage().getHeaders().get('X-Forwarded-For');
        }

        return ipAddress;
    }

    public static List<String> getUserLocation(String ipAddress) {
        String endPoint = 'http://ip-api.com/json/' + ipAddress;

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setHeader('Content-Type', 'application/json');
        request.setEndpoint(endPoint);
        request.setMethod('GET');
        HttpResponse res = http.send(request);

        Map<String, Object> respMap = (Map<String, Object>)JSON.deserializeUntyped(res.getBody());
        
        List<String> location = new List<String>();
        if(respMap.get('status').equals('success')) {
            location.add((String)respMap.get('city'));
            location.add((String)respMap.get('country'));
        }

        return location;
    }
}