force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <label>Article</label>
    <nameField>
        <label>Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Article_Preview__c.field-meta.xml
<CustomField>
    <fullName>Article_Preview__c</fullName>
    <inlineHelpText>Summary / tldr of the article,</inlineHelpText>
    <label>Article Preview</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Article_Region__c.field-meta.xml
<CustomField>
    <fullName>Article_Region__c</fullName>
    <description>Choose article language/region</description>
    <label>Article Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>(BR) Brazil</fullName>
            </value>
            <value>
                <fullName>(EN) English</fullName>
                <default>true</default>
                <label>(EN) English</label>
            </value>
            <value>
                <fullName>(FR) France</fullName>
            </value>
            <value>
                <fullName>(DE) Germany</fullName>
            </value>
            <value>
                <fullName>(PT) Portugal</fullName>
            </value>
            <value>
                <fullName>(ES) Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Article__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Author</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Articles</relationshipLabel>
    <relationshipName>Articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Cover_Photo__c.field-meta.xml
<CustomField>
    <fullName>Cover_Photo__c</fullName>
    <label>Cover Photo (URL)</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/HTML_Content__c.field-meta.xml
<CustomField>
    <fullName>HTML_Content__c</fullName>
    <label>HTML Content</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Publish__c.field-meta.xml
<CustomField>
    <fullName>Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Scheduled_Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Publish_Date__c</fullName>
    <label>Scheduled Publish Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Total_Views__c.field-meta.xml
<CustomField>
    <fullName>Total_Views__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total_Views</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BNES_AuthorController.cls
public class BNES_AuthorController {
    private String contactId;
    public String parameterId { get; set; }

    public BNES_AuthorController() {
        parameterId = ApexPages.currentPage().getParameters().get('id');
        if (parameterId != 'admin') {
            contactId = ApexPages.currentPage().getParameters().get('id');
        }
    }

    public Contact getAuthor() {
        return [
            SELECT Id, Name, LastName, Salutation, Profile_Picture__c, Bio__c, Account.Name, Levels__c, Username__c
            FROM Contact
            WHERE Id = :contactId
        ];
    }

    public List<Article__c> getAuthorArticles() {
        if (parameterId != 'admin') {
            return [
                SELECT
                    Id,
                    Name,
                    Author__c,
                    Author__r.Name,
                    Author__r.Username__c,
                    Author__r.Account.Name,
                    Author__r.Levels__c,
                    Author__r.Profile_Picture__c,
                    Cover_Photo__c,
                    Article_Preview__c,
                    HTML_Content__c,
                    Content__c,
                    Scheduled_Publish_Date__c,
                    CreatedDate
                FROM Article__c
                WHERE Publish__c = TRUE
                AND Author__c = :contactId
                AND Article_Region__c = '(ES) Spain'
                ORDER BY Scheduled_Publish_Date__c DESC
                LIMIT 5
            ];
        } else {
            return [
                SELECT
                    Id,
                    Name,
                    Author__c,
                    Author__r.Name,
                    Author__r.Username__c,
                    Author__r.Account.Name,
                    Author__r.Levels__c,
                    Author__r.Profile_Picture__c,
                    Cover_Photo__c,
                    Article_Preview__c,
                    HTML_Content__c,
                    Content__c,
                    Scheduled_Publish_Date__c,
                    CreatedDate
                FROM Article__c
                WHERE Publish__c = TRUE
                AND Author__c = NULL
                AND Article_Region__c = '(ES) Spain'
                ORDER BY Scheduled_Publish_Date__c DESC
                LIMIT 5
            ];
        }
    }

    public List<Article__c> getTrendingArticles() {
        return [
            SELECT
                Id,
                Name,
                Author__c,
                Author__r.Name,
                Author__r.Username__c,
                Author__r.Profile_Picture__c,
                Author__r.Show_Author_Page__c,
                Cover_Photo__c,
                Article_Preview__c,
                HTML_Content__c,
                Content__c,
                Scheduled_Publish_Date__c,
                CreatedDate
            FROM Article__c
            WHERE Publish__c = TRUE
            AND Scheduled_Publish_Date__c = LAST_N_DAYS:7
            AND Article_Region__c = '(ES) Spain'
            ORDER BY Total_Views__c DESC
            LIMIT 3
        ];
    }
}