force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <label>Article</label>
    <nameField>
        <label>Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Featured</fullName>
            </value>
            <value>
                <fullName>Trends</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Property Management</fullName>
            </value>
            <value>
                <fullName>Self Storage</fullName>
            </value>
            <value>
                <fullName>Restaurants</fullName>
            </value>
            <value>
                <fullName>CoWorking</fullName>
                <label>Coworking</label>
            </value>
            <value>
                <fullName>Student Housing</fullName>
            </value>
            <value>
                <fullName>Villas</fullName>
            </value>
            <value>
                <fullName>Vacation Rental</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Hostel</fullName>
            </value>
            <value>
                <fullName>Tendencias</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Article__c/fields/Is_Main_Article__c.field-meta.xml
<CustomField>
    <fullName>Is_Main_Article__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Main Article?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Meta_Description__c.field-meta.xml
<CustomField>
    <fullName>Meta_Description__c</fullName>
    <label>Meta Description</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Meta_Title__c.field-meta.xml
<CustomField>
    <fullName>Meta_Title__c</fullName>
    <label>Meta Title</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Publish__c.field-meta.xml
<CustomField>
    <fullName>Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Scheduled_Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Publish_Date__c</fullName>
    <label>Scheduled Publish Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PublishArticleBatch_Test.cls
@isTest
public class PublishArticleBatch_Test {
    
    @isTest static void testProcess(){
    
        List<Article__c> articles = new List<Article__c>();
        for(Integer i = 0; i <= 10; i++) {
            Article__c article = new Article__c(Name = 'Test Article ' + i, Category__c = 'Article', Publish__c = false, Scheduled_Publish_Date__c = Date.Today().addDays(i), Is_Main_Article__c = true, Meta_Title__c = 'Article Title', Meta_Description__c = 'Article Desc');
            articles.add(article);
        }
        insert articles;
        
        Test.startTest();   
          PublishArticleBatch batch = new PublishArticleBatch();
          batch.execute(null, articles);
          batch.start(null);
          batch.finish(null); 
        Test.stopTest();
    }

    @isTest static void testScheduledJob(){
        Test.startTest();
          ScheduledJob job = new ScheduledJob();
          job.execute(null);
        Test.stopTest();
    }    
}