force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <label>Article</label>
    <nameField>
        <label>Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Article_Preview__c.field-meta.xml
<CustomField>
    <fullName>Article_Preview__c</fullName>
    <inlineHelpText>Summary / tldr of the article,</inlineHelpText>
    <label>Article Preview</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Author</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Articles</relationshipLabel>
    <relationshipName>Articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Featured</fullName>
            </value>
            <value>
                <fullName>Trends</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Property Management</fullName>
            </value>
            <value>
                <fullName>Self Storage</fullName>
            </value>
            <value>
                <fullName>Restaurants</fullName>
            </value>
            <value>
                <fullName>CoWorking</fullName>
                <label>Coworking</label>
            </value>
            <value>
                <fullName>Student Housing</fullName>
            </value>
            <value>
                <fullName>Villas</fullName>
            </value>
            <value>
                <fullName>Vacation Rental</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Hostel</fullName>
            </value>
            <value>
                <fullName>Tendencias</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Article__c/fields/Cover_Photo__c.field-meta.xml
<CustomField>
    <fullName>Cover_Photo__c</fullName>
    <label>Cover Photo (URL)</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/HTML_Content__c.field-meta.xml
<CustomField>
    <fullName>HTML_Content__c</fullName>
    <label>HTML Content</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Meta_Description__c.field-meta.xml
<CustomField>
    <fullName>Meta_Description__c</fullName>
    <label>Meta Description</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Meta_Title__c.field-meta.xml
<CustomField>
    <fullName>Meta_Title__c</fullName>
    <label>Meta Title</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Publish__c.field-meta.xml
<CustomField>
    <fullName>Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Scheduled_Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Publish_Date__c</fullName>
    <label>Scheduled Publish Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Region__c.field-meta.xml
<CustomField>
    <fullName>Product_Region__c</fullName>
    <description>Choose product language/region</description>
    <label>Product Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>(BR) Brazil</fullName>
            </value>
            <value>
                <fullName>(EN) English</fullName>
                <default>true</default>
                <label>(EN) English</label>
            </value>
            <value>
                <fullName>(FR) France</fullName>
            </value>
            <value>
                <fullName>(DE) Germany</fullName>
            </value>
            <value>
                <fullName>(PT) Portugal</fullName>
            </value>
            <value>
                <fullName>(ES) Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/**
 * Data Factory to generate records for unit tests
 * @author Alex Tsytsiura
 * @date July 15, 2020
 */

@IsTest
public class TestDataFactory {
    //-------------------------------------------------------------------------
    // Constants
    private final static Id STANDARD_PRICEBOOK_ID = Test.getStandardPricebookId();

    //-------------------------------------------------------------------------
    // Create SObject Utils
    public static List<Account> createAccounts(Integer numberOfRecords) {
        List<Account> result = new List<Account>();

        final Long ind = Datetime.now().getTime();
        for (Integer i = 0; i < numberOfRecords; i++) {
            result.add(new Account(
                    Name = 'TestAcc_' + ind + '#' + i
            ));
        }

        return result;
    }

    public static List<Contact> createContacts(Integer numberOfRecords, final List<Account> accounts) {
        List<Contact> result = new List<Contact>();

        for (Integer i = 0; i < numberOfRecords; i++) {
            final Long ind = Datetime.now().getTime();
            for (Account a : accounts) {
                result.add(new Contact(
                        AccountId = a.Id,
                        FirstName = 'Test',
                        LastName = 'TestCont_' + ind + '#' + i,
                        Email = 'test' + ind + '_' + i + '@example.com',
                        Profile_Picture__c = 'https://example.com/avatar.png'
                ));
            }
        }

        return result;
    }

    public static void createAdminContact() {
        Account account = new Account(
            Name = 'Booking Ninjas'
        );
        insert account;

        Contact contact = new Contact(
            AccountId = account.Id,
            FirstName = 'David',
            LastName = 'Harroch',
            Email = 'david@bookingninjas.com',
            Profile_Picture__c = 'https://example.com/avatar.png'
        );
        insert contact;
    }

    public static List<Opportunity> createOpportunities(Integer numberOfRecords, final List<Account> accounts) {
        List<Opportunity> result = new List<Opportunity>();

        for (Integer i = 0; i < numberOfRecords; i++) {
            final Long ind = Datetime.now().getTime();
            for (Account a : accounts) {
                result.add(new Opportunity(
                        Name = 'TestOpp_' + ind + '#' + i,
                        AccountId = a.Id,
                        StageName = 'Qualification',
                        CloseDate = Date.today()
                ));
            }
        }

        return result;
    }

    public static List<Quote> createQuotes(Integer numberOfRecords, final List<Opportunity> opportunities) {
        List<Quote> result = new List<Quote>();

        for (Integer i = 0; i < numberOfRecords; i++) {
            final Long ind = Datetime.now().getTime();
            for (Opportunity o : opportunities) {
                result.add(new Quote(
                        Name = 'TestQuote_' + ind + '#' + i,
                        OpportunityId = o.Id,
                        Pricebook2Id = STANDARD_PRICEBOOK_ID
                ));
            }
        }

        return result;
    }

    public static List<Product2> createProducts(Integer numberOfRecords) {
        List<Product2> result = new List<Product2>();

        for (Integer i = 0; i < numberOfRecords; i++) {
            final Long ind = Datetime.now().getTime();
            result.add(new Product2(
                    Name = 'TestProd_' + ind + '#' + i,
                    IsActive = true,
                    Product_Region__c = '(EN) English'
            ));
        }

        return result;
    }

    public static void createArticles(Integer numberOfRecords, final List<Contact> contacts) {
        List<Article__c> result = new List<Article__c>();

        for (Integer i = 0; i < numberOfRecords; i++) {
            for (Contact a : contacts) {
                result.add(new Article__c(
                    Name = 'TestArticle_' + i,
                    Author__c = a.Id,
                    Cover_Photo__c = 'https://example.com/thumbnail.png',
                    Article_Preview__c = 'Test preview text',
                    HTML_Content__c = '<p>Article content</p>',
                    Scheduled_Publish_Date__c = Date.today().addDays(-2),
                    Publish__c = true,
                    Category__c = 'Featured',
                    Meta_Title__c = 'Article Title',
                    Meta_Description__c = 'Article description'
                ));
            }
        }

        insert result;
    }

    public static void createArticlesNoAuthor(Integer numberOfRecords) {
        List<Article__c> result = new List<Article__c>();

        for (Integer i = 0; i < numberOfRecords; i++) {
            result.add(new Article__c(
                Name = 'TestArticle_' + i,
                Cover_Photo__c = 'https://example.com/thumbnail.png',
                Article_Preview__c = 'Test preview text',
                HTML_Content__c = '<p>Article content</p>',
                Scheduled_Publish_Date__c = Date.today().addDays(-2),
                Publish__c = true,
                Category__c = 'Featured',
                Meta_Title__c = 'Article Title',
                Meta_Description__c = 'Article description'
            ));
        }

        insert result;
    }

    public static List<QuoteLineItem> createQuoteLineItems(List<Quote> quotes, List<PricebookEntry> entries) {
        List<QuoteLineItem> result = new List<QuoteLineItem>();

        for (Quote q : quotes) {
            for (PricebookEntry e : entries) {
                result.add(new QuoteLineItem(
                        QuoteId = q.Id,
                        PricebookEntryId = e.Id,
                        Quantity = 1,
                        UnitPrice = 100
                ));
            }
        }

        return result;
    }

    //-------------------------------------------------------------------------
    // Utils
    public static List<PricebookEntry> assignProductsToPricebook(List<Product2> products) {
        List<PricebookEntry> result = new List<PricebookEntry>();

        for (Product2 p : products) {
            result.add(new PricebookEntry(
                    Product2Id = p.Id,
                    Pricebook2Id = STANDARD_PRICEBOOK_ID,
                    UnitPrice = 100,
                    IsActive = true
            ));
        }

        insert result;
        return result;
    }
}