force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <label>Article</label>
    <nameField>
        <label>Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Is_Main_Article__c.field-meta.xml
<CustomField>
    <fullName>Is_Main_Article__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Main Article?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Publish__c.field-meta.xml
<CustomField>
    <fullName>Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Scheduled_Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Publish_Date__c</fullName>
    <label>Scheduled Publish Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PublishArticleBatch.cls
global with sharing class PublishArticleBatch implements Database.Batchable<sObject>{

    DateTime dT = System.now();
    Date dateToday = date.newinstance(dT.year(), dT.month(), dT.day());
    
    private PublishArticleService service = new PublishArticleService(); 
    public String query = 'SELECT Id, Name, Is_Main_Article__c, Publish__c, Scheduled_Publish_Date__c FROM Article__c WHERE Publish__c = false AND Scheduled_Publish_Date__c != NULL AND Scheduled_Publish_Date__c = :dateToday';
    
    //Start Method which retrieves the records of case
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }  
    
    global void execute(Database.BatchableContext BC, List<Article__c> records) {
        service.process(records);
    }
    
    global void finish(Database.BatchableContext BC) {
        
    } 
}