force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <label>Article</label>
    <nameField>
        <label>Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Article_Region__c.field-meta.xml
<CustomField>
    <fullName>Article_Region__c</fullName>
    <description>Choose article language/region</description>
    <label>Article Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>(BR) Brazil</fullName>
            </value>
            <value>
                <fullName>(EN) English</fullName>
                <default>true</default>
                <label>(EN) English</label>
            </value>
            <value>
                <fullName>(FR) France</fullName>
            </value>
            <value>
                <fullName>(DE) Germany</fullName>
            </value>
            <value>
                <fullName>(PT) Portugal</fullName>
            </value>
            <value>
                <fullName>(ES) Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Article_Views__c/Article_Views__c.object-meta.xml
<CustomObject>
    <label>Article Views</label>
    <nameField>
        <displayFormat>AV-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article_Views__c/fields/Article__c.field-meta.xml
<CustomField>
    <fullName>Article__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Article</label>
    <referenceTo>Article__c</referenceTo>
    <relationshipLabel>Article Views</relationshipLabel>
    <relationshipName>Article_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article_Views__c/fields/ArticleId__c.field-meta.xml
<CustomField>
    <fullName>ArticleId__c</fullName>
    <label>ArticleId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BNES_ArticleControllerTest.cls
@isTest
private class BNES_ArticleControllerTest {
    @testSetup
    static void setup() {
        List<Account> accounts = TestDataFactory.createAccounts(1);
        insert accounts;
        List<Contact> contacts = TestDataFactory.createContacts(1, accounts);
        insert contacts;
        TestDataFactory.createArticles(5, contacts);

        // add es region
        List<Article__c> articles = new List<Article__c>();
        for (Article__c article : [SELECT Id FROM Article__c]) {
            article.Article_Region__c = '(ES) Spain';
            articles.add(article);
        }
        update articles;
    }

    @isTest
    static void testGetArticles() {
        Id articleId = [SELECT Id FROM Article__c LIMIT 1].Id;
        BNES_ArticleController controller = new BNES_ArticleController();

        Test.startTest();
        controller.articleId = articleId;
        Article__c articleShown = controller.getArticle();
        List<Article__c> trendingArticles = controller.getTrendingArticles();
        Test.stopTest();

        System.assertEquals(articleShown.Id, articleId);
        System.assertEquals(3, trendingArticles.size());
    }

    @isTest
    static void testArticleView() {
        Id articleId = [SELECT Id FROM Article__c LIMIT 1].Id;
        PageReference articlePage = Page.BNES_Article;
        Test.setCurrentPage(articlePage);
        Test.setMock(HttpCalloutMock.class, new IPAPIHttpCalloutMock());
        ApexPages.currentPage().getHeaders().put('True-Client-IP', '192.168.1.1');

        BNES_ArticleController controller = new BNES_ArticleController();

        Test.startTest();
        controller.articleId = articleId;
        controller.saveArticleView();
        Test.stopTest();

        System.assertEquals(1, [SELECT COUNT() FROM Article_Views__c WHERE IP_Address__c = '192.168.1.1']);
        System.assertEquals(1, [SELECT COUNT() FROM Article_Views__c WHERE ArticleId__c = :articleId]);
    }
}