force-app/main/default/objects/Vacancy__c/Vacancy__c.object-meta.xml
<CustomObject>
    <label>Vacancy</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacancy__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Describe what the position entails.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/DetailBannerArt__c.field-meta.xml
<CustomField>
    <fullName>DetailBannerArt__c</fullName>
    <description>The artwork that is displayed in the banner of the detail page.</description>
    <label>Detail Banner Art</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VacancyDetailArt</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/IconArt__c.field-meta.xml
<CustomField>
    <fullName>IconArt__c</fullName>
    <label>Icon Art</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VacancyIconArt</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Intro__c.field-meta.xml
<CustomField>
    <fullName>Intro__c</fullName>
    <description>Short text to describe the position on the grid.</description>
    <label>Intro</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/IsOpen__c.field-meta.xml
<CustomField>
    <fullName>IsOpen__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If unchecked, this job will not be visible to guests.</description>
    <label>Is Open</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Control the order in which the vacancies are rendered on the website.</description>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/OtherInformation__c.field-meta.xml
<CustomField>
    <fullName>OtherInformation__c</fullName>
    <description>Any other information like extra credits goes here.</description>
    <label>Other Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Overview__c.field-meta.xml
<CustomField>
    <fullName>Overview__c</fullName>
    <description>What does the position entail? Each line is rendered as a bullet point.</description>
    <label>Overview</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/Qualifications__c.field-meta.xml
<CustomField>
    <fullName>Qualifications__c</fullName>
    <description>List the requirements for the role. Each line is displayed as a bullet point.</description>
    <label>Qualifications</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vacancy__c/fields/VacancyID__c.field-meta.xml
<CustomField>
    <fullName>VacancyID__c</fullName>
    <displayFormat>JD-{00000}</displayFormat>
    <label>Vacancy ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/BN_VacancyPageController_Test.cls
@isTest private class BN_VacancyPageController_Test {
    private static void insertVacancyRecords(Integer y){
        for(Integer x = 0; x < y; x++){
            Vacancy__c v = new Vacancy__c(
                Name ='Vacancy '+ x, 
                Intro__c='Something',
                DetailBannerArt__c='https://d1b89zc79exfxt.cloudfront.net/img/Account_Executives.png',
                IconArt__c='https://d1b89zc79exfxt.cloudfront.net/img/career-monitor.png',
                Description__c='Something',
                Order__c = x,
                OtherInformation__c = 'Other information',
                Qualifications__c = 'Qualifications',
                Overview__c = 'Overview',
                IsOpen__c = (Math.mod(x, 2) > 0)
            );

            insert v;
        }
    }

    @isTest static void testVacancyIsLoadedBasedOnIdParameter(){
        insertVacancyRecords(5);
        Vacancy__c v = [SELECT Id, Name, VacancyID__c FROM Vacancy__c LIMIT 1];
        Pagereference reference = Page.BN_Career_Detail;

        reference.getParameters().put('id', v.Id);
        Test.setCurrentPage(reference);

        BN_VacancyPageController controller = new BN_VacancyPageController();
        System.assertEquals(v.VacancyID__c, controller.getVacancyID());
    }
}