force-app/main/default/objects/Detailed_Category__c/Detailed_Category__c.object-meta.xml
<CustomObject>
    <label>Detailed Category</label>
    <nameField>
        <label>Detailed Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Detailed Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Detailed_Category__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detailed Category</label>
    <referenceTo>Detailed_Category__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account_LineItem__c/Financial_Account_LineItem__c.object-meta.xml
<CustomObject>
    <label>Financial Account LineItem</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Financial Account LineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account LineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account_LineItem__c/fields/Detailed_Category__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detailed Category</label>
    <referenceTo>Detailed_Category__c</referenceTo>
    <relationshipLabel>Financial Account LineItems</relationshipLabel>
    <relationshipName>Financial_Account_LineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account_LineItem__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Financial Account LineItems</relationshipLabel>
    <relationshipName>Financial_Account_LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Financial_Account_LineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Transactions</fullName>
                <default>true</default>
                <label>New Transactions</label>
            </value>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Excluded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Account_LineItem__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account_LineItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SPENT</fullName>
            </value>
            <value>
                <fullName>RECEIVED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountingDataService.cls
public with sharing class AccountingDataService {
	private static final String AND_CLAUSE = ' AND ';

	public static List<Financial_Account_LineItem__c> getAccountLIList(Date startDate, Date endDate, 
		String status, Id finAccId, Financial_Account_LineItem__c accLI) {
		List<Financial_Account_LineItem__c> accLiList = new List<Financial_Account_LineItem__c>();
    	if(Financial_Account_LineItem__c.SObjectType.getDescribe().isAccessible()){
            status = String.escapeSingleQuotes(status);
			String query = 'SELECT   Id, ' +
								    'Date__c,' +
                           		    'Description__c,' +
                           		    'Detailed_Category__c,' +
                           			'Status__c,' +
                           			'Transaction_Amount__c,' +
                           			'Name,' +
                           			'Type__c  ' +
                           	'From Financial_Account_LineItem__c ' +
                           	'WHERE Status__c =: status ' +
                           	'AND Financial_Account__c =: finAccId' + AND_CLAUSE;

            String description = accLI.Description__c;
            String category = accLI.Detailed_Category__c;
            Decimal amount = accLI.Transaction_Amount__c;
            String typeTransaction = accLI.Type__c;
            System.debug(LoggingLevel.Info ,'description = ' + description);

			if(startDate != null){
				query += 'Date__c >=: startDate' + AND_CLAUSE;
			}
			if(endDate != null){
				query += 'Date__c <=: endDate' + AND_CLAUSE;
			}
			if(category != null){
				category = String.escapeSingleQuotes(category);
				query += 'Detailed_Category__c =: category' + AND_CLAUSE;
			}
			if(amount != null){
				query += 'Transaction_Amount__c =: amount' + AND_CLAUSE;
			}
			if(typeTransaction != null){
				typeTransaction = String.escapeSingleQuotes(typeTransaction);
				query += 'Type__c =: typeTransaction' + AND_CLAUSE;
			}
			if(description != null){
				description = '\'%' + String.escapeSingleQuotes(description)  + '%\'';
				query += 'Description__c LIKE ' + description + AND_CLAUSE;
			}

			if(query.contains(AND_CLAUSE)){
				query = query.removeEnd(AND_CLAUSE);
			}
			accLiList = Database.query(query);
		}
		return accLiList;
	}


	public List<Financial_Account_LineItem__c> getAccountLIListExtended(Date startDate, Date endDate,
			String status, Id finAccId, Financial_Account_LineItem__c accLI) {

		List<Financial_Account_LineItem__c> accLiList = new List<Financial_Account_LineItem__c>();
		if(Financial_Account_LineItem__c.SObjectType.getDescribe().isAccessible()){
			status = String.escapeSingleQuotes(status);
			String query = 'SELECT   Id, ' +
					'Date__c,' +
					'Description__c,' +
					'Detailed_Category__c,' +
					'Detailed_Category__r.Name,' +
					'Status__c,' +
					'Transaction_Amount__c,' +
					'Name,' +
					'Type__c  ' +
					'From Financial_Account_LineItem__c ' +
					'WHERE Status__c =: status ' +
					'AND Financial_Account__c =: finAccId' + AND_CLAUSE;

			String description = accLI.Description__c;
			String category = accLI.Detailed_Category__c;
			Decimal amount = accLI.Transaction_Amount__c;
			String typeTransaction = accLI.Type__c;
			System.debug(LoggingLevel.Info ,'description = ' + description);

			if(startDate != null){
				query += 'Date__c >=: startDate' + AND_CLAUSE;
			}
			if(endDate != null){
				query += 'Date__c <=: endDate' + AND_CLAUSE;
			}
			if(String.isNotBlank(category)){
				category = String.escapeSingleQuotes(category);
				query += 'Detailed_Category__c =: category' + AND_CLAUSE;
			}
			if(amount != null){
				query += 'Transaction_Amount__c =: amount' + AND_CLAUSE;
			}
			if(String.isNotBlank(typeTransaction)){
				typeTransaction = String.escapeSingleQuotes(typeTransaction);
				query += 'Type__c =: typeTransaction' + AND_CLAUSE;
			}
			if(String.isNotBlank(description)){
				description = '\'%' + String.escapeSingleQuotes(description)  + '%\'';
				query += 'Description__c LIKE ' + description + AND_CLAUSE;
			}

			if(query.contains(AND_CLAUSE)){
				query = query.removeEnd(AND_CLAUSE);
			}

			accLiList = Database.query(query);
		}
		return accLiList;
	}
}