force-app/main/default/objects/Detailed_Category__c/Detailed_Category__c.object-meta.xml
<CustomObject>
    <label>Detailed Category</label>
    <nameField>
        <label>Detailed Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Detailed Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Detailed_Category__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detailed Category</label>
    <referenceTo>Detailed_Category__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account_LineItem__c/Financial_Account_LineItem__c.object-meta.xml
<CustomObject>
    <label>Financial Account LineItem</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Financial Account LineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account LineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account_LineItem__c/fields/Detailed_Category__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detailed Category</label>
    <referenceTo>Detailed_Category__c</referenceTo>
    <relationshipLabel>Financial Account LineItems</relationshipLabel>
    <relationshipName>Financial_Account_LineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account_LineItem__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Financial Account LineItems</relationshipLabel>
    <relationshipName>Financial_Account_LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/YodleeDataService.cls
public with sharing class YodleeDataService implements DI{
	public interface DI{
		List<SObject> insertRecords(List<SObject> records);
		Map<String, Financial_Account__c> getFinancialAccountMap(Set<String> bankNames);
		Financial_Account_LineItem__c getLastFinAccItem();
		List<Detailed_Category__c> getDetailedCategoryList();
	}

	public List<SObject> insertRecords(List<SObject> records){
		if( !records.isEmpty() && records.get(0).getSObjectType().getDescribe().isCreateable()){
			Database.insert(records, false);
		}
		return records;
	}	

	public Financial_Account_LineItem__c getLastFinAccItem(){
		List<Financial_Account_LineItem__c> finList = new List<Financial_Account_LineItem__c>();
		if(Financial_Account_LineItem__c.SObjectType.getDescribe().isAccessible()){
			finList.addAll([Select Date__c
						   From Financial_Account_LineItem__c
						   Order By Date__c DESC
						   Limit 1]);
		}
 		return finList.isEmpty() ? new Financial_Account_LineItem__c() : finList.get(0);
	}

	public Map<String, Financial_Account__c> getFinancialAccountMap(Set<String> bankNames){
		List<Financial_Account__c> finAccList = new List<Financial_Account__c>();
		if(! bankNames.isEmpty() && Financial_Account__c.SObjectType.getDescribe().isAccessible()){
			finAccList.addAll([Select Id,
									  Name
							   FROM Financial_Account__c
							   Where Name IN : bankNames]);
		}
		Map<String, Financial_Account__c> nameToAccountMap = new Map<String, Financial_Account__c>();
		for(Financial_Account__c item : finAccList){
			nameToAccountMap.put(item.Name, item);
		}
		return nameToAccountMap;
	}

	public List<Detailed_Category__c> getDetailedCategoryList(){
		List<Detailed_Category__c> categoryList = new List<Detailed_Category__c>();
		if(Detailed_Category__c.SObjectType.getDescribe().isAccessible()){
			categoryList.addAll([Select Name
								From Detailed_Category__c]);
		}
		return categoryList;
	}
}