force-app/main/default/objects/Product2/fields/AnnualDiscount__c.field-meta.xml
<CustomField>
    <fullName>AnnualDiscount__c</fullName>
    <label>Annual Discount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Subscription Fee</fullName>
            </value>
            <value>
                <fullName>Implementation Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Expose_on_site__c.field-meta.xml
<CustomField>
    <fullName>Expose_on_site__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Expose on site</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Features__c.field-meta.xml
<CustomField>
    <fullName>Features__c</fullName>
    <label>Features</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest Management</fullName>
                <label>Gain full control of managing your guests by leveraging our mobile and desktop app.</label>
            </value>
            <value>
                <fullName>Reservation Management</fullName>
                <label>Save up on operational costs by digitizing your reservation calendar for real-time online booking.</label>
            </value>
            <value>
                <fullName>Housekeeping Management</fullName>
                <label>Monitor your staff, assign tasks, systematically handle checklists all from the comfort of your room, office, or wherever.</label>
            </value>
            <value>
                <fullName>User Management</fullName>
                <label>Save money on software license purchases by getting multiple user access, total control, and integration of your whole establishment.</label>
            </value>
            <value>
                <fullName>Inventory Management</fullName>
                <label>Never have an inventory out of place with automated tracking of inventory across multiple channels and devices.</label>
            </value>
            <value>
                <fullName>Availability Hour Grid</fullName>
                <label>Improve room efficiency by managing the availability of your rooms or properties with this powerful and dynamic interface.</label>
            </value>
            <value>
                <fullName>Invoicing + Payment API</fullName>
                <label>Create, send out your invoices, and receive payments without worrying about manual bookkeeping anymore.</label>
            </value>
            <value>
                <fullName>Reporting</fullName>
                <label>Monitor your business statistics online, collect and analyze data to be used to develop future forecasts, marketing plans, and track progress with the latest technology.</label>
            </value>
            <value>
                <fullName>Mobile Apps</fullName>
                <label>Get push notification, instant updates, and instant online access with the Booking Ninjas mobile apps available across android and ios platforms.</label>
            </value>
            <value>
                <fullName>Add-On Features*</fullName>
                <label>Add extensions to the Booking Ninjas core PMS to create an even more customized instance for your business.</label>
            </value>
            <value>
                <fullName>Gestión de Huéspedes</fullName>
                <label>Obtén el control total de la gestión de tus huéspedes sacando provecho de nuestra aplicación para móviles y ordenadores.</label>
            </value>
            <value>
                <fullName>Gestión de Reservas</fullName>
                <label>Ahorra gastos de funcionamiento mediante la digitalización de tu calendario de reservas. Esto incorporará en tiempo real las reservas realizadas de forma online.</label>
            </value>
            <value>
                <fullName>Gestión del Servicio de Limpieza</fullName>
                <label>Controla a tu plantilla, asigna tareas y gestiona las listas de comprobación desde la comodidad de tu habitación, tu oficina o cualquier otro lugar.</label>
            </value>
            <value>
                <fullName>Gestión de Usuarios</fullName>
                <label>Olvídate de comprar licencias de softwares mediante la obtención de acceso para varios usuarios, control total e integración de todo tu establecimiento.</label>
            </value>
            <value>
                <fullName>Gestión del Inventario</fullName>
                <label>Olvídate de tener inventario fuera de lugar gracias al seguimiento automatizado del inventario, a través de varios canales y dispositivos.</label>
            </value>
            <value>
                <fullName>Cuadrícula con Horario de Disponibilidad</fullName>
                <label>Mejora el rendimiento de las habitaciones mediante la gestión de la disponibilidad de tus habitaciones o propiedades y gracias a este interfaz potente y dinámica.</label>
            </value>
            <value>
                <fullName>Facturación + API de Pagos</fullName>
                <label>Crea, envía tus facturas y recibe pagos sin tener que preocuparte más de hacer la contabilidad de forma manual.</label>
            </value>
            <value>
                <fullName>Informes</fullName>
                <label>Monitoriza de forma online las estadísticas de tu negocio, recopila y analiza datos para crear pronósticos, planes de marketing y haz seguimientos con la última tecnología.</label>
            </value>
            <value>
                <fullName>Aplicaciones Móviles</fullName>
                <label>Obtén notificaciones emergentes, actualizaciones de inmediato y acceso online instantáneo con las aplicaciones móviles de Booking Ninjas disponibles en plataformas iOS y Android.</label>
            </value>
            <value>
                <fullName>Complementos *</fullName>
                <label>Añade complementos al PMS central de Booking Ninjas para crear un negocio todavía más personalizado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Hierarchy_Order__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_Order__c</fullName>
    <description>Products hierarchy order on the site</description>
    <label>Hierarchy Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ImplementationDeposit__c.field-meta.xml
<CustomField>
    <fullName>ImplementationDeposit__c</fullName>
    <label>Implementation Deposit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ImplementationFee__c.field-meta.xml
<CustomField>
    <fullName>ImplementationFee__c</fullName>
    <label>Implementation Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MonthlyFee__c.field-meta.xml
<CustomField>
    <fullName>MonthlyFee__c</fullName>
    <label>Monthly Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Region__c.field-meta.xml
<CustomField>
    <fullName>Product_Region__c</fullName>
    <description>Choose product language/region</description>
    <label>Product Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>(BR) Brazil</fullName>
            </value>
            <value>
                <fullName>(EN) English</fullName>
                <default>true</default>
                <label>(EN) English</label>
            </value>
            <value>
                <fullName>(FR) France</fullName>
            </value>
            <value>
                <fullName>(DE) Germany</fullName>
            </value>
            <value>
                <fullName>(PT) Portugal</fullName>
            </value>
            <value>
                <fullName>(ES) Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5-50</fullName>
            </value>
            <value>
                <fullName>50-100</fullName>
            </value>
            <value>
                <fullName>100-500</fullName>
            </value>
            <value>
                <fullName>500-1,500</fullName>
            </value>
            <value>
                <fullName>1,500-4,000</fullName>
            </value>
            <value>
                <fullName>4,000+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BNES_PricingController_Test.cls
@isTest
public with sharing class BNES_PricingController_Test {
    @testSetup
    static void setup() {
        List<Product2> newProductList = new List<Product2>();
        newProductList.add(
            new Product2(
                Name = 'test1',
                AnnualDiscount__c = 'Implementation Fee',
                Features__c = 'Guest Management',
                ImplementationDeposit__c = 50,
                ImplementationFee__c = 500,
                MonthlyFee__c = 125,
                Size__c = '5-50',
                Hierarchy_Order__c = 1,
                Expose_on_site__c = true,
                IsActive = true,
                Product_Region__c = '(ES) Spain'
            )
        );
        insert newProductList;
    }

    @isTest
    static void getProductsTest() {
        Test.startTest();
        List<BNES_PricingController.ProductWrapper> products = BNES_PricingController.getProducts();
        Test.stopTest();
    }

    @isTest
    static void getCurrenciesTest() {
        Test.startTest();
        List<BN_PricingController.CurrencyWrapper> ps = BN_PricingController.getCurrency();
        Test.stopTest();
    }
}