force-app/main/default/objects/Product2/fields/AnnualDiscount__c.field-meta.xml
<CustomField>
    <fullName>AnnualDiscount__c</fullName>
    <label>Annual Discount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Subscription Fee</fullName>
            </value>
            <value>
                <fullName>Implementation Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Features__c.field-meta.xml
<CustomField>
    <fullName>Features__c</fullName>
    <label>Features</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Guest Management</fullName>
                <label>Gain full control of managing your guests by leveraging our mobile and desktop app.</label>
            </value>
            <value>
                <fullName>Reservation Management</fullName>
                <label>Save up on operational costs by digitizing your reservation calendar for real-time online booking.</label>
            </value>
            <value>
                <fullName>Housekeeping Management</fullName>
                <label>Monitor your staff, assign tasks, systematically handle checklists all from the comfort of your room, office, or wherever.</label>
            </value>
            <value>
                <fullName>User Management</fullName>
                <label>Save money on software license purchases by getting multiple user access, total control, and integration of your whole establishment.</label>
            </value>
            <value>
                <fullName>Inventory Management</fullName>
                <label>Never have an inventory out of place with automated tracking of inventory across multiple channels and devices.</label>
            </value>
            <value>
                <fullName>Availability Hour Grid</fullName>
                <label>Improve room efficiency by managing the availability of your rooms or properties with this powerful and dynamic interface.</label>
            </value>
            <value>
                <fullName>Invoicing + Payment API</fullName>
                <label>Create, send out your invoices, and receive payments without worrying about manual bookkeeping anymore.</label>
            </value>
            <value>
                <fullName>Reporting</fullName>
                <label>Monitor your business statistics online, collect and analyze data to be used to develop future forecasts, marketing plans, and track progress with the latest technology.</label>
            </value>
            <value>
                <fullName>Mobile Apps</fullName>
                <label>Get push notification, instant updates, and instant online access with the Booking Ninjas mobile apps available across android and ios platforms.</label>
            </value>
            <value>
                <fullName>Add-On Features*</fullName>
                <label>Add extensions to the Booking Ninjas core PMS to create an even more customized instance for your business.</label>
            </value>
            <value>
                <fullName>Gestión de Huéspedes</fullName>
                <label>Obtén el control total de la gestión de tus huéspedes sacando provecho de nuestra aplicación para móviles y ordenadores.</label>
            </value>
            <value>
                <fullName>Gestión de Reservas</fullName>
                <label>Ahorra gastos de funcionamiento mediante la digitalización de tu calendario de reservas. Esto incorporará en tiempo real las reservas realizadas de forma online.</label>
            </value>
            <value>
                <fullName>Gestión del Servicio de Limpieza</fullName>
                <label>Controla a tu plantilla, asigna tareas y gestiona las listas de comprobación desde la comodidad de tu habitación, tu oficina o cualquier otro lugar.</label>
            </value>
            <value>
                <fullName>Gestión de Usuarios</fullName>
                <label>Olvídate de comprar licencias de softwares mediante la obtención de acceso para varios usuarios, control total e integración de todo tu establecimiento.</label>
            </value>
            <value>
                <fullName>Gestión del Inventario</fullName>
                <label>Olvídate de tener inventario fuera de lugar gracias al seguimiento automatizado del inventario, a través de varios canales y dispositivos.</label>
            </value>
            <value>
                <fullName>Cuadrícula con Horario de Disponibilidad</fullName>
                <label>Mejora el rendimiento de las habitaciones mediante la gestión de la disponibilidad de tus habitaciones o propiedades y gracias a este interfaz potente y dinámica.</label>
            </value>
            <value>
                <fullName>Facturación + API de Pagos</fullName>
                <label>Crea, envía tus facturas y recibe pagos sin tener que preocuparte más de hacer la contabilidad de forma manual.</label>
            </value>
            <value>
                <fullName>Informes</fullName>
                <label>Monitoriza de forma online las estadísticas de tu negocio, recopila y analiza datos para crear pronósticos, planes de marketing y haz seguimientos con la última tecnología.</label>
            </value>
            <value>
                <fullName>Aplicaciones Móviles</fullName>
                <label>Obtén notificaciones emergentes, actualizaciones de inmediato y acceso online instantáneo con las aplicaciones móviles de Booking Ninjas disponibles en plataformas iOS y Android.</label>
            </value>
            <value>
                <fullName>Complementos *</fullName>
                <label>Añade complementos al PMS central de Booking Ninjas para crear un negocio todavía más personalizado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Hierarchy_Order__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_Order__c</fullName>
    <description>Products hierarchy order on the site</description>
    <label>Hierarchy Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ImplementationDeposit__c.field-meta.xml
<CustomField>
    <fullName>ImplementationDeposit__c</fullName>
    <label>Implementation Deposit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ImplementationFee__c.field-meta.xml
<CustomField>
    <fullName>ImplementationFee__c</fullName>
    <label>Implementation Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MonthlyFee__c.field-meta.xml
<CustomField>
    <fullName>MonthlyFee__c</fullName>
    <label>Monthly Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Region__c.field-meta.xml
<CustomField>
    <fullName>Product_Region__c</fullName>
    <description>Choose product language/region</description>
    <label>Product Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>(BR) Brazil</fullName>
            </value>
            <value>
                <fullName>(EN) English</fullName>
                <default>true</default>
                <label>(EN) English</label>
            </value>
            <value>
                <fullName>(FR) France</fullName>
            </value>
            <value>
                <fullName>(DE) Germany</fullName>
            </value>
            <value>
                <fullName>(PT) Portugal</fullName>
            </value>
            <value>
                <fullName>(ES) Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5-50</fullName>
            </value>
            <value>
                <fullName>50-100</fullName>
            </value>
            <value>
                <fullName>100-500</fullName>
            </value>
            <value>
                <fullName>500-1,500</fullName>
            </value>
            <value>
                <fullName>1,500-4,000</fullName>
            </value>
            <value>
                <fullName>4,000+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Settings__c/fields/Is_Live__c.field-meta.xml
<CustomField>
    <fullName>Is_Live__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Live</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stripe_Settings__c/fields/Stripe_Secret_Live_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Live_Key__c</fullName>
    <label>Stripe_Secret_Live_Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Settings__c/fields/Stripe_Secret_Test_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Secret_Test_Key__c</fullName>
    <label>Stripe_Secret_Test_Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BN_InvoiceController.cls
public without sharing class BN_InvoiceController {
    private String crediential {
        get {
            List<Stripe_Settings__c> st = [
                SELECT Is_Live__c, Stripe_Secret_Live_Key__c, Stripe_Secret_Test_Key__c
                FROM Stripe_Settings__c
            ];
            if (st.size() > 0) {
                if (st[0].Is_Live__c) {
                    return st[0].Stripe_Secret_Live_Key__c;
                } else {
                    return st[0].Stripe_Secret_Test_Key__c;
                }
            }
            return '';
        }
    }
    public String title { get; set; }
    public String description { get; set; }
    public String page { get; set; }
    public String ogImage { get; set; }
    public String quoteId { get; set; }
    public ItemWrapper item { get; set; }

    public BN_InvoiceController() {
        quoteId = ApexPages.currentPage().getParameters().get('id');
        item = getQuoteItem();
        title = 'Invoice #' + item.quoteNumber + ' | Booking Ninjas';
        description = 'Invoice #' + item.quoteNumber;
        page = ApexPages.currentPage().getUrl().substringAfter('/').split('\\?')[0];
    }

    public PageReference activateQuote() {
        updateQuote();
        PageReference pr = new PageReference('/thank-you?id=' + quoteId);
        pr.setRedirect(true);
        return pr;
    }

    private void updateQuote() {
        Quote quote = [SELECT Id FROM Quote WHERE Id = :quoteId LIMIT 1];
        quote.Status = 'Active';
        quote.ActivationDate__c = Date.today();
        update quote;
    }

    private ItemWrapper getQuoteItem() {
        QuoteLineItem item = [
            SELECT
                Id,
                Payment_Type__c,
                Product2Id,
                Product2.AnnualDiscount__c,
                Product2.ImplementationDeposit__c,
                Product2.ImplementationFee__c,
                Product2.MonthlyFee__c,
                Product2.Name,
                Product2.Features__c,
                Product2.Size__c,
                Quote.Contact.FirstName,
                Quote.Contact.LastName,
                Quote.Contact.Name,
                Quote.Contact.Account.Name,
                Quote.ContactId,
                Quote.StripeChargeId__c,
                Quote.ExpirationDate,
                Quote.Effective_Date__c,
                Quote.Due_Date__c,
                Quote.QuoteNumber
            FROM QuoteLineItem
            WHERE QuoteId = :quoteId AND Product2.IsActive = TRUE AND Product2.Product_Region__c LIKE '(%'
            ORDER BY Product2.Hierarchy_Order__c ASC
            LIMIT 1
        ];
        Map<String, Object> cardData = getCardData(item.Quote.StripeChargeId__c);
        return new ItemWrapper(item, cardData);
    }

    public class ItemWrapper {
        public String id { get; set; }
        public Date effectiveDate { get; set; }
        public Date dueDate { get; set; }
        public String quoteNumber { get; set; }
        public String contactAccountName { get; set; }
        public String contactFirstName { get; set; }
        public String contactLastName { get; set; }
        public String productId { get; set; }
        public String productName { get; set; }
        public List<String> productFeatures { get; set; }
        public String productSize { get; set; }
        public String billingPeriod { get; set; }
        public Decimal annualyPayment { get; set; }
        public Decimal annualyPaymentOriginal { get; set; }
        public Decimal monthlyPayment { get; set; }
        public Boolean subsFeeDiscountable { get; set; }
        public Decimal subsPayment { get; set; }
        public Decimal subsPaymentOriginal { get; set; }
        public String subsPaymentOriginalText { get; set; }
        public Decimal subsPaymentThree { get; set; }
        public Decimal subsPaymentSix { get; set; }
        public Decimal subsPaymentTwelve { get; set; }
        public Boolean implFeeDiscountable { get; set; }
        public Decimal handleFeePayment { get; set; }
        public Decimal handleFeePaymentOriginal { get; set; }
        public String handleFeePaymentOriginalText { get; set; }
        public String stripeChargeId { get; set; }
        public String cardName { get; set; }
        public String cardNumber { get; set; }
        public String cardExpiredDate { get; set; }

        public ItemWrapper(QuoteLineItem item, Map<String, Object> cardData) {
            this.id = item.Id;
            this.effectiveDate = item.Quote.Effective_Date__c;
            this.dueDate = item.Quote.Due_Date__c;
            this.quoteNumber = item.Quote.QuoteNumber;
            this.contactAccountName = item.Quote.Contact.Account.Name;
            this.contactFirstName = item.Quote.Contact.FirstName;
            this.contactLastName = item.Quote.Contact.LastName;
            this.productId = item.Product2Id;
            this.productName = item.Product2.Name;
            this.productFeatures = new List<String>();
            for (String feature : item.Product2.Features__c.split(';')) {
                this.productFeatures.add(feature);
            }
            this.productSize = item.Product2.Size__c;
            this.billingPeriod = item.Payment_Type__c;
            String discountType = item.Product2.AnnualDiscount__c;
            Boolean isAnnualy = this.billingPeriod == 'Annualy';
            this.subsFeeDiscountable = discountType == 'All' || discountType == 'Subscription Fee';
            this.implFeeDiscountable = discountType == 'All' || discountType == 'Implementation Fee';
            this.monthlyPayment = item.Product2.MonthlyFee__c;
            Decimal discountedSubsFee = this.monthlyPayment - (this.monthlyPayment * 0.2);
            this.annualyPayment = isAnnualy
                ? subsFeeDiscountable ? discountedSubsFee * 12 : this.monthlyPayment * 12
                : null;
            this.annualyPaymentOriginal = this.monthlyPayment * 12;
            this.subsPayment = isAnnualy ? this.annualyPayment : this.monthlyPayment;
            this.subsPaymentOriginal = isAnnualy ? this.monthlyPayment * 12 : this.monthlyPayment;
            this.subsPaymentOriginalText = String.valueOf(this.subsPaymentOriginal);
            this.subsPaymentThree = this.subsPayment / 3;
            this.subsPaymentSix = this.subsPayment / 6;
            this.subsPaymentTwelve = this.subsPayment / 12;
            this.handleFeePaymentOriginal = item.Product2.ImplementationFee__c;
            this.handleFeePaymentOriginalText = String.valueOf(this.handleFeePaymentOriginal);
            Decimal discountedImplFee = this.handleFeePaymentOriginal - (this.handleFeePaymentOriginal * 0.2);
            this.handleFeePayment = isAnnualy
                ? implFeeDiscountable ? discountedImplFee : this.handleFeePaymentOriginal
                : this.handleFeePaymentOriginal;
            this.stripeChargeId = item.Quote.StripeChargeId__c;
            Map<String, String> card = getPaymentMethod(cardData);
            this.cardName = card.get('cardName');
            this.cardNumber = card.get('cardNumber');
            this.cardExpiredDate = card.get('cardExpiration');
        }

        private Map<String, String> getPaymentMethod(Map<String, Object> cardData) {
            if (cardData != null) {
                String month = (String) cardData.get('exp_month');
                String year = (String) cardData.get('exp_year');
                return new Map<String, String>{
                    'cardName' => (String) cardData.get('holder'),
                    'cardNumber' => (String) cardData.get('last4'),
                    'cardExpiration' => month + '/' + year
                };
            } else {
                return new Map<String, String>{
                    'cardName' => 'Teguh Prayoga',
                    'cardNumber' => '4242',
                    'cardExpiration' => '12/2025'
                };
            }
        }
    }

    private Map<String, String> getCardData(String chargeId) {
        Map<String, Object> paymentData = getChargeData(chargeId);
        try {
            Map<String, Object> bd = (Map<String, Object>) paymentData.get('billing_details');
            String cardHolder = (String) bd.get('name');
            Map<String, Object> pm = (Map<String, Object>) paymentData.get('payment_method_details');
            Map<String, Object> card = (Map<String, Object>) pm.get('card');
            Map<String, String> cardData = new Map<String, String>{
                'holder' => cardHolder,
                'exp_month' => String.valueOf((Integer) card.get('exp_month')),
                'exp_year' => String.valueOf((Integer) card.get('exp_year')),
                'last4' => (String) card.get('last4')
            };
            return cardData;
        } catch (Exception e) {
            return null;
        }
    }

    private Map<String, Object> getChargeData(String chargeId) {
        String endPoint = 'https://api.stripe.com/v1/charges/' + chargeId;

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        request.setHeader('Authorization', 'Bearer ' + crediential);
        request.setEndpoint(endPoint);
        request.setMethod('GET');

        Map<String, Object> respMap;
        if (!Test.isRunningTest()) {
            HttpResponse res = http.send(request);
            respMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
        } else {
            respMap = new Map<String, Object>{
                'id' => chargeId,
                'payment_method_details' => new Map<String, Object>{
                    'card' => new Map<String, Object>{
                        'brand' => 'Visa',
                        'exp_month' => 2,
                        'exp_year' => 2022,
                        'last4' => '4242'
                    }
                },
                'billing_details' => new Map<String, Object>{ 'name' => 'Teguh Prayoga' }
            };
        }

        return respMap;
    }
}