force-app/main/default/objects/Category_List__c/Category_List__c.object-meta.xml
<CustomObject>
    <label>Category List</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Detailed_Category__c/Detailed_Category__c.object-meta.xml
<CustomObject>
    <label>Detailed Category</label>
    <nameField>
        <label>Detailed Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Detailed Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detailed_Category__c/fields/Category_List__c.field-meta.xml
<CustomField>
    <fullName>Category_List__c</fullName>
    <label>Category List</label>
    <referenceTo>Category_List__c</referenceTo>
    <relationshipLabel>Detailed Categories</relationshipLabel>
    <relationshipName>Detailed_Categories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expenses__c/Expenses__c.object-meta.xml
<CustomObject>
    <label>Expenses</label>
    <nameField>
        <label>Expenses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expenses__c/fields/Detailed_Category__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detailed Category</label>
    <referenceTo>Detailed_Category__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expenses__c/fields/Related_FA_LineItem__c.field-meta.xml
<CustomField>
    <fullName>Related_FA_LineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related FA LineItem</label>
    <referenceTo>Financial_Account_LineItem__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expenses__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Related_FA_LineItem__r.Status__c )</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <formula>Total_Received__c + Total_Spent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Category_List__c.field-meta.xml
<CustomField>
    <fullName>Category_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category List</label>
    <referenceTo>Category_List__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Detailed_Category__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detailed Category</label>
    <referenceTo>Detailed_Category__c</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Items_To_Reconcile__c.field-meta.xml
<CustomField>
    <fullName>Items_To_Reconcile__c</fullName>
    <label>Items To Reconcile</label>
    <summaryFilterItems>
        <field>Financial_Account_LineItem__c.Status__c</field>
        <operation>equals</operation>
        <value>New Transactions</value>
    </summaryFilterItems>
    <summaryForeignKey>Financial_Account_LineItem__c.Financial_Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Financial_Account_LineItem__c/Financial_Account_LineItem__c.object-meta.xml
<CustomObject>
    <label>Financial Account LineItem</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Financial Account LineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account LineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account_LineItem__c/fields/Detailed_Category__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detailed Category</label>
    <referenceTo>Detailed_Category__c</referenceTo>
    <relationshipLabel>Financial Account LineItems</relationshipLabel>
    <relationshipName>Financial_Account_LineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account_LineItem__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Financial Account LineItems</relationshipLabel>
    <relationshipName>Financial_Account_LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Financial_Account_LineItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Transactions</fullName>
                <default>true</default>
                <label>New Transactions</label>
            </value>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Excluded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Account_LineItem__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account_LineItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SPENT</fullName>
            </value>
            <value>
                <fullName>RECEIVED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>Sales</label>
    <nameField>
        <label>Sales Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales__c/fields/Detailed_Category__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detailed Category</label>
    <referenceTo>Detailed_Category__c</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales__c/fields/Related_FA_LineItem__c.field-meta.xml
<CustomField>
    <fullName>Related_FA_LineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related FA LineItem</label>
    <referenceTo>Financial_Account_LineItem__c</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountingScreenController.cls
public with sharing class AccountingScreenController
{
    public static final String NEW_TRANSACTIONS_STATUS = 'New Transactions';
    public static final String EXCLUDED_STATUS = 'Excluded';
    public static final String RECONSILED_STATUS = 'Reconciled';

    @AuraEnabled(cacheable=true)
    public static List<Financial_Account__c> getFAccountList()
    {
        List<Financial_Account__c> listOfAccounts;

        if (Financial_Account__c.SObjectType.getDescribe().isAccessible()) {
            listOfAccounts = [
                    SELECT Id, Name, Items_To_Reconcile__c, Balance__c
                    FROM   Financial_Account__c
                    LIMIT  50000
            ];
        }

        return listOfAccounts;
    }

    @AuraEnabled(cacheable=true)
    public static List<Detailed_Category__c> getDetailedCategories()
    {
        Set<String> necessaryCategoryNames = new Set<String>
        {
                'Splitted', 'UnCategorized'
        };

        List<Detailed_Category__c> categories = [
                SELECT Id, Name
                FROM  Detailed_Category__c
                WHERE Name IN :necessaryCategoryNames
                LIMIT 10
        ];

        return categories;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, String> getCategoryListDependent()
    {
        Map<String, String> result = new Map<String, String>();

        List<Category_List__c> categoryLists = [
                SELECT Name,
                        (SELECT Name FROM Detailed_Categories__r)
                FROM Category_List__c
                LIMIT 1000
        ];

        for (Category_List__c currentCategoryList : categoryLists)
        {
            for (Detailed_Category__c currentDetailedCategory : currentCategoryList.Detailed_Categories__r)
            {
                result.put(currentDetailedCategory.Id, currentCategoryList.Name + ' | ' + currentDetailedCategory.Name);
            }
        }

        return result;
    }

    @AuraEnabled
    public static RelatedListsWrapper getRelatedLists(Date startDate, Date endDate,
            String finAccId, String description, String detailedCategoryId, String transactionAmount, String type)
    {
        AccountingDataService dataService = new AccountingDataService();
        Financial_Account_LineItem__c accLI = new Financial_Account_LineItem__c();
        accLI.Description__c = description;
        accLI.Detailed_Category__c = String.isNotBlank(detailedCategoryId) ? detailedCategoryId : accLI.Detailed_Category__c;
        accLI.Transaction_Amount__c = String.isNotBlank(transactionAmount) ? Double.valueOf(transactionAmount) : accLI.Transaction_Amount__c;
        accLI.Type__c = type;

        RelatedListsWrapper result = new RelatedListsWrapper();
        result.newTransactions = dataService.getAccountLIListExtended(startDate, endDate, NEW_TRANSACTIONS_STATUS, finAccId, accLI);
        result.reconciled = dataService.getAccountLIListExtended(startDate, endDate, RECONSILED_STATUS, finAccId, accLI);
        result.excluded = dataService.getAccountLIListExtended(startDate, endDate, EXCLUDED_STATUS, finAccId, accLI);

        return result;
    }

    @AuraEnabled
    public static void removeRelatedRecords(List<ID> lineItemIds)
    {
        List<Financial_Account_LineItem__c> accountLineItems = [
                SELECT (SELECT Id FROM Sales__r), (SELECT Id FROM Expenses__r)
                FROM Financial_Account_LineItem__c
                WHERE Id IN :lineItemIds
        ];

        if (!accountLineItems.isEmpty())
        {
            List<SObject> recordsToDelete = new List<SObject>();

            for(Financial_Account_LineItem__c item : accountLineItems){
                recordsToDelete.addAll(item.Sales__r);
                recordsToDelete.addAll(item.Expenses__r);
            }
            
            if (!recordsToDelete.isEmpty())
            {
                delete recordsToDelete;
            }
        }
    }

    @AuraEnabled
    public static void insertSplitItems(List<Map<String, String>> splittedItems)
    {
        Map<String, Schema.SObjectType> sobjectsDescribes = Schema.getGlobalDescribe();
        List<SObject> recordsToInsert = new List<SObject>();

        for (Map<String, String> currentObjectData : splittedItems)
        {
            SObject newRecord = sobjectsDescribes.get(currentObjectData.get('SobjectType')).newSObject();
            currentObjectData.remove('SobjectType');

            for (String fieldName : currentObjectData.keySet())
            {
                if (fieldName == 'Amount__c')
                {
                    newRecord.put(fieldName, Double.valueOf(currentObjectData.get(fieldName)));
                }
                else if (fieldName == 'Date__c')
                {
                    newRecord.put(fieldName, Date.valueOf(currentObjectData.get(fieldName)));
                }
                else
                {
                    newRecord.put(fieldName, currentObjectData.get(fieldName));
                }
            }

            recordsToInsert.add(newRecord);
        }        

        insert recordsToInsert;
    }

    @AuraEnabled
    public static List<Financial_Account_LineItem__c> updateFAccountLineItem(String updateItems, String detailedCategory)
    {
        List<Financial_Account_LineItem__c> itemList = (List<Financial_Account_LineItem__c> )JSON.deserialize(updateItems, List<Financial_Account_LineItem__c>.class);
        List<Financial_Account_LineItem__c> updatedFAItems = new List<Financial_Account_LineItem__c>();
        
        Map<Id, Financial_Account_LineItem__c> mapFALineItems = new Map<Id, Financial_Account_LineItem__c>(itemList);
        Detailed_Category__c detailCategory;
        if(String.isNotEmpty(detailedCategory)){
            detailCategory = [SELECT ID FROM Detailed_Category__c WHERE Id = :detailedCategory LIMIT 1];
        }

        for(Financial_Account_LineItem__c updatedItem : [SELECT ID, Status__c, Detailed_Category__c FROM Financial_Account_LineItem__c WHERE ID IN :mapFALineItems.keySet()]){
            updatedItem.Status__c = mapFALineItems.get(updatedItem.Id).Status__c;
            updatedItem.Detailed_Category__c = detailCategory != null ? detailCategory.Id : updatedItem.Detailed_Category__c;
            updatedFAItems.add(updatedItem);
        }
        update updatedFAItems;
        return updatedFAItems;
    }


    public class RelatedListsWrapper
    {
        @AuraEnabled public List<Financial_Account_LineItem__c> newTransactions;
        @AuraEnabled public List<Financial_Account_LineItem__c> reconciled;
        @AuraEnabled public List<Financial_Account_LineItem__c> excluded;
    }
    
}