force-app/main/default/objects/Stripe_Transaction__c/Stripe_Transaction__c.object-meta.xml
<CustomObject>
    <label>Stripe Transaction</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Stripe Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Transaction__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Transaction description</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Guest_Contact__c.field-meta.xml
<CustomField>
    <fullName>Guest_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Stripe Transactions</relationshipLabel>
    <relationshipName>Stripe_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Receipt_URL__c.field-meta.xml
<CustomField>
    <fullName>Receipt_URL__c</fullName>
    <label>Receipt URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Stripe_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Transaction_Id__c</fullName>
    <description>Track the stripe transaction id for any kind of back tracking</description>
    <label>Stripe Transaction Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/trialEmail__c.field-meta.xml
<CustomField>
    <fullName>trialEmail__c</fullName>
    <description>It&apos;s for trial/pilot page, should not be manually add value.</description>
    <label>trialEmail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/StripeTransactionTriggerTest.cls
@isTest
public class StripeTransactionTriggerTest {

    static testmethod void testCallFlowChange() {
        
        Contact contact = new Contact();
        contact.LastName = 'Teguh';
        contact.Email = 'teguh@bookingninjas.com';
        insert contact;
           
        Stripe_Transaction__c st = new Stripe_Transaction__c();
        st.trialEmail__c = 'teguh@bookingninjas.com';
        st.Stripe_Transaction_Id__c = '123';
        st.Total_Amount__c = 1;
        st.Description__c = 'Desc';
        st.Receipt_URL__c = 'https://bookingninjas.com';
        insert st;
        
        Stripe_Transaction__c stRecord = [SELECT Id, Guest_Contact__c, trialEmail__c FROM Stripe_Transaction__c WHERE Id = :st.Id LIMIT 1];
        
        Test.StartTest();
        System.assertEquals(stRecord.Guest_Contact__c, contact.Id);
        System.assertEquals(stRecord.trialEmail__c, null);
        Test.StopTest();
    }
    
}