force-app/main/default/objects/Stripe_Transaction__c/Stripe_Transaction__c.object-meta.xml
<CustomObject>
    <label>Stripe Transaction</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Stripe Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Transaction__c/fields/Payment_Intent_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Intent_Id__c</fullName>
    <label>Payment Intent Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Receipt_URL__c.field-meta.xml
<CustomField>
    <fullName>Receipt_URL__c</fullName>
    <label>Receipt URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Succeeded</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Partial Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Stripe_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Transaction_Id__c</fullName>
    <description>Track the stripe transaction id for any kind of back tracking</description>
    <label>Stripe Transaction Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StripeWebhook.cls
@RestResource(urlMapping='/stripe/webhook/*')
global class StripeWebhook {

    @HttpPost
    global static void doPost() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        res.responseBody = Blob.valueOf('success');
        res.statusCode = 201;
        Blob body = req.requestBody;
        Map<String, String> webHookInfor = StripeWebhook.extractPaymentInformation(body.toString());
        StripeWebhook.capturePaymentInformation(webHookInfor);
    }
    
    private static Map<String, String> extractPaymentInformation(String response) {
        Map<String, String> webHookInfor = new Map<String, String>();        
        if(String.isNotBlank(response)) {
            String piId = '';
            String receiptUrl = '';
            String stripeTransactionId = '';
            Double totalAmount;
        	Map<String, Object> infor = (Map<String, Object>)JSON.deserializeUntyped(response);
            if(infor.containsKey('type') && 'payment_intent.succeeded'.equals((String)infor.get('type'))) {
                if(infor.containsKey('data')) {
                    Map<String, Object> dataMap = (Map<String, Object>)infor.get('data');
                    if(dataMap.containsKey('object')) {
                        Map<String, Object> objectMap = (Map<String, Object>)dataMap.get('object');
                        //	extract payment intent id, which is the key to cross check this transacion in Salesforce DB
                        piId = (String)objectMap.get('id');
                        webHookInfor.put('piId', piId);
                        
                        //	extract receipt url
                        if(objectMap.containsKey('charges')) {
                            Map<String, Object> chargesMap = (Map<String, Object>)objectMap.get('charges');
                            if(chargesMap.containsKey('data')) {
                                List<Object> dataObject = (List<Object>)chargesMap.get('data');
                                if(dataObject != null && dataObject.size() > 0) {
                                    Map<String, Object> paymentInfor = (Map<String, Object>)dataObject.get(0);
                                    if(paymentInfor.containsKey('receipt_url')) {
                                        receiptUrl = (String)paymentInfor.get('receipt_url');
                                        webHookInfor.put('receiptUrl', receiptUrl);
                                    }
                                    if(paymentInfor.containsKey('id')) {
                                        stripeTransactionId = (String)paymentInfor.get('id');
                                        webHookInfor.put('stripeTransactionId', stripeTransactionId);
                                    }
                                    if(paymentInfor.containsKey('amount')) {
                                        totalAmount = (Double)paymentInfor.get('amount');
                                        totalAmount = totalAmount/100;
                                        webHookInfor.put('totalAmount', String.valueOf(totalAmount));
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        return webHookInfor;
    }
    
    private static void capturePaymentInformation(Map<String, String> infor) {
        Stripe_Transaction__c trans = new Stripe_Transaction__c();
        if(infor != null && !infor.isEmpty()) {
            try{
                trans = [SELECT Id, Stripe_Transaction_Id__c, Total_Amount__C, Status__c, Receipt_URL__c
                         FROM Stripe_Transaction__c
                         WHERE Payment_Intent_Id__c =: infor.get('piId') LIMIT 1];
                trans.Status__c = 'Succeeded';
                trans.Stripe_Transaction_Id__c = infor.get('stripeTransactionId');
                trans.Receipt_URL__c = infor.get('receiptUrl');
                if(String.isNotBlank(infor.get('totalAmount'))) {
                    trans.Total_Amount__c = Double.valueOf(infor.get('totalAmount'));
                }
                
                update trans;
            } catch(Exception ex) {
                System.debug('ERROR : StripeWebhook.capturePaymentInformation() \n' + ex.getMessage());
            }
        }
    }
}