force-app/main/default/objects/Stripe_Transaction__c/Stripe_Transaction__c.object-meta.xml
<CustomObject>
    <label>Stripe Transaction</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Stripe Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Transaction__c/fields/Guest_Contact__c.field-meta.xml
<CustomField>
    <fullName>Guest_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Stripe Transactions</relationshipLabel>
    <relationshipName>Stripe_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Payment_Intent_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Intent_Id__c</fullName>
    <label>Payment Intent Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Receipt_URL__c.field-meta.xml
<CustomField>
    <fullName>Receipt_URL__c</fullName>
    <label>Receipt URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Succeeded</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Partial Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Stripe_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Transaction_Id__c</fullName>
    <description>Track the stripe transaction id for any kind of back tracking</description>
    <label>Stripe Transaction Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StripeWebhookTest.cls
@isTest
public class StripeWebhookTest {

    @testSetup static void setupTestData() {
        Contact con = new Contact(
        	FirstName = 'Test',
            LastName = 'User'
        );
        insert con;
        
    	Stripe_Transaction__c trans = new Stripe_Transaction__c(
        	Payment_Intent_Id__c = 'pi_1GeNGeLJXa2cEwUAJk8NtQ0Q',
            Guest_Contact__c = con.Id
        );
        insert trans;
    }
    
    @isTest static void testWebhook() {
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestUri = 'stripe/services/apexrest/stripe/webhook';
        request.httpMethod = 'GET';
        StaticResource sr = [SELECT Id, Body FROM StaticResource WHERE Name = 'Stripe_Payment_Intent_Response' LIMIT 1];
		request.requestBody = Blob.valueOf(sr.Body.toString());
        RestContext.request = request;
        RestContext.response = response;
        
        Test.startTest();
        	StripeWebhook.doPost();
        Test.stopTest();
        
        Stripe_Transaction__c trans = [SELECT Id, Stripe_Transaction_Id__c, Total_Amount__C, Status__c, Receipt_URL__c
                         FROM Stripe_Transaction__c
                         WHERE Payment_Intent_Id__c = 'pi_1GeNGeLJXa2cEwUAJk8NtQ0Q'];
        System.assertEquals('Succeeded', trans.Status__c);
    }
}