force-app/main/default/objects/Stripe_Transaction__c/Stripe_Transaction__c.object-meta.xml
<CustomObject>
    <label>Stripe Transaction</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Stripe Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Transaction__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Transaction description</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Guest_Contact__c.field-meta.xml
<CustomField>
    <fullName>Guest_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Stripe Transactions</relationshipLabel>
    <relationshipName>Stripe_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Receipt_URL__c.field-meta.xml
<CustomField>
    <fullName>Receipt_URL__c</fullName>
    <label>Receipt URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Succeeded</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Partial Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Stripe_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Transaction_Id__c</fullName>
    <description>Track the stripe transaction id for any kind of back tracking</description>
    <label>Stripe Transaction Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BN_Portal_PaymentHistory_Controller.cls
public class BN_Portal_PaymentHistory_Controller extends BN_Portal_Template_Controller {
    
    public Contact contact {get; set;}
    public List<Stripe_Transaction__c> stripeTransactions {get; set;}
    
    public Date startDate {get; set;}
    public Date endDate {get; set;}
    public String status {get; set;}
    
    public BN_Portal_PaymentHistory_Controller() {
    
        String bnUserId = BN_Portal_UserUtils.getCurrBNUserId();
        
        contact = BN_Portal_UserUtils.getContactByBNUserId(bnUserId);
        
        startDate = Date.Today();
        endDate = Date.Today().addDays(30);
        status = 'All';
        
        search();
    }
    
    private List<Stripe_Transaction__c> getTransactionsByContactId(String contactId, Date startDate, Date endDate, String status) {
        if(status == 'All') {
            return [SELECT Id, Guest_Contact__r.Name, Receipt_URL__c, Stripe_Transaction_Id__c, Description__c, Status__c, Total_Amount__c, CreatedDate FROM Stripe_Transaction__c WHERE Guest_Contact__c = :contactId AND CreatedDate >= :startDate AND CreatedDate <= :endDate];
        }
        else {
            return [SELECT Id, Guest_Contact__r.Name, Receipt_URL__c, Stripe_Transaction_Id__c, Description__c, Status__c, Total_Amount__c, CreatedDate FROM Stripe_Transaction__c WHERE Guest_Contact__c = :contactId AND CreatedDate >= :startDate AND CreatedDate <= :endDate AND Status__c = :status];
        }
        
    }
    
    public void search()
    {
        stripeTransactions = getTransactionsByContactId(contact.Id, startDate, endDate, status);
    }
    
    public List<SelectOption> getStatusList()
    {       
        List<SelectOption> statusList = new List<SelectOption>();
        statusList.add(new SelectOption('All', 'All'));
        statusList.add(new SelectOption('Pending', 'Pending'));
        statusList.add(new SelectOption('Failed', 'Failed'));
        statusList.add(new SelectOption('Succeeded', 'Succeeded'));
        statusList.add(new SelectOption('Refunded', 'Refunded'));
        statusList.add(new SelectOption('Partial Refund', 'Partial Refund'));
        
        return statusList;
    }
}