force-app/main/default/objects/Stripe_Transaction__c/Stripe_Transaction__c.object-meta.xml
<CustomObject>
    <label>Stripe Transaction</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Stripe Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Transaction__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Transaction description</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Payment_Intent_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Intent_Id__c</fullName>
    <label>Payment Intent Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Succeeded</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Partial Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Stripe_Checkout_Session_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Checkout_Session_Id__c</fullName>
    <label>Stripe Checkout Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StripeCheckoutController.cls
public class StripeCheckoutController {

    public String stripeCheckoutSessionId { get; set; }
    public String itemName { get; set; }
    public String itemDescription { get; set; }
    public String amount { get; set; }
    public Integer quantity { get; set; }
    public Stripe_Transaction__c trans { get; set; }
    public String sessionId { get; set; }
    String piId;
    Map<String, String> sessionInfo;
    
    public StripeCheckoutController() {
        trans = new Stripe_Transaction__c(
        	Status__c = 'Pending'
        );
        stripeCheckoutSessionId = ApexPages.currentPage().getParameters().get('session_id');
        //	TODO : need to set the session id from the response and enable Checkout
    }
    
    public void getSessionId() {
        Http ht = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:Stripe/checkout/sessions');
        req.setMethod('POST');
        
        req.setHeader('Content-Type', 'application/x-www-form-urlencoded');        
        
        String body = '';
        String baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        String successUrl = baseUrl + '/apex/StripeCheckout?session_id={CHECKOUT_SESSION_ID}';
        String cancelUrl = baseUrl + '/apex/StripeCheckout';
        
        //	setting amount according to the required format
        if(String.isNotBlank(this.amount)) {
            if(this.amount.contains('.')) {
                String[] priceParts = this.amount.split('\\.');
                if(priceParts[1].length() > 2) {
                    this.amount = priceParts[0] + priceParts[1].substring(0, 2);
                } else if(priceParts[1].length() == 1) {
                    this.amount = this.amount.replace('.', '') + '0';
                } else {
                    this.amount = this.amount.replace('.', '');
                }
            }
        } else {
            this.amount = '00';
        }
        
        body = 'success_url=' + successUrl + 
            	'&cancel_url=' + cancelUrl + 
            	'&payment_method_types[0]=card' +            
            	'&line_items[0][name]=' + this.itemName +
            	'&line_items[0][description]=' + this.itemDescription + 
            	'&line_items[0][amount]=' + this.amount + 
            	'&line_items[0][currency]=usd' +
            	'&line_items[0][quantity]=' + this.quantity;
        req.setBody(body);
        
        HttpResponse resp = ht.send(req);

        extractSessionInfor(resp);
        
    }
    
    private void extractSessionInfor(HttpResponse resp) {
        sessionInfo = new Map<String, String>();
        Map<String, Object> respMap = (Map<String, Object>)JSON.deserializeUntyped(resp.getBody());
        
        if(respMap.containsKey('payment_intent')) {
            piId = (String)respMap.get('payment_intent');
            sessionInfo.put('piId', piId);
        }
        if(respMap.containsKey('id')) {
            sessionId = (String)respMap.get('id');
            sessionInfo.put('sessionId', sessionId);
        }
    }
    
    public void captureTransaction() {
        if(sessionInfo != null && !sessionInfo.isEmpty()) {
            trans.Description__c = this.itemDescription;
            try {
                if(sessionInfo.containsKey('piId'))
                    trans.Payment_Intent_Id__c = sessionInfo.get('piId');
                if(sessionInfo.containsKey('sessionId'))
                    trans.Stripe_Checkout_Session_Id__c = sessionInfo.get('sessionId');
                
                insert trans;
            } catch(Exception ex) {
                System.debug('ERROR : StripeCheckoutController.captureTransaction() \n' + ex.getMessage());
            }
        }
    }
}