force-app/main/default/objects/Stripe_Transaction__c/Stripe_Transaction__c.object-meta.xml
<CustomObject>
    <label>Stripe Transaction</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Stripe Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Transaction__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Transaction description</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Guest_Contact__c.field-meta.xml
<CustomField>
    <fullName>Guest_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guest Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Stripe Transactions</relationshipLabel>
    <relationshipName>Stripe_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Receipt_URL__c.field-meta.xml
<CustomField>
    <fullName>Receipt_URL__c</fullName>
    <label>Receipt URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Succeeded</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Partial Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stripe_Transaction__c/fields/Stripe_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Transaction_Id__c</fullName>
    <description>Track the stripe transaction id for any kind of back tracking</description>
    <label>Stripe Transaction Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StripeRefundExtension.cls
public class StripeRefundExtension {

    public String recordId {get;  set;}
    public Stripe_Transaction__c trans {get; set;}
    public Decimal amount {get; set;}
    
    public StripeRefundExtension(ApexPages.StandardController controller)
    {
        //recordId = (String)controller.getRecord().id;
        recordId = ApexPages.currentPage().getParameters().get('id');
        
        trans = getTransaction(recordId);
        if(trans != null) {
            amount = trans.Total_Amount__c;
        }
    }
    
    private Stripe_Transaction__c getTransaction(string id)
    {
        return [SELECT Id, Stripe_Transaction_Id__c, Total_Amount__c, Description__c, Receipt_URL__c, Status__c, Guest_Contact__r.Name  FROM Stripe_Transaction__c Where  Id = :id];
    }
    
    public void doRefund()
    {
        String errorMessage;
        
        if(String.isNotBlank(trans.Stripe_Transaction_Id__c))
        {
            Integer amountToRefund = Integer.valueOf(amount * 100);
            HttpResponse response = StripeService.getRefund(trans.Stripe_Transaction_Id__c, amountToRefund);
            //Map<String, Object> m = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
            
            if(response.getStatusCode() == 200) 
            {                
                //String parentTransactionId = (String)m.get('id');
                String parentTransactionId = trans.Stripe_Transaction_Id__c;
                
                // update status
                trans.Status__c = amount == trans.Total_Amount__c ? 'Refunded' : 'Partial Refund';
                update trans;
                
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.INFO, 'Transaction successfully refunded! Stripe transaction id : ' + parentTransactionId));
            } 
            else
            {
                //errorMessage = (String)m.get('message');
                errorMessage = 'Please try again.';
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'Error making Stripe refund: ' + errorMessage));
            }          
        }
        else 
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'Stripe Transaction Id is missing!'));
        }
    }
}