force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <label>Webinar</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booking Ninjas</fullName>
            </value>
            <value>
                <fullName>Industry Trends</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Hosted_By__c.field-meta.xml
<CustomField>
    <fullName>Hosted_By__c</fullName>
    <label>Hosted By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Long_Description__c.field-meta.xml
<CustomField>
    <fullName>Long_Description__c</fullName>
    <label>Long Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Recording_URL__c.field-meta.xml
<CustomField>
    <fullName>Recording_URL__c</fullName>
    <label>Recording URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Webinar_End__c.field-meta.xml
<CustomField>
    <fullName>Webinar_End__c</fullName>
    <label>Webinar End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Webinar_Start__c.field-meta.xml
<CustomField>
    <fullName>Webinar_Start__c</fullName>
    <label>Webinar Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/WebinarImageUploaderController_Test.cls
@isTest
public class WebinarImageUploaderController_Test {
	@isTest static void test01(){
        Webinar__c webinar = new Webinar__c(Name = 'Webinar 1', 
                           Category__c = 'Booking Ninjas', 
                           Webinar_Start__c = System.now().addDays(5).addHours(1), 
                           Webinar_End__c = System.now().addDays(5).addHours(2), 
                           Hosted_By__c = 'David Harroch, CEO of Booking Ninjas', Short_Description__c = 'Test message', Long_Description__c = 'Long message here', 
                           Recording_URL__c = 'https://www.youtube.com/watch?v=cff2_gEO8PE');
                               
        insert webinar;
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        ContentVersion contentVersion_1 = new ContentVersion(
            Title='Header_Picture1', 
            PathOnClient ='/Header_Picture1.jpg',
            VersionData = bodyBlob, 
            origin = 'H'
        );
        insert contentVersion_1;
       
        ContentVersion contentVersion_2 = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion_1.Id LIMIT 1];
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = webinar.id;
        contentlink.contentdocumentid = contentVersion_2.contentdocumentid;
        contentlink.ShareType = 'V';
        insert contentlink;
        
        WebinarImageUploaderController.updatePicturePath(webinar.id);
        
        System.assertEquals(documents.size(), 1);
        System.assertEquals(documents[0].Id, contentVersion_2.ContentDocumentId);
        System.assertEquals(documents[0].LatestPublishedVersionId, contentVersion_2.Id);
        System.assertEquals(documents[0].Title, contentVersion_2.Title);
        System.assertEquals(contentlink.ContentDocumentId,contentVersion_2.ContentDocumentId );
        
        documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        delete documents;
    }
}