force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <label>Webinar</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar__c/fields/Long_Description__c.field-meta.xml
<CustomField>
    <fullName>Long_Description__c</fullName>
    <label>Long Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Webinar_End__c.field-meta.xml
<CustomField>
    <fullName>Webinar_End__c</fullName>
    <label>Webinar End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Webinar_Start__c.field-meta.xml
<CustomField>
    <fullName>Webinar_Start__c</fullName>
    <label>Webinar Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Webinar_Registration__c/Webinar_Registration__c.object-meta.xml
<CustomObject>
    <label>Webinar Registration</label>
    <nameField>
        <displayFormat>WR-{000000}</displayFormat>
        <label>Registration No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webinar Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar_Registration__c/fields/LinkedIn_URL__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_URL__c</fullName>
    <label>LinkedIn_URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Webinar_Registration__c/fields/Webinar__c.field-meta.xml
<CustomField>
    <fullName>Webinar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Webinar</label>
    <referenceTo>Webinar__c</referenceTo>
    <relationshipLabel>Webinar Registrations</relationshipLabel>
    <relationshipName>Webinar_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Webinar_Registration__c/fields/Webinar_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Webinar_Schedule__c</fullName>
    <label>Webinar Schedule</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BN_WebinarSingle.cls
public with sharing class BN_WebinarSingle {

    public Webinar__c webinar {get; set;}
    public String name {get; set;}
    public String email {get; set;}
    public String phone {get; set;}
    public String linkedURL {get; set;}
    public String webinarDate {get; set;}
    public String webinarTime {get; set;}
    
    public BN_WebinarSingle(){
        this.name = '';
        this.email = '';
        this.phone = '';
        this.linkedURL = '';

        this.webinar = [SELECT Id, Short_Description__c, Long_Description__c, Name, Date__c, Time__c, Webinar_Start__c, Webinar_End__c
                        FROM Webinar__c
                        WHERE Id =: ApexPages.currentPage().getParameters().get('id')
                       ];

        this.webinarDate = webinar.Webinar_Start__c.format('MM/dd/YYYY');
        this.webinarTime = webinar.Webinar_Start__c.format('hh:mm a');
    }
    
    public PageReference saveYourSeat(){
        Integer index = name.indexOf(' ');
        insert new Webinar_Registration__c(First_Name__c = index > -1 ? name.substring(0, index) : null,
                                           Last_Name__c = index > -1 ? name.substring(index, name.length()) : name,
                                           Email__c = email,
                                           Phone__c = phone,
                                           LinkedIn_URL__c = linkedURL,
                                           Webinar_Schedule__c = webinar.Date__c,
                                           Webinar__c = webinar.Id
                                          );
        
        // send email notification
        sendEmailNotif();
        
        // redirect to thank you  page
        PageReference pageRef = new PageReference('/apex/BN_WebinarThankYou?webinarId=' + webinar.Id);
        pageRef.setRedirect(true);
        return pageRef;
    }

    private void sendEmailNotif(){
        String title = webinar.Name;

        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.toAddresses = new List<String>{email};
        message.setccAddresses(new List<String>{'david@bookingninjas.com'});
        message.optOutPolicy = 'FILTER';
        message.subject = 'Thank you for your interest in our Booking Ninjas Webinar - ' + title;
        message.setHtmlBody('This letter is confirmation that we have received your seat reservation for our webinar entitled: ' + title + '! <br/> This webinar is scheduled on ' + webinarDate + ' at ' + webinar.Webinar_Start__c.format('hh:mm a') + ' to ' + webinar.Webinar_End__c.format('hh:mm a') + '. <br/> We appreciate your interest in joining our webinar. <br/><br/> Best regards, <br/> David M. Harroch <br/> Founder and CEO <br/> Booking Ninjas');
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{message});
    }
}