force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <label>Webinar</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booking Ninjas</fullName>
            </value>
            <value>
                <fullName>Industry Trends</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Hosted_By__c.field-meta.xml
<CustomField>
    <fullName>Hosted_By__c</fullName>
    <label>Hosted By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Long_Description__c.field-meta.xml
<CustomField>
    <fullName>Long_Description__c</fullName>
    <label>Long Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Webinar_End__c.field-meta.xml
<CustomField>
    <fullName>Webinar_End__c</fullName>
    <label>Webinar End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Webinar_Start__c.field-meta.xml
<CustomField>
    <fullName>Webinar_Start__c</fullName>
    <label>Webinar Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Webinar_Registration__c/Webinar_Registration__c.object-meta.xml
<CustomObject>
    <label>Webinar Registration</label>
    <nameField>
        <displayFormat>WR-{000000}</displayFormat>
        <label>Registration No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webinar Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar_Registration__c/fields/Webinar__c.field-meta.xml
<CustomField>
    <fullName>Webinar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Webinar</label>
    <referenceTo>Webinar__c</referenceTo>
    <relationshipLabel>Webinar Registrations</relationshipLabel>
    <relationshipName>Webinar_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BN_WebinarSingle_Test.cls
@isTest
private class BN_WebinarSingle_Test {
    
    @isTest
    static void tester(){
        Webinar__c webinar = new Webinar__c(Name = 'Webinar 1',
                                            Category__c = 'Booking Ninjas',
                                            Webinar_Start__c = Datetime.now().addDays(10).addHours(1),
                                            Webinar_End__c = Datetime.now().addDays(10).addHours(2),
                                            Hosted_By__c = 'David Harroch, CEO of Booking Ninjas',
                                            Short_Description__c = 'Test message',
                                            Long_Description__c = 'Long message here'
                                           );
        insert webinar;

        Test.startTest();
        
        PageReference pageRef = Page.BN_WebinarSingle;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', webinar.Id);
        
        BN_WebinarSingle obj = new BN_WebinarSingle();
        obj.name = 'Joe';
        obj.email = 'joe@email.com';
        obj.phone = '05554443322';
        obj.linkedURL = 'www.linkedIn.com/testuser123.com';
        obj.saveYourSeat();
        
        Test.stopTest();

        System.assertEquals(1, [SELECT COUNT() FROM Webinar_Registration__c]);
    }
}