force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <label>Webinar</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booking Ninjas</fullName>
            </value>
            <value>
                <fullName>Industry Trends</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Hosted_By__c.field-meta.xml
<CustomField>
    <fullName>Hosted_By__c</fullName>
    <label>Hosted By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Long_Description__c.field-meta.xml
<CustomField>
    <fullName>Long_Description__c</fullName>
    <label>Long Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Recording_URL__c.field-meta.xml
<CustomField>
    <fullName>Recording_URL__c</fullName>
    <label>Recording URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Short_Description__c.field-meta.xml
<CustomField>
    <fullName>Short_Description__c</fullName>
    <label>Short Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Webinar_End__c.field-meta.xml
<CustomField>
    <fullName>Webinar_End__c</fullName>
    <label>Webinar End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Webinar_Start__c.field-meta.xml
<CustomField>
    <fullName>Webinar_Start__c</fullName>
    <label>Webinar Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Webinar_Registration__c/Webinar_Registration__c.object-meta.xml
<CustomObject>
    <label>Webinar Registration</label>
    <nameField>
        <displayFormat>WR-{000000}</displayFormat>
        <label>Registration No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webinar Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar_Registration__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webinar_Registration__c/fields/Webinar__c.field-meta.xml
<CustomField>
    <fullName>Webinar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Webinar</label>
    <referenceTo>Webinar__c</referenceTo>
    <relationshipLabel>Webinar Registrations</relationshipLabel>
    <relationshipName>Webinar_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Webinar_Registration__c/fields/Webinar_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Webinar_Schedule__c</fullName>
    <label>Webinar Schedule</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BN_WebinarsController_Test.cls
@isTest
public with sharing class BN_WebinarsController_Test {
    
    @testSetup static void setup()
    {
        //Webinar_Start__c, Webinar_End__c
        List<Webinar__c> webinar = new List<Webinar__c>{
            new Webinar__c(Name = 'Webinar 1', Category__c = 'Booking Ninjas', Webinar_Start__c = System.now().addDays(5).addHours(1), Webinar_End__c = System.now().addDays(5).addHours(2), Hosted_By__c = 'David Harroch, CEO of Booking Ninjas', Short_Description__c = 'Test message', Long_Description__c = 'Long message here', Recording_URL__c = 'https://www.youtube.com/watch?v=cff2_gEO8PE'),
            new Webinar__c(Name = 'Webinar 2', Category__c = 'Booking Ninjas', Webinar_Start__c = System.now().addDays(10).addHours(1), Webinar_End__c = System.now().addDays(5).addHours(10), Hosted_By__c = 'David Harroch, CEO of Booking Ninjas', Short_Description__c = 'Test message', Long_Description__c = 'Long message here'),
            new Webinar__c(Name = 'Webinar 3', Category__c = 'Booking Ninjas', Webinar_Start__c = System.now().addDays(15).addHours(1), Webinar_End__c = System.now().addDays(5).addHours(15), Hosted_By__c = 'David Harroch, CEO of Booking Ninjas', Short_Description__c = 'Test message', Long_Description__c = 'Long message here'),
            new Webinar__c(Name = 'Webinar 4', Category__c = 'Booking Ninjas', Webinar_Start__c = System.now().addDays(20).addHours(1), Webinar_End__c = System.now().addDays(5).addHours(20), Hosted_By__c = 'David Harroch, CEO of Booking Ninjas', Short_Description__c = 'Test message', Long_Description__c = 'Long message here'),
            new Webinar__c(Name = 'Webinar 5', Category__c = 'Booking Ninjas', Webinar_Start__c = System.now().addDays(25).addHours(1), Webinar_End__c = System.now().addDays(5).addHours(25), Hosted_By__c = 'David Harroch, CEO of Booking Ninjas', Short_Description__c = 'Test message', Long_Description__c = 'Long message here')
        };
        insert webinar;
        
        Webinar_Registration__c registration = new Webinar_Registration__c();
        registration.First_Name__c = 'David';
        registration.Last_Name__c = 'Harroch';
        registration.Email__c = 'david@bookingninjas.com';
        registration.Phone__c = '+19176002345';
        registration.Business__c = 'Company A';
        registration.Country__c = 'United States';
        registration.Webinar_Schedule__c = webinar[0].Date__c;
        registration.Webinar__c = webinar[0].Id;
        insert registration;
    }
    
    static testMethod void testListAllWebinars() 
    {
        Test.startTest();
            PageReference pageRef = Page.BN_Webinars;
            Test.setCurrentPage(pageRef);
            
            BN_WebinarsController ctrl = new BN_WebinarsController();
            List<BN_WebinarsController.Webinar> webinars = ctrl.getWebinarList();
            List<BN_WebinarsController.Webinar> webinarsOld = ctrl.getRecordingList();
        Test.stopTest();

        System.assertNotEquals(null, webinars);
        System.assertNotEquals(null, webinarsOld);
    }
    
    static testMethod void testRegister() 
    {
        List<Webinar__c> webinar = [SELECT Id, Name FROM Webinar__c];
        Test.startTest();
            PageReference pageRef = Page.BN_Webinars;
            Test.setCurrentPage(pageRef);
            BN_WebinarsController ctrl = new BN_WebinarsController();
            //Webinar__c webinar = [SELECT Id, Name, Date__c, Webinar_Start__c, Webinar_End__c FROM Webinar__C LIMIT 1];
            String webinarName = ApexPages.currentPage().getParameters().put('webinar', webinar[0].Name);
            ctrl.firstName = 'Joe';
            ctrl.email = 'joe@email.com';
            ctrl.webinarName = webinar[0].Name;
            ctrl.saveYourSeat();
            ctrl.getWebinarTopic();
        	ctrl.toWebinarSinglePage();
        Test.stopTest();
    }
}