force-app/main/default/objects/Opportunity/fields/Contact_2__c.field-meta.xml
<CustomField>
    <fullName>Contact_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 2)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_3__c.field-meta.xml
<CustomField>
    <fullName>Contact_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 3</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 3)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_4__c.field-meta.xml
<CustomField>
    <fullName>Contact_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 4</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 4)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_5__c.field-meta.xml
<CustomField>
    <fullName>Contact_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact 5</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact 5)</relationshipLabel>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GenerateQuotePDFPassthroughController.cls
public with sharing class GenerateQuotePDFPassthroughController {
    //private final Id QuoteId = (Id) ApexPages.currentPage().getParameters().get('quoteId');
    private final Id QuotePDFTemplateId = (Id)Label.QuotePDFTemplate;
    Private Quote Quote;
    Private String quoteAttachmentName;
    Private List<String> ccAddresses;
    
    public void GenerateQuotePDFAndRedirectToQuotePage(id QuoteID) {
         Quote = [select id, name, ContactID, Contact.Email, Contact_2__c, Contact_2__r.Email, Contact_3__c, Contact_3__r.Email, Contact_4__c, Contact_4__r.Email, Contact_5__c, Contact_5__r.Email, OpportunityID, Opportunity.name from Quote where id = :QuoteId limit 1];
         quoteAttachmentName = (String)Quote.Opportunity.name + '_' + quote.name;
         String emailID = quote.Contact.Email;
         
         ccAddresses = new List<String>();
         if(Quote.Contact_2__c != null) {
             ccAddresses.add(Quote.Contact_2__r.Email);
         }
         else if(Quote.Contact_3__c != null) {
             ccAddresses.add(Quote.Contact_3__r.Email);
         }
         else if(Quote.Contact_4__c != null) {
             ccAddresses.add(Quote.Contact_4__r.Email);
         }
         else if(Quote.Contact_5__c != null) {
             ccAddresses.add(Quote.Contact_5__r.Email);
         }

        GenerateQuoteDocument(QuoteId, emailID);
    }

    private void GenerateQuoteDocument(Id quotesId, String emailID) {
        String quoteURL = '/quote/quoteTemplateDataViewer.apexp?id=' + quotesId
                          + '&headerHeight=190&footerHeight=188&summlid=' + QuotePDFTemplateId
                          + '#toolbar=1&navpanes=0&zoom=90';
        System.debug('quoteURL==' + quoteURL);
        PageReference pageReferenceForPDF = new PageReference(quoteURL);
        System.debug('Here');

        QuoteDocument newQuoteDocument = new QuoteDocument();
        Blob renderedPDF;
        renderedPDF = Test.isRunningTest()==true? Blob.valueOf('BLob when occur error'):pageReferenceForPDF.getContentAsPDF();
        newQuoteDocument.Document = renderedPDF;
        newQuoteDocument.QuoteId = quotesId;
        INSERT newQuoteDocument;
        
        if (emailID != null && emailID != '') {
            List<String> emailIDs = new List<String>();
            emailIDs.add(emailID);
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            Messaging.EmailFileAttachment efa1 = new Messaging.EmailFileAttachment();
            efa1.setFileName(quoteAttachmentName+'.pdf');
            efa1.setBody(renderedPDF);
            EmailTemplate et =[Select id from EmailTemplate where DeveloperName=:'Quotes_Email'];
            email.setTemplateId(et.id);
            email.setTargetObjectId(quote.ContactID);
            email.setWhatID(quote.opportunityid);
            email.setToAddresses( EmailIds);
            if (ccAddresses != null && ccAddresses.size() > 0)
            {
                email.setccAddresses(ccAddresses);
            }
            email.setBccSender(true);
            email.setFileAttachments(new Messaging.EmailFileAttachment[] {efa1});
            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});   
            System.debug('quoteURL==' + quoteURL);
        }
    }
}