force-app/main/default/objects/Opportunity/fields/ESignGenie_FolderId__c.field-meta.xml
<CustomField>
    <fullName>ESignGenie_FolderId__c</fullName>
    <description>Technical field - hold e-Sign Genie&apos;s related folder Id</description>
    <label>ESignGenie FolderId</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmbedESignPopupController.cls
public    class EmbedESignPopupController {
    @AuraEnabled
    public static String getEmbedSessionURL(Id recordId) {
        try {
            ESignEmbedService service = new ESignEmbedService();
            return service.invokeCreateFolderRequest(recordId);
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static void attachDocument(Id recordId, Id contId, Integer folderId){
        try {
            ESignEmbedService service = new ESignEmbedService();
            service.checkDocSign(recordId, contId, folderId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Opportunity getOpp(Id recordId){
        try {
            return [SELECT Id, Primary_Contact__c, ESignGenie_FolderId__c FROM Opportunity WHERE Id =:recordId ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


}