force-app/main/default/objects/Opportunity/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Preferred_Date__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Date__c</fullName>
    <label>Preferred Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Preferred_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Date_Time__c</fullName>
    <label>Preferred Date &amp; Time (EST)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Preferred_Time__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Time__c</fullName>
    <label>Preferred Time (EST)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>8:00 AM</fullName>
            </value>
            <value>
                <fullName>9:00 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM</fullName>
            </value>
            <value>
                <fullName>3:00 PM</fullName>
            </value>
            <value>
                <fullName>4:00 PM</fullName>
            </value>
            <value>
                <fullName>5:00 PM</fullName>
            </value>
            <value>
                <fullName>6:00 PM</fullName>
            </value>
            <value>
                <fullName>7:00 PM</fullName>
            </value>
            <value>
                <fullName>8:00 PM</fullName>
            </value>
            <value>
                <fullName>9:00 PM</fullName>
            </value>
            <value>
                <fullName>10:00 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <businessProcess>Client</businessProcess>
    <label>Client</label>
</RecordType>

force-app/main/default/classes/RequestDemoController.cls
public without sharing class RequestDemoController {
    String recId;
    public Lead lead {get; set;}
    public Opportunity opp {get; set;}
    public Contact con {get; set;}
    public Contact admin {get; set;}
    public String StdObject {get; set;}
    public String Name {get; set;}
    public String Email {get; set;}
    public String Phone {get; set;}
    public DateTime PreferredDateTime {get; set;}
    public String Message {get; set;}
    public EmailTemplate etClient {get; set;}
    public EmailTemplate etAdmin {get; set;}
        
    public RequestDemoController(){
    
        recId = ApexPages.currentPage().getParameters().get('id');
        String prefix = String.valueOf(recId).substring(0,3);
        if(prefix == '00Q') {
            lead = [Select Id, Name, FirstName, LastName, Email, Phone, LeadSource, Preferred_Date__c, Preferred_Time__c, Message__c, IP_Address__c from Lead where id =: recId];
            StdObject = 'Lead';
            Name = lead.Name;
            Email = lead.Email;
            Phone = lead.Phone;
            etAdmin = [Select Id, Name from EmailTemplate where name = 'Request Demo Response Admin - Lead' limit 1]; //email template for response admin
        }
        else if (prefix == '003') {
            con = [Select Id, Name, FirstName, LastName, Email, Phone, IsPersonAccount, Preferred_Date__c, Preferred_Time__c, Message__c, IP_Address__c from Contact where id =: recId];
            StdObject = 'Contact';
            Name = con.Name;
            Email = con.Email;
            Phone = con.Phone;
            etAdmin = [Select Id, Name from EmailTemplate where name = 'Request Demo Response Admin - Contact' limit 1]; //email template for response admin
        }
        else if (prefix == '006') {
            opp = [Select Id, Primary_Contact__c, Primary_Contact__r.Name, Primary_Contact__r.FirstName, Primary_Contact__r.LastName, Primary_Contact__r.Email, Primary_Contact__r.Phone, LeadSource, Preferred_Date__c, Preferred_Time__c, Message__c from Opportunity where id =: recId];
            StdObject = 'Opportunity';
            Name = opp.Primary_Contact__r.Name;
            Email = opp.Primary_Contact__r.Email;
            Phone = opp.Primary_Contact__r.Phone;
            etAdmin = [Select Id, Name from EmailTemplate where name = 'Request Demo Response Admin - Opportunity' limit 1]; //email template for response admin
        }
        
        etClient = [Select Id, Name from EmailTemplate where name = 'Request Demo Response Client' limit 1]; //email template for response client
        
        PreferredDateTime = null;
        Message = '';
    }
    
    public PageReference SaveForm() 
    {
        if(StdObject == 'Lead')
        {
            lead.Preferred_Date_Time__c = PreferredDateTime;
            lead.Message__c = Message;
            lead.IP_Address__c = GetUserIPAddress();
            update lead;

            System.Debug('Lead==='+lead);
        }
        else if(StdObject == 'Contact')
        {
            con.Preferred_Date_Time__c = PreferredDateTime;
            con.Message__c = Message;
            con.IP_Address__c = GetUserIPAddress();
            update con;
            
            System.Debug('Contact==='+con);
        }
        else if(StdObject == 'Opportunity')
        {
            opp.Preferred_Date_Time__c = PreferredDateTime;
            opp.Message__c = Message;
            update opp;
            
            System.Debug('Opportunity==='+opp);
        }
        
        SendEmailToAdmin();
        SendEmailToClient();
        
        PageReference p = new Pagereference('/apex/Response?id=' + recId);
        p.setRedirect(true);
        return p;
    }
    
    public void SendEmailToAdmin()
    {
        //sends an email
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setUseSignature(false);
        mail.setToAddresses(new string[]{ 'david@bookingninjas.com' });
        if(StdObject == 'Lead') {
            mail.setTargetObjectId(lead.Id);
        }
        else if (StdObject == 'Contact') {
            mail.setTargetObjectId(con.Id);
        }
        else if (StdObject == 'Opportunity') {
            mail.setTargetObjectId(opp.Primary_Contact__c);
            mail.setWhatId(opp.Id);
        }
        mail.setTemplateId(etAdmin.Id);
        mail.setTreatTargetObjectAsRecipient(false);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    
    public void SendEmailToClient()
    {
        //sends an email
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setUseSignature(false);
        if(StdObject == 'Lead') {
            mail.setTargetObjectId(lead.Id);
            mail.setSaveAsActivity(true);
            //mail.setWhatId(lead.Id);
        }
        else if (StdObject == 'Contact') {
            mail.setTargetObjectId(con.Id);
            mail.setSaveAsActivity(true);
            //mail.setWhatId(con.Id);
        }
        else if (StdObject == 'Opportunity') {
            mail.setTargetObjectId(opp.Primary_Contact__c);
            mail.setSaveAsActivity(true);
            mail.setWhatId(opp.Id);
        }
        mail.setTemplateId(etClient.Id);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    
    public String GetUserIPAddress() {
        string ReturnValue = '';
        
        ReturnValue = ApexPages.currentPage().getHeaders().get('True-Client-IP');
        if (ReturnValue == '' || ReturnValue == null) {
            ReturnValue = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');
        }
        System.Debug('IP: ' + ReturnValue);
        return ReturnValue;
    }
}