force-app/main/default/objects/Opportunity/fields/Monthly_Price__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Price__c</fullName>
    <label>Monthly Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/One_Time_Payment__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Payment__c</fullName>
    <label>One Time Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AnnualDiscount__c.field-meta.xml
<CustomField>
    <fullName>AnnualDiscount__c</fullName>
    <label>Annual Discount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Subscription Fee</fullName>
            </value>
            <value>
                <fullName>Implementation Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Hierarchy_Order__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_Order__c</fullName>
    <description>Products hierarchy order on the site</description>
    <label>Hierarchy Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ImplementationDeposit__c.field-meta.xml
<CustomField>
    <fullName>ImplementationDeposit__c</fullName>
    <label>Implementation Deposit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ImplementationFee__c.field-meta.xml
<CustomField>
    <fullName>ImplementationFee__c</fullName>
    <label>Implementation Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MonthlyFee__c.field-meta.xml
<CustomField>
    <fullName>MonthlyFee__c</fullName>
    <label>Monthly Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Region__c.field-meta.xml
<CustomField>
    <fullName>Product_Region__c</fullName>
    <description>Choose product language/region</description>
    <label>Product Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>(BR) Brazil</fullName>
            </value>
            <value>
                <fullName>(EN) English</fullName>
                <default>true</default>
                <label>(EN) English</label>
            </value>
            <value>
                <fullName>(FR) France</fullName>
            </value>
            <value>
                <fullName>(DE) Germany</fullName>
            </value>
            <value>
                <fullName>(PT) Portugal</fullName>
            </value>
            <value>
                <fullName>(ES) Spain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BN_CheckoutSucceedControllerTest.cls
@isTest
public with sharing class BN_CheckoutSucceedControllerTest {

    private static Account account;
    private static Contact contact;
    private static String invoiceId;
    private final static Id STANDARD_PRICEBOOK_ID = Test.getStandardPricebookId();
    
    static {
        account = new Account();
        account.Name =  'Booking Ninjas';
        insert account;
        
        contact = new Contact();
        contact.LastName = 'Harroch';
        contact.FirstName = 'David';
        contact.Email = 'testdavid@bookingninjas.com';
        contact.AccountId = account.Id;
        insert contact;

        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            Type = 'New Business',
            AccountId = account.Id,
            Primary_Contact__c = contact.Id,
            CloseDate = Date.today().addDays(5),
            StageName = 'Working'
        );
        insert opp;

        Quote quot = new Quote(
            Name = 'Test Quote',
            OpportunityId = opp.Id,
            Due_Now__c = 120,
            Grand_Total__c = 120,
            One_Time_Payment__c = 120,
            Monthly_Price__c = 45,
            AnnualyPayment__c = 0,
            ExpirationDate = Date.today().addDays(7),
            Due_Date__c = Date.today().addDays(7)
        );
        insert quot;
        invoiceId = quot.Id;

        Product2 product = new Product2(
            Name = 'Extra Small',
            Hierarchy_Order__c = 1,
            Description = 'X-Tra small package',
            Product_Region__c = '(EN) English',
            AnnualDiscount__c = 'All',
            ImplementationDeposit__c = 30,
            ImplementationFee__c = 500,
            MonthlyFee__c = 75,
            IsActive = true
        );
        insert product;

        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            Name = CreateInvoiceAuraController.PRICEBOOK_STANDARD_NAME,
            IsActive = true
        );
        update standardPricebook;

        PriceBookEntry pbe = new PriceBookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = product.Id,
            IsActive = true,
            UnitPrice = 75
        );
        insert pbe;
    }

    public static testMethod void testNewVisitWithQuoteId() 
    {
        PageReference successPage = Page.BN_CheckoutSucceed;
        Test.setCurrentPage(successPage);
        ApexPages.currentPage().getParameters().put('id', 'stripe-id');
        ApexPages.currentPage().getParameters().put('invoice', invoiceId);
        ApexPages.currentPage().getParameters().put('order', '1');
        ApexPages.currentPage().getParameters().put('length', 'monthly');

        Test.startTest();
        BN_CheckoutSucceedController controller = new BN_CheckoutSucceedController();
        Cookie visited = ApexPages.currentPage().getCookies().get('visited-stripe-id');
        controller.addSuccessActions();
        Test.stopTest();

        System.AssertEquals(visited.getValue(), '1');
    }

    public static testMethod void testNewVisitWithoutQuoteId() 
    {
        PageReference successPage = Page.BN_CheckoutSucceed;
        Test.setCurrentPage(successPage);
        ApexPages.currentPage().getParameters().put('id', 'stripe-id');
        ApexPages.currentPage().getParameters().put('invoice', '');
        ApexPages.currentPage().getParameters().put('order', '1');
        ApexPages.currentPage().getParameters().put('length', 'monthly');

        Test.startTest();
        BN_CheckoutSucceedController controller = new BN_CheckoutSucceedController();
        Cookie visited = ApexPages.currentPage().getCookies().get('visited-stripe-id');
        controller.addSuccessActions();
        Test.stopTest();

        System.AssertEquals(visited.getValue(), '1');
    }

}