force-app/main/default/objects/Opportunity/fields/PMS_Text__c.field-meta.xml
<CustomField>
    <fullName>PMS_Text__c</fullName>
    <label>What are you looking to get out of your</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BN_ExpressionInterestController_Test.cls
@isTest(seealldata = true)
public with sharing class BN_ExpressionInterestController_Test {

    public static Account account;
    public static Contact contact;
    public static Opportunity opportunity;
    
    static 
    {
        createTestData();
    }
    
    public static void createTestData() 
    {
        account = new Account();
        account.Name =  'Booking Ninjas';
        insert account;
        
        contact = new Contact();
        contact.LastName = 'Harroch';
        contact.FirstName = 'David';
        contact.Email = 'testdavid@bookingninjas.com';
        contact.AccountId = account.Id;
        insert contact;
        
        opportunity = new Opportunity();
        opportunity.Name = 'New Opportunity';
        opportunity.AccountId = account.Id;
        opportunity.Primary_Contact__c = contact.Id;
        opportunity.Type = 'New Business';
        opportunity.StageName = 'Trial';
        opportunity.LeadSource = 'Booking Ninjas';
        opportunity.CloseDate = Date.Today().addDays(15);
        opportunity.PMS_Text__c =  'Test message';
        insert opportunity;
    }
    
    public static testMethod void testRegister() 
    {
        Test.startTest();
        
            PageReference pageRef = Page.BN_Interest;
            Test.setCurrentPage(pageRef);

            BN_ExpressionInterestController ctrl = new BN_ExpressionInterestController();
            
            ctrl.name = 'Joe Johnson';
            ctrl.email = 'joe@email.com';
            ctrl.propertyName = 'Test Hotel';
            ctrl.numberOfRooms = '100';
            ctrl.pmsText = 'Test messgae';
            ctrl.targetDateOfActivation = Date.Today();
            ctrl.register(); 
            
        Test.stopTest();
    }
}