force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/trialEmail__c.field-meta.xml
<CustomField>
    <fullName>trialEmail__c</fullName>
    <description>It&apos;s for trial/pilot page, should not be manually add value.</description>
    <label>trialEmail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerTest.cls
@isTest
public class OpportunityTriggerTest {

    static testmethod void TestOppAutoFillFields() {
    
        Contact contact = new Contact();
        contact.LastName = 'Teguh';
        contact.Email = 'teguh@bookingninjas.com';
        insert contact;

        Account acc = new Account();
        acc.Name = 'Business Account';
        insert acc;
        
        Test.StartTest();
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp Name';
        opp.AccountId = acc.Id;
        opp.CloseDate = Date.Today();
        opp.StageName = 'Qualification';
        opp.Primary_Contact__c = contact.id;
        insert opp;
        
        Test.StopTest();
        
        //System.assertEquals(opp.Name, 'Business Account_Qualification_' + String.valueOf(Date.today().addDays(30)));
        //System.assertEquals(opp.CloseDate, Date.today().addDays(30));
        //System.assertEquals(opp.StageName, 'Qualification');
        //System.assertEquals(opp.Type, 'New Business');
    }
    
    static testmethod void testOpportunityFromTrialForm() {
        
        Contact contact = new Contact();
        contact.LastName = 'Teguh';
        contact.Email = 'teguh@bookingninjas.com';
        insert contact;
           
        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'New Opportunity: Teguh';
        opportunity.trialEmail__c = 'teguh@bookingninjas.com';
        opportunity.Type = 'New Business';
        opportunity.StageName = 'Trial';
        opportunity.LeadSource = 'Booking Ninjas';
        opportunity.CloseDate = Date.Today().addDays(15);
        insert opportunity;
        
        Opportunity oppRecord = [SELECT Id, AccountId, Primary_Contact__c, trialEmail__c FROM Opportunity WHERE Id = :opportunity.Id LIMIT 1];
        
        Test.StartTest();
        System.assertEquals(oppRecord.AccountId, contact.AccountId);
        System.assertEquals(oppRecord.Primary_Contact__c, contact.Id);
        System.assertEquals(oppRecord.trialEmail__c, null);
        Test.StopTest();
    }

}