force-app/main/default/objects/BN_User__c/BN_User__c.object-meta.xml
<CustomObject>
    <label>BN User</label>
    <nameField>
        <displayFormat>BNU-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BN Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BN_User__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>BN Users</relationshipLabel>
    <relationshipName>BN_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BN_User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>50</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/BN_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BN_User__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Request Change Password</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BN_User__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BN_User_History_Login__c/BN_User_History_Login__c.object-meta.xml
<CustomObject>
    <label>BN User History Login</label>
    <nameField>
        <displayFormat>BNHL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BN User History Login</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BN_User_History_Login__c/fields/BN_User__c.field-meta.xml
<CustomField>
    <fullName>BN_User__c</fullName>
    <label>BN User</label>
    <referenceTo>BN_User__c</referenceTo>
    <relationshipLabel>BN User History Login</relationshipLabel>
    <relationshipName>BN_User_History_Login</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BN_User_History_Login__c/fields/isLogout__c.field-meta.xml
<CustomField>
    <fullName>isLogout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isLogout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BN_User_History_Login__c/fields/Source_IP__c.field-meta.xml
<CustomField>
    <fullName>Source_IP__c</fullName>
    <label>Source IP</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BN_Portal_UserUtils.cls
public class BN_Portal_UserUtils {
    
    public static Boolean isLogout() {
        
        DateTime dt =  DateTime.now();
        String strdate = dt.format('MMddyyyy');
        String uniqueId = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP') + '.' + strdate;
        
        List<BN_User_History_Login__c> loginHis = [SELECT Id, isLogout__c
                                           FROM BN_User_History_Login__c
                                           WHERE Status__c = 'Success' 
                                            AND Session_Id__c = :uniqueId
                                           ORDER BY CreatedDate DESC];
                                           
        if (loginHis.size() == 0) return true;
            
        if (loginHis[0].isLogout__c) return true;

        return false;
    }
    
    public static String logout() {
    
        DateTime dt =  DateTime.now();
        String strdate = dt.format('MMddyyyy');
        String uniqueId = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP') + '.' + strdate;
        
        List<BN_User_History_Login__c> loginHists = [SELECT Id, isLogout__c
                                           FROM BN_User_History_Login__c
                                           WHERE isLogout__c = false 
                                            AND Session_Id__c = :uniqueId
                                            ORDER BY CreatedDate DESC];
        try {
            if (loginHists.size() > 0) {
                for (BN_User_History_Login__c loginHist : loginHists) {
                    loginHist.isLogout__c = true;
                }
            }
            UPDATE loginHists;
        } catch (Exception e) {
            System.debug('Login Exception: ' + e);
            return e.getMessage();
        }
        
        return '';
    }
    
    public static String login(String username, String password) {
        if (String.isEmpty(username))
            return System.Label.BN_User_Username_Empty;
        if (String.isEmpty(password))
            return System.Label.BN_User_Password_Empty;
        
        DateTime dt =  DateTime.now();
        String strdate = dt.format('MMddyyyy');
        String uniqueId = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP') + '.' + strdate;
          
        try {
            List<BN_User__c> beUsers = [SELECT Id, Password__c, Status__c, Contact__c
                            FROM BN_User__c 
                            WHERE Username__c = :username];
            if (beUsers.size() == 0) {
                System.debug(System.Label.BN_User_No_Exist);
                return System.Label.BN_User_No_Exist;
            } else {
                if (beUsers[0].Password__c != password) {
                    System.debug(System.Label.BN_User_Pass_Incorrect);
                    BN_User_History_Login__c newLogin = new BN_User_History_Login__c(                       
                        BN_User__c = beUsers[0].Id,
                        Status__c = 'Password Incorrect',
                        Session_Id__c = uniqueId,
                        Source_IP__c = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP'));
                    INSERT newLogin;
                    return System.Label.BN_User_Pass_Incorrect;
                } if (beUsers[0].Contact__c == null) {
                    return 'This user is not link to any opportunity. Please contact with our administrator.';
                } else if (beUsers[0].Status__c == 'Inactive' || beUsers[0].Status__c == 'Locked') {
                    System.debug(System.Label.BN_User_Inactive);
                    BN_User_History_Login__c newLogin = new BN_User_History_Login__c(
                        BN_User__c = beUsers[0].Id,
                        Status__c = 'User Inactive',
                        Session_Id__c = uniqueId,
                        Source_IP__c = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP'));
                    INSERT newLogin;
                    return System.Label.BN_User_Inactive;
                }
            }
        
            System.debug('Login Success');
            BN_User_History_Login__c newLogin = new BN_User_History_Login__c(
                BN_User__c = beUsers[0].Id,
                Status__c = 'Success',
                Session_Id__c = uniqueId,
                Source_IP__c = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP'));
            INSERT newLogin;
        } catch (Exception e) {
            System.debug('Login Exception: ' + e);
            return e.getMessage();
        }

        return '';
    }
    
    public static String getCurrBNUserId() {

        DateTime dt =  DateTime.now();
        String strdate = dt.format('MMddyyyy');
        String uniqueId = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP') + '.' + strdate;
        
        List<BN_User_History_Login__c> loginHis = [SELECT Id, BN_User__c
                                           FROM BN_User_History_Login__c
                                           WHERE Status__c = 'Success' 
                                            AND isLogout__c = false
                                            AND Session_Id__c = :uniqueId
                                           ORDER BY CreatedDate DESC LIMIT 1];
        if (loginHis.size() > 0) return loginHis[0].BN_User__c;
        return '';
    }
    
    public static Contact getContactByBNUserId(string userId) {
        
        BN_User__c user = [SELECT Id, Contact__c FROM BN_User__c WHERE Id = :userId];
        if (user != null) 
        {
            return [SELECT Id, Name, Email, Phone, AccountId, Account.Name, Vision__c, Values__c, Methods__c, Obstacles__c, Measures__c FROM Contact WHERE Id = :user.Contact__c];
        }
        return null;
    }
    
    public static String getUserRole(String userId) {
        return [SELECT Id, Role__c FROM BN_User__c WHERE Id = :userId].Role__c;
    }
    
    public static PageReference defaultLandingPage() {
        PageReference fwPage = new PageReference('/portal');

        return fwPage;
    }
}