force-app/main/default/objects/BN_User__c/BN_User__c.object-meta.xml
<CustomObject>
    <label>BN User</label>
    <nameField>
        <displayFormat>BNU-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BN Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BN_User__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Request Change Password</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Email_Subscription__c/Email_Subscription__c.object-meta.xml
<CustomObject>
    <label>Email Subscription</label>
    <nameField>
        <displayFormat>ES-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BN_Portal_ForgotPassword_Controller_Test.cls
@isTest
public class BN_Portal_ForgotPassword_Controller_Test
{
    @testSetup static void posSetup() {
        BN_DataTest.createDataTest(true, true);
        
        Email_Subscription__c subscription= new Email_Subscription__c();
        subscription.Email__c  = 'david@bookingninjas.com';
        insert subscription;
    }
    
    @isTest
    static void itShould()
    {
        PageReference pageRef = Page.BN_Portal_ForgotPassword;
        Test.setCurrentPage(pageRef);
        
        BN_Portal_ForgotPassword_Controller ctr = new BN_Portal_ForgotPassword_Controller();
        ctr.emailRequest = 'david@bookingninjas.com';
        ctr.requestChangePassword();
        
        List<BN_User__c> bnUsers = [SELECT Id FROM BN_User__c LIMIT 1];
        if (bnUsers.size() > 0) {
            //bnUsers[0].Status__c = 'Request Change Password';
            //update beUsers[0];
            
            Apexpages.currentPage().getParameters().put('id', bnUsers[0].Id);
            ctr = new BN_Portal_ForgotPassword_Controller();
            
            ctr.newPassword = 'newPassword';
            ctr.submitNewPassword();
        }
    }
    
    @isTest
    static void testSubscribe() 
    {
        PageReference pageRef = Page.BN_Portal_ForgotPassword;
        Test.setCurrentPage(pageRef);
        
        BN_Portal_ForgotPassword_Controller ctrl = new BN_Portal_ForgotPassword_Controller();
        
        ctrl.email = 'joee@johnson.com';
        ctrl.subscribe();
    }
}