force-app/main/default/objects/BN_User__c/BN_User__c.object-meta.xml
<CustomObject>
    <label>BN User</label>
    <nameField>
        <displayFormat>BNU-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BN Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BN_User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>50</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/BN_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BN_User__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Request Change Password</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BN_User__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Email_Subscription__c/Email_Subscription__c.object-meta.xml
<CustomObject>
    <label>Email Subscription</label>
    <nameField>
        <displayFormat>ES-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BN_Portal_Template_Controller_Test.cls
@isTest
public class BN_Portal_Template_Controller_Test
{
    @testSetup static void posSetup() {
        BN_DataTest.createDataTest(true, true);
        
        Email_Subscription__c subscription= new Email_Subscription__c();
        subscription.Email__c  = 'david@bookingninjas.com';
        insert subscription;
    }
    
    @isTest
    static void itShould()
    {
        String username;
        String password;
        List<BN_User__c> bnUsers = [SELECT Id, Username__c, Password__c FROM BN_User__c WHERE Role__c = 'Client' AND Status__c = 'Active'];
        if (bnUsers.size() > 0) {
            username = bnUsers[0].Username__c;
            password = bnUsers[0].Password__c;
        }
    
        PageReference pageRef = Page.BN_Portal_Home;
        Test.setCurrentPage(pageRef);
        
        BN_Portal_Template_Controller ctr = new BN_Portal_Template_Controller();
        
        ctr.page = ApexPages.currentPage().getUrl().substringAfter('/').split('\\?')[0];
        ctr.title = 'Best Hotel Management Software - Cloud-Based PMS | Booking Ninjas';
        ctr.description = 'The proper way to handle your property management today. Join our users and enjoy predictable growth';
        
        ctr.ref = Apexpages.currentPage().getUrl();
        
        Boolean isLogout = ctr.getIsLogout();
        ctr.checkUserLogin();
        ctr.redirectToLandingPage();
        
        if(isLogout)
        {
            ctr.username = username;
            ctr.password = password;
            ctr.login();
            ctr.getUserRole();
        }
        
        ctr.logoutPage();
    }
    
    @isTest
    static void passwordIncorrect()
    {
        String username;
        String password;
        List<BN_User__c> bnUsers = [SELECT Id, Username__c, Password__c FROM BN_User__c WHERE Role__c = 'Client' AND Status__c = 'Active'];
        if (bnUsers.size() > 0) {
            username = bnUsers[0].Username__c;
            password = bnUsers[0].Password__c;
        }
    
        PageReference pageRef = Page.BN_Portal_Home;
        Test.setCurrentPage(pageRef);
        
        BN_Portal_Template_Controller ctr = new BN_Portal_Template_Controller();
        
        Boolean isLogout = ctr.getIsLogout();
        
        if(isLogout)
        {
            ctr.username = username;
            ctr.password = 'wrongPassword';
            ctr.login();
        }
    }
    
    @isTest
    static void inactiveClient()
    {
        String username;
        String password;
        List<BN_User__c> bnUsers = [SELECT Id, Username__c, Password__c FROM BN_User__c WHERE Role__c = 'Client' AND Status__c = 'Inactive'];
        if (bnUsers.size() > 0) {
            username = bnUsers[0].Username__c;
            password = bnUsers[0].Password__c;
        }
    
        PageReference pageRef = Page.BN_Portal_Home;
        Test.setCurrentPage(pageRef);
        
        BN_Portal_Template_Controller ctr = new BN_Portal_Template_Controller();
        
        Boolean isLogout = ctr.getIsLogout();
        
        if(isLogout)
        {
            ctr.username = username;
            ctr.password = password;
            ctr.login();
        }
    }
    
    @isTest
    static void testSubscribe() 
    {
        PageReference pageRef = Page.BN_Portal_Template;
        Test.setCurrentPage(pageRef);
        
        BN_Portal_Template_Controller ctrl = new BN_Portal_Template_Controller();
        
        ctrl.email = 'joee@johnson.com';
        ctrl.subscribe();
    }
}