force-app/main/default/objects/BN_User__c/BN_User__c.object-meta.xml
<CustomObject>
    <label>BN User</label>
    <nameField>
        <displayFormat>BNU-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BN Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BN_User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>50</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/BN_User__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BN_Portal_ClientV2MOM_Controller_Test.cls
@isTest
public class BN_Portal_ClientV2MOM_Controller_Test
{
    @testSetup static void posSetup() {
        BN_DataTest.createDataTest(true, true);
    }
    
    public static testMethod void testItShould() 
    {
        String bnUserId;

        List<BN_User__c> bnUsers = [SELECT Id, Username__c, Password__c FROM BN_User__c LIMIT 1];
        if (bnUsers.size() > 0)
        {
            BN_Portal_UserUtils.login(bnUsers[0].Username__c, bnUsers[0].Password__c);
        
            bnUserId = BN_Portal_UserUtils.getCurrBNUserId();
        }
        
        PageReference pageRef = Page.BN_Portal_ClientV2MOM;
        Test.setCurrentPage(pageRef);
        
        BN_Portal_ClientV2MOM_Controller ctrl = new BN_Portal_ClientV2MOM_Controller();
        
        ctrl.contact = BN_Portal_UserUtils.getContactByBNUserId(bnUserId);
        
        ctrl.vision = 'test vision';
        ctrl.values = 'test values';
        ctrl.methods = 'test methods';
        ctrl.obstacles = 'test obstacles';
        ctrl.measures = 'test measures';
        ctrl.saveV2MOM();
    }
}