force-app/main/default/objects/NewActivity__c/NewActivity__c.object-meta.xml
<CustomObject>
    <label>NewActivity</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NewActivities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NewActivity__c/fields/Campaign_Date__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Date__c</fullName>
    <label>Campaign Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>NewActivities</relationshipLabel>
    <relationshipName>NewActivities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Super Warms</fullName>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Total_Click__c.field-meta.xml
<CustomField>
    <fullName>Total_Click__c</fullName>
    <label>Total Click</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Total_Open__c.field-meta.xml
<CustomField>
    <fullName>Total_Open__c</fullName>
    <label>Total Open</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Unsubscribed__c.field-meta.xml
<CustomField>
    <fullName>Unsubscribed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unsubscribed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Unsubscribed_Date__c.field-meta.xml
<CustomField>
    <fullName>Unsubscribed_Date__c</fullName>
    <label>Unsubscribed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Unsubscribed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Unsubscribed_Reason__c</fullName>
    <label>Unsubscribed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Campaign_Date__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Date__c</fullName>
    <description>No need to set this, it&apos;s only for email integrator to determine when is the email campaign date</description>
    <label>Campaign Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchKirimOpportunityTest.cls
@istest
class BatchKirimOpportunityTest {

    @testSetup 
    static void setup() {
        Account account = new Account(name='Teguh Prayoga');
        insert account;
        
        Contact contact = new Contact(
            Lastname = 'Prayoga',
            Email = 'teguh1@live.com',
            AccountId = account.Id
        );
        insert contact;

        NewActivity__c aktivitas = new NewActivity__c(
            Name = 'Test Campaign',
            Campaign_Date__c = Date.today(),
            Contact__c = contact.Id,
            Total_Open__c = 6,
            Total_Click__c = 1,
            Unsubscribed__c = false,
            Unsubscribed_Reason__c = null,
            Unsubscribed_Date__c = null,
            Status__c = 'Hot'
        );
        insert aktivitas;

        Opportunity opportunity = new Opportunity(
            Name = 'fromtrigger',
            Type = 'New Business',
            AccountId = Account.Id,
            Primary_Contact__c = contact.Id,
            CloseDate = Date.newInstance(2018, 2, 17),
            StageName = 'Top Opps'
        );
        insert opportunity;
    }
    
    static testmethod void testActivityScheduler() {
        // schedule time
        //String cronExpr = '0 0 0 15 3 ? 2022';
		String cronExpr = '0 0 * * * ?';

        Test.startTest();
        BatchKirimOpportunity opps = new BatchKirimOpportunity();
        String jobId = System.schedule('BatchKirimOpportunity', cronExpr, opps);
        Test.stopTest();

        Integer executedJobs = [
            SELECT count() FROM AsyncApexJob
            WHERE JobType = 'BatchApex'
            AND ApexClass.Name = 'BatchKirimOpportunity'
        ];
        system.assertEquals(1, executedJobs, 'The job should be scheduled');
    }

    static testmethod void testUpdateOpportunity() {
        Test.startTest();
        BatchKirimOpportunity opps = new BatchKirimOpportunity();
        Id batchId = Database.executeBatch(opps);
        Test.stopTest();

        // after the testing stops, assert records were updated properly
        System.assertEquals(1, [select count() from Opportunity]);
        Date tanggal = Date.today().addDays(5);
        System.assertEquals(1, [select count() from Opportunity where StageName = 'Top Opps' AND CloseDate = :tanggal]);
    }

    static testmethod void testAddOpportunity() {
        Account account = new Account(name='Muhammad Teguh');
        insert account;
        
        Contact contact = new Contact(
            Lastname = 'Teguh',
            Email = 'teguh2@live.com',
            AccountId = account.Id
        );
        insert contact;

        NewActivity__c aktivitas = new NewActivity__c(
            Name = 'Test Campaign 2',
            Campaign_Date__c = Date.today(),
            Contact__c = contact.Id,
            Total_Open__c = 7,
            Total_Click__c = 1,
            Unsubscribed__c = false,
            Unsubscribed_Reason__c = null,
            Unsubscribed_Date__c = null,
            Status__c = 'Hot'
        );
        insert aktivitas;

        Test.startTest();
        BatchKirimOpportunity opps = new BatchKirimOpportunity();
        Id batchId = Database.executeBatch(opps);
        Test.stopTest();

        // after the testing stops, assert records were updated properly
        System.assertEquals(2, [select count() from Opportunity]);
        Date tanggal = Date.today().addDays(5);
        System.assertEquals(1, [select count() from Opportunity where StageName = 'Working' AND CloseDate = :tanggal]);
        System.assertEquals(1, [select count() from Opportunity where StageName = 'Top Opps' AND CloseDate = :tanggal]);
    }

}