force-app/main/default/objects/Account_Executive__c/Account_Executive__c.object-meta.xml
<CustomObject>
    <label>Account Executive</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Executives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/Cook_Book__c.object-meta.xml
<CustomObject>
    <label>Cook Book</label>
    <nameField>
        <label>Cook Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cook Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <referenceTo>Account_Executive__c</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Call_Result__c.field-meta.xml
<CustomField>
    <fullName>Call_Result__c</fullName>
    <label>Call Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appointments</fullName>
            </value>
            <value>
                <fullName>Call Backs</fullName>
            </value>
            <value>
                <fullName>Demo/Trial</fullName>
                <label>ReEngage</label>
            </value>
            <value>
                <fullName>Follow up_Warm up</fullName>
                <label>Follow up/Warm up</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>2nd Meetings</fullName>
                <isActive>false</isActive>
                <label>2nd Meetings</label>
            </value>
            <value>
                <fullName>Voice Mail</fullName>
                <isActive>false</isActive>
                <label>Voice Mail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(Contact__r.Email != null, Contact__r.Email, Contact__r.Email_2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Interest_Level__c.field-meta.xml
<CustomField>
    <fullName>Interest_Level__c</fullName>
    <label>Interest Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Scheduled_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Time__c</fullName>
    <label>Scheduled Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Calls</fullName>
            </value>
            <value>
                <fullName>Linkedin Requests</fullName>
            </value>
            <value>
                <fullName>Emails</fullName>
            </value>
            <value>
                <fullName>Drips</fullName>
            </value>
            <value>
                <fullName>Touch Calls</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CookBookController_Test.cls
@isTest
public class CookBookController_Test {
    
    public static Cook_Book__c cb;
    public static Account_Executive__c ae;
    
    Static {
        createTestData();
    }

    public static void createTestData() {
        //Business account
        Account a = new Account(Name = 'test', BillingCountry = 'Philippines');
        insert a;

        Contact con = new Contact(FirstName = 'David', LastName = 'Harroch', Accountid = a.Id, Email =  'david@bookingninjas.com', MailingCountry = 'Philippines');
        insert con;
        
        ae = new Account_Executive__c();
        ae.Name = 'David Harroch';
        ae.Email__c = 'david@bookigninjas.com';
        insert ae;
        
        //instantiate date time
        DateTime dt = Datetime.Now();
        
        List<Cook_Book__c> cbList = new List<Cook_Book__c>();
        for(Integer i=1; i<=10; i++) {
            cb = new Cook_Book__c();
            cb.Name = 'Test_Call_' + con.Name + '_' + Date.Today().addDays(i);
            cb.Contact__c = con.Id;
            cb.Scheduled_Date__c = Date.Today().addDays(i);
            cb.Scheduled_Time__c = Time.newInstance(dt.hour(), dt.minute(), 0, 0);
            cb.Account_Executive__c = ae.Id;
            cb.Type__c = 'Calls';
            cb.Call_Result__c = 'Appointments';
            cb.Interest_Level__c = String.valueOf(i);
            cbList.add(cb);
        }
        insert cbList;
    }
    
    public static testMethod void TestCookBookList() {
        Test.StartTest();
        
        PageReference pageRef = Page.CookBookReport;
        Test.setCurrentPage(pageRef);
        CookBookController controller = new CookBookController();
        controller.getListOfUsers();
        controller.getListOfInterestLevel();
        controller.getListOfContinents();
        controller.getListOfCallResult();
        controller.UserId = ae.Id;
        controller.StartDate = Date.Today();
        controller.EndDate = Date.Today().addDays(30);
        controller.InterestLevel = '1';
        controller.Continent = 'Asia';
        controller.search();
        
        Test.StopTest();
    }
}