force-app/main/default/objects/Account_Executive__c/Account_Executive__c.object-meta.xml
<CustomObject>
    <label>Account Executive</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Executives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/Cook_Book__c.object-meta.xml
<CustomObject>
    <label>Cook Book</label>
    <nameField>
        <label>Cook Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cook Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <referenceTo>Account_Executive__c</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(Contact__r.Email != null, Contact__r.Email, Contact__r.Email_2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Scheduled_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Time__c</fullName>
    <label>Scheduled Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/ScheduleCallBatchTest.cls
@isTest
public class ScheduleCallBatchTest {

    @isTest static void testProcess(){
    
        Account acc = new Account(Name = 'Business Account');
     
        Contact con = new Contact(LastName = 'Harroch', FirstName = 'David', Email = 'david@bookingninjas.com', AccountId = acc.Id);
        insert con;

        Account_Executive__c ae = new Account_Executive__c(Name = 'David', Email__c = 'david@bookingninjas.com');
        insert ae;
        
        List<Cook_Book__c> cbs = new List<Cook_Book__c>();
        for(Integer i = 0; i <= 20; i++) {
            Cook_Book__c cb = new Cook_Book__c(Name = 'Call and Meeting', Scheduled_Date__c = Date.Today(), Scheduled_Time__c = Time.newInstance(i, 0, 0 ,0), Contact__c = con.Id, Account_Executive__c = ae.Id);
            cbs.add(cb);
        }
        insert cbs;
        
        Test.startTest();
            ScheduleCallBatch batch = new ScheduleCallBatch();
            batch.execute(null, cbs);
            batch.start(null);
            batch.finish(null);
        Test.stopTest();
    }

    @isTest static void testScheduledJob(){
        Test.startTest();
            ScheduledJob job = new ScheduledJob();
            job.execute(null);
        Test.stopTest();
    }    
}