force-app/main/default/objects/Account_Executive__c/Account_Executive__c.object-meta.xml
<CustomObject>
    <label>Account Executive</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Executives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/Cook_Book__c.object-meta.xml
<CustomObject>
    <label>Cook Book</label>
    <nameField>
        <label>Cook Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cook Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <referenceTo>Account_Executive__c</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Call_Result__c.field-meta.xml
<CustomField>
    <fullName>Call_Result__c</fullName>
    <label>Call Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appointments</fullName>
            </value>
            <value>
                <fullName>Call Backs</fullName>
            </value>
            <value>
                <fullName>Demo/Trial</fullName>
                <label>ReEngage</label>
            </value>
            <value>
                <fullName>Follow up_Warm up</fullName>
                <label>Follow up/Warm up</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>2nd Meetings</fullName>
                <isActive>false</isActive>
                <label>2nd Meetings</label>
            </value>
            <value>
                <fullName>Voice Mail</fullName>
                <isActive>false</isActive>
                <label>Voice Mail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(Contact__r.Email != null, Contact__r.Email, Contact__r.Email_2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Interest_Level__c.field-meta.xml
<CustomField>
    <fullName>Interest_Level__c</fullName>
    <label>Interest Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Record_Call__c.field-meta.xml
<CustomField>
    <fullName>Record_Call__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Record Call?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/NewActivity__c.object-meta.xml
<CustomObject>
    <label>NewActivity</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NewActivities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NewActivity__c/fields/Campaign_Date__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Date__c</fullName>
    <label>Campaign Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>NewActivities</relationshipLabel>
    <relationshipName>NewActivities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Total_Open__c.field-meta.xml
<CustomField>
    <fullName>Total_Open__c</fullName>
    <label>Total Open</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchKirimCookBook.cls
public class BatchKirimCookBook implements Database.Batchable<sObject>, Schedulable {

    public Iterable<sObject> start(Database.BatchableContext bc) {
        List<Cook_Book__c> removeCbs = [SELECT Id FROM Cook_Book__c WHERE Name LIKE '% -Appointments- %' AND CreatedDate = LAST_N_DAYS:7];
        if (removeCbs != null) {
            delete removeCbs;
        }

        List<NewActivity__c> acts = [SELECT ID, Name, Campaign_Date__c, Total_Open__c, Contact__c, Contact__r.Name, Contact__r.AccountId, Contact__r.Email, Contact__r.HasOptedOutOfEmail FROM NewActivity__c WHERE Campaign_Date__c = LAST_N_DAYS:7 AND Total_Open__c >= 2];

        return acts;
    }

    public void execute(Database.BatchableContext bc, List<NewActivity__c> acts){
        List<Cook_Book__c> addCbs = new List<Cook_Book__c>();
        Account_Executive__c aex = [SELECT Id FROM Account_Executive__c WHERE Email__c = 'david@bookingninjas.com' LIMIT 1];

        for (NewActivity__c act: acts) {
            Integer actStatus = Integer.valueOf(act.Total_Open__c);
            String cbStatus = '';
            String cbStrStatus = '';
            if (actStatus >= 7) {
                cbStrStatus = 'Hot';
                cbStatus = '6';
            } else if (actStatus >= 4) {
                cbStrStatus = 'Super Warms';
                cbStatus = '5';
            } else if (actStatus >= 2) {
                cbStrStatus = 'Warm';
                cbStatus = '4';
            }
            Date skrg = date.today();
            Date tanggalBuka = act.Campaign_Date__c;
            Date tanggalTelp = tanggalBuka.addDays(2);
            Integer numberDaysDue = skrg.monthsBetween(tanggalTelp);

            if (numberDaysDue >= 0 && act.Contact__r.HasOptedOutOfEmail != true) {
                Cook_Book__c cb = new Cook_Book__c(
                    Name = act.Contact__r.Name + ' -Appointments- ' + String.valueOf(tanggalTelp),
                    Contact__c = act.Contact__c,
                    Account_Executive__c = aex.Id,
                    Interest_Level__c = cbStatus,
                    Record_Call__c = true,
                    Call_Result__c = 'Appointments',
                    Notes__c = cbStrStatus + ': ' + act.Name,
                    Scheduled_Date__c = tanggalTelp
                );
                if (!addCbs.contains(cb)) {
                    addCbs.add(cb);
                }
            }
        }

        if (addCbs != null) {
            insert addCbs;
        }
    }

    public void finish(Database.BatchableContext bc){
    }

    public void execute(SchedulableContext sc) {
        BatchKirimCookBook b = new BatchKirimCookBook();
        database.executebatch(b, 100); // execute only 100 records per batch
    }

}