force-app/main/default/objects/Account_Executive__c/Account_Executive__c.object-meta.xml
<CustomObject>
    <label>Account Executive</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Executives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/Cook_Book__c.object-meta.xml
<CustomObject>
    <label>Cook Book</label>
    <nameField>
        <label>Cook Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cook Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <referenceTo>Account_Executive__c</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Call_Result__c.field-meta.xml
<CustomField>
    <fullName>Call_Result__c</fullName>
    <label>Call Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appointments</fullName>
            </value>
            <value>
                <fullName>Call Backs</fullName>
            </value>
            <value>
                <fullName>Demo/Trial</fullName>
                <label>ReEngage</label>
            </value>
            <value>
                <fullName>Follow up_Warm up</fullName>
                <label>Follow up/Warm up</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>2nd Meetings</fullName>
                <isActive>false</isActive>
                <label>2nd Meetings</label>
            </value>
            <value>
                <fullName>Voice Mail</fullName>
                <isActive>false</isActive>
                <label>Voice Mail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(Contact__r.Email != null, Contact__r.Email, Contact__r.Email_2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Interest_Level__c.field-meta.xml
<CustomField>
    <fullName>Interest_Level__c</fullName>
    <label>Interest Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Calls</fullName>
            </value>
            <value>
                <fullName>Linkedin Requests</fullName>
            </value>
            <value>
                <fullName>Emails</fullName>
            </value>
            <value>
                <fullName>Drips</fullName>
            </value>
            <value>
                <fullName>Touch Calls</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/X2nd_Phone__c.field-meta.xml
<CustomField>
    <fullName>X2nd_Phone__c</fullName>
    <label>2nd Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/ScheduleCallService.cls
public with sharing class ScheduleCallService {
    
    public String contactId {get; set;}
    Set<String> objectIds = new Set<String>();
    List<Contact> contacts = new List<Contact>();
    
    public Date scheduledDate {get; set;}
    public String notes {get; set;}
    public String interestLevel {get; set;}
    public Id userId {get; set;}
    
    public boolean contactHasSchedule {get; set;}
    public Boolean showError {get; set;}
    public Boolean showSuccess {get; set;}
    public String responseMessage {get; set;}
    
    public ScheduleCallService() {
        
        contactHasSchedule = false;
        showError = false;
        showSuccess = false;
        responseMessage = '';
    }
    
    public void createTask() 
    {
        showError = false;
        showSuccess = false;
        responseMessage = '';
        
        if(scheduledDate != null && userId != null) 
        {   
            // instantiate CB list for saving                        
            List<Cook_Book__c> cook_books = new List<Cook_Book__c>();
                        
            // split ids to list
            List<String> contactIds = contactId.split(',');
            for(String cId : contactIds) 
            {
                objectIds.add(cId);
            }
            
            // iterate contacts and schedule call one at a time        
            for(Contact contact : [SELECT Id, Name, Account.Name, Email, MobilePhone, Phone, x2nd_Phone_Number__c FROM Contact WHERE Id IN :objectIds]) 
            {
                Cook_Book__c cb = new Cook_Book__c();
                cb.Name = contact.Name + ' - Appointments ' + String.valueOf(scheduledDate);
                cb.Contact__c = contact.Id;
                cb.Mobile__c = contact.MobilePhone;
                cb.Phone__c = contact.Phone;
                cb.X2nd_Phone__c = contact.X2nd_Phone_Number__c;
                cb.Account_Executive__c = userId;
                cb.Scheduled_Date__c = scheduledDate;
                cb.Type__c = 'Calls';
                cb.Call_Result__c = 'Appointments';
                cb.Notes__c = notes;
                cb.Interest_Level__c = interestLevel;
                cook_books.add(cb);
            }
            
            try 
            {
                if(cook_books.size() > 0)
                {
                    insert cook_books;
                    
                    Account_Executive__c ae = [SELECT Id, Name, Email__c FROM Account_Executive__c WHERE Id = :userId];
                    sendEmail(scheduledDate, ae.Email__c, cook_books.size());    
                        
                    showError = false;
                    showSuccess = true;
                    responseMessage = 'Successfully created ' + cook_books.size() + ' cook book(s) out of ' + contacts.size() + ' contact(s) and assigned schedule call to ' + ae.Name + '.';
                }
                else {
                    showError = true;
                    showSuccess = false;
                    responseMessage = 'Selected contact(s) or AE(s) might already have scheduled call on the selected date, please select a new date or assign to another AE';
                }
            }
            catch(Exception e) 
            {
                showError = true;
                showSuccess = false;
                responseMessage = 'Failed to set schedule calls. See error: ' + e.getMessage();
            }
        }
        else 
        {
            showError = true;
            showSuccess = false;
            responseMessage = 'No date or account executive selected!';
        }
        
    }
    
    public List<SelectOption> getListOfUsers() 
    {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '--Select--'));
        for(Account_Executive__c u : [Select Id, Name, Email__c from Account_Executive__c]) 
        {
            options.add(new SelectOption(u.Id, u.Email__c));
        }
        return options;
    }
    
    public List<SelectOption> getListInterestLevel() 
    {
        List<SelectOption> options = new List<SelectOption>();
        for(Integer i = 0; i <= 10; i++) 
        {
            options.add(new SelectOption(String.valueOf(i), String.valueOf(i)));
        }
        return options;
    }
    
    public void isContactHasSchedule() 
    {
        showError = false;
        showSuccess = false;
        responseMessage = '';
        
        List<String> contactIds = contactId.split(',');
        for(String cId : contactIds) 
        {
            objectIds.add(cId);
        }
        
        List<Cook_Book__c> checkCBs = [SELECT Id FROM Cook_Book__c WHERE Contact__c IN :objectIds AND Scheduled_Date__c >= :scheduledDate];
        if(checkCBs.size() > 0) 
        {         
            showError = true;
            showSuccess = false;
            responseMessage = 'Selected contact(s) has already scheduled call in the future. Would you still like to proceed?';
        }
    }
    
    private boolean isExistingSchedule(String contactId, String userId, Date scheduledDate)
    {    
        // check first if contact has existing schedule
        List<Cook_Book__c> checkContacts = [SELECT Id FROM Cook_Book__c WHERE Contact__c = :contactId AND Scheduled_Date__c = :scheduledDate];
        if(checkContacts.size() > 0)
        {
            return true;
        }
        else 
        {
            // then check if account executive is available for the available schedule
            List<Cook_Book__c> checkAEs = [SELECT Id FROM Cook_Book__c WHERE Account_Executive__c = :userId AND Scheduled_Date__c = :scheduledDate];
            if(checkAEs.size() > 0) {
                return true;
            }
            return false;
        } 
    }
    
    private void sendEmail(Date scheduledDate, string recipient, integer size)
    {
        OrgWideEmailAddress orgAddress = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'noreply@bookingninjas.com' LIMIT 1];
        
        String formattedDate = scheduledDate.Month() + '/' + scheduledDate.Day() + '/' + scheduledDate.Year();
                    
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(new String[]{ recipient });
        email.setSubject('You have new assigned task!');
        email.setHTMLBody('You have ' + size + ' new scheduled call(s) on ' + formattedDate + '. <br/><br/> Please see via <a href=\'https://bookingninjas.my.salesforce.com/apex/CookBookReport?id=' + userId + '&date=' + scheduledDate + '\'>cook book report</a>.<br/><br/> If you find the record with no scheduled time, please set it. <br/><br/>If you already had a recent interaction with the contacts, please disregard.');
        email.setOrgWideEmailAddressId(orgAddress.Id);
        Messaging.SendEmailResult[] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
    }
}