force-app/main/default/objects/Account_Executive__c/Account_Executive__c.object-meta.xml
<CustomObject>
    <label>Account Executive</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Executives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/Cook_Book__c.object-meta.xml
<CustomObject>
    <label>Cook Book</label>
    <nameField>
        <label>Cook Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cook Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <referenceTo>Account_Executive__c</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Call_Result__c.field-meta.xml
<CustomField>
    <fullName>Call_Result__c</fullName>
    <label>Call Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appointments</fullName>
            </value>
            <value>
                <fullName>Call Backs</fullName>
            </value>
            <value>
                <fullName>Demo/Trial</fullName>
                <label>ReEngage</label>
            </value>
            <value>
                <fullName>Follow up_Warm up</fullName>
                <label>Follow up/Warm up</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>2nd Meetings</fullName>
                <isActive>false</isActive>
                <label>2nd Meetings</label>
            </value>
            <value>
                <fullName>Voice Mail</fullName>
                <isActive>false</isActive>
                <label>Voice Mail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(Contact__r.Email != null, Contact__r.Email, Contact__r.Email_2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Interest_Level__c.field-meta.xml
<CustomField>
    <fullName>Interest_Level__c</fullName>
    <label>Interest Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Linkedin__c.field-meta.xml
<CustomField>
    <fullName>Linkedin__c</fullName>
    <formula>HYPERLINK(Contact__r.LinkedIN__c , Contact__r.LinkedIN__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linkedin</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Scheduled_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Time__c</fullName>
    <label>Scheduled Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Calls</fullName>
            </value>
            <value>
                <fullName>Linkedin Requests</fullName>
            </value>
            <value>
                <fullName>Emails</fullName>
            </value>
            <value>
                <fullName>Drips</fullName>
            </value>
            <value>
                <fullName>Touch Calls</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/X2nd_Phone__c.field-meta.xml
<CustomField>
    <fullName>X2nd_Phone__c</fullName>
    <label>2nd Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CookBookController.cls
public with sharing class CookBookController {
    
    private static final String AND_CLAUSE = ' AND ';
    private static final String WHERE_CLAUSE = ' WHERE ';
    private static final String APPOINTMENTS = 'Appointments';
    private static final String CALL_BACKS = 'Call Backs';
    private static final String VOICE_MAIL = 'Voice Mail';
    
    
    public List<CookBook> CookBooks { get; set; }
    public Integer count { get; set; }
    public Date StartDate { get; set; }
    public Date EndDate { get; set; }
    public Id UserId { get; set; }
    public String InterestLevel { get; set; }
    public String Continent { get; set; }
    public String CallResult { get; set; }
    public Boolean HasPhone { get; set; }
        
    public CookBookController()
    {
        UserId = apexpages.currentpage().getparameters().get('id');
        StartDate = String.isEmpty(apexpages.currentpage().getparameters().get('date')) ? Date.Today() : Date.valueOf(apexpages.currentpage().getparameters().get('date'));
        EndDate = StartDate;
        HasPhone = true;
        count = 0;
        
        search();
    }
    
    public void search()
    { 
        String query = 'SELECT Id, Contact__c, Contact__r.Name, Contact__r.LinkedIN__c, Contact__r.Title, Scheduled_Date__c, Scheduled_Time__c, Type__c, Account_Executive__c, Account_Executive__r.Name, Call_Result__c, Interest_Level__c FROM Cook_Book__c' + WHERE_CLAUSE;
        query += '(Call_Result__c = :APPOINTMENTS OR Call_Result__c = :CALL_BACKS OR Call_Result__c = :VOICE_MAIL)' + AND_CLAUSE;
        if(UserId != null) {
            query += 'Account_Executive__c = :UserId' + AND_CLAUSE;
        }              
        if(StartDate != null) {
            query += 'Scheduled_Date__c >= :StartDate' + AND_CLAUSE;
        }
        if(EndDate != null) {
            query += 'Scheduled_Date__c <= :EndDate' + AND_CLAUSE;
        }
        if(!String.isEmpty(InterestLevel)) {
            query += 'Interest_Level__c = :InterestLevel' + AND_CLAUSE;
        }
        if(!String.isEmpty(CallResult)) {
            query += 'Call_Result__c = :CallResult' + AND_CLAUSE;
        }
        if(!String.isEmpty(Continent)) {
            query += 'Contact__r.Account.Continent__c = :Continent' + AND_CLAUSE;
        }
        
        if(HasPhone) {
            query += '(Mobile__c <> null OR Phone__c <> null OR X2nd_Phone__c <> null)' + AND_CLAUSE;
        }
        else {
            query += '(Mobile__c = null AND Phone__c = null AND X2nd_Phone__c = null)' + AND_CLAUSE;
        }
        
        if(query.contains(AND_CLAUSE)) {
            query = query.removeEnd(AND_CLAUSE);
        }
        else {
            query = query.remove(WHERE_CLAUSE);
        }
        query += ' ORDER BY Scheduled_Time__c';
        System.debug(LoggingLevel.Info ,'query = ' + query);
        
        Cook_Book__c[] results = Database.query(String.escapeSingleQuotes(query));
        
        CookBooks = new List<CookBook>();
        for(Cook_Book__c cb : results) {
            CookBooks.add(new CookBook(cb));
        }
        
        count = CookBooks.size();
    }
    
    // wrapper class to hold aggregate data
    public class CookBook 
    {
        public String Id { get; private set; }
        public String Contact { get; private set; }
        public String AE { get; private set; }
        public String ScheduledDate { get; private set; }
        public String ScheduledTime { get; private set; }
        public String CallResult { get; private set; }
        public String InterestLevel { get; private set; }
        public String Linkedin { get; private set; }
        public String Title { get; private set; }

        public CookBook(Cook_Book__c cb) {
            Id = cb.Id;
            Contact = cb.Contact__r.Name;
            ScheduledDate = cb.Scheduled_Date__c == null ? '' : cb.Scheduled_Date__c.Month() + '/' + cb.Scheduled_Date__c.Day() + '/' + cb.Scheduled_Date__c.Year();
            ScheduledTime = cb.Scheduled_Time__c == null ? '' : cb.Scheduled_Time__c.Hour() + ':' + cb.Scheduled_Time__c.Minute();
            AE = cb.Account_Executive__r.Name;
            CallResult = cb.Call_Result__c;
            InterestLevel = cb.Interest_Level__c;
            Linkedin = cb.Contact__r.LinkedIN__c;
            Title = cb.Contact__r.Title;
        }
    }
    
    public List<SelectOption> getListOfUsers() 
    {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '--Select--'));
        for(Account_Executive__c ae : [Select Id, Name, Email__c from Account_Executive__c]) {
            options.add(new SelectOption(ae.Id, ae.Email__c));
        }
        return options;
    }
    
    public List<SelectOption> getListOfInterestLevel() 
    {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '--Select--'));
        for(Integer i = 0; i <= 10; i++) {
            options.add(new SelectOption(String.valueOf(i), String.valueOf(i)));
        }
        return options;
    }
    
    public List<SelectOption> getListOfCallResult() 
    {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '--Select--'));
        //options.add(new SelectOption('Contacted', 'Contacted'));
        options.add(new SelectOption('Voice Mail', 'Voice Mail'));
        options.add(new SelectOption('Call Backs', 'Call Backs'));
        options.add(new SelectOption('Appointments', 'Appointments'));
        //options.add(new SelectOption('2nd Meetings', '2nd Meetings'));
        //options.add(new SelectOption('Demo/Trial', 'Demo/Trial'));
        //options.add(new SelectOption('Proposal', 'Proposal'));
        //options.add(new SelectOption('Close', 'Close'));
        return options;
    }
    
    public List<SelectOption> getListOfContinents() 
    {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '--Select--'));
        options.add(new SelectOption('Africa', 'Africa'));
        options.add(new SelectOption('Asia', 'Asia'));
        options.add(new SelectOption('Australia & Oceania', 'Australia & Oceania'));
        options.add(new SelectOption('EC America', 'EC America'));
        options.add(new SelectOption('EMEA', 'EMEA'));
        options.add(new SelectOption('Europe', 'Europe'));
        options.add(new SelectOption('South America', 'South America'));
        options.add(new SelectOption('WC America', 'WC America'));
        return options;
    }
}