force-app/main/default/objects/Account_Executive__c/Account_Executive__c.object-meta.xml
<CustomObject>
    <label>Account Executive</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Executives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/Cook_Book__c.object-meta.xml
<CustomObject>
    <label>Cook Book</label>
    <nameField>
        <label>Cook Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cook Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <referenceTo>Account_Executive__c</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Scheduled_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Time__c</fullName>
    <label>Scheduled Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/ScheduleCallBatch.cls
global with sharing class ScheduleCallBatch implements Database.Batchable<sObject>{
    private ScheduleCallBatchService service = new ScheduleCallBatchService();
    public static Integer HOUR_PARAM = System.Now().addMinutes(30).hour();
    public static Integer MINUTE_PARAM = System.Now().addMinutes(30).minute();
    Time mapTime = Time.newInstance(HOUR_PARAM, MINUTE_PARAM, 0, 0);
    public static String query = 'SELECT Id, ' + 
                                        'Contact__c, ' +
                                        'Account_Executive__c, ' +
                                        'Scheduled_Date__c, ' +
                                        'Scheduled_Time__c ' +
                                 'FROM Cook_Book__c ' +
                                 'WHERE Scheduled_Date__c = TODAY ' +
                                 'AND Scheduled_Time__c = :mapTime ' +
                                 'AND Account_Executive__c != NULL';
                                 
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Cook_Book__c> records) {
        service.process(records);
    }  

    global void finish(Database.BatchableContext BC) {
        
    }    
}