force-app/main/default/objects/Account_Executive__c/Account_Executive__c.object-meta.xml
<CustomObject>
    <label>Account Executive</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Executives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Log__c/Call_Log__c.object-meta.xml
<CustomObject>
    <label>Call Log</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Log__c/fields/Call_Result__c.field-meta.xml
<CustomField>
    <fullName>Call_Result__c</fullName>
    <label>Call Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Voice Mail</fullName>
            </value>
            <value>
                <fullName>Call backs</fullName>
            </value>
            <value>
                <fullName>Appointments</fullName>
            </value>
            <value>
                <fullName>2nd Meetings</fullName>
            </value>
            <value>
                <fullName>Demo/Trial</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Cook_Book__c.field-meta.xml
<CustomField>
    <fullName>Cook_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cook Book</label>
    <referenceTo>Cook_Book__c</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/Cook_Book__c.object-meta.xml
<CustomObject>
    <label>Cook Book</label>
    <nameField>
        <label>Cook Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cook Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <referenceTo>Account_Executive__c</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Call_Result__c.field-meta.xml
<CustomField>
    <fullName>Call_Result__c</fullName>
    <label>Call Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appointments</fullName>
            </value>
            <value>
                <fullName>Call Backs</fullName>
            </value>
            <value>
                <fullName>Demo/Trial</fullName>
                <label>ReEngage</label>
            </value>
            <value>
                <fullName>Follow up_Warm up</fullName>
                <label>Follow up/Warm up</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>2nd Meetings</fullName>
                <isActive>false</isActive>
                <label>2nd Meetings</label>
            </value>
            <value>
                <fullName>Voice Mail</fullName>
                <isActive>false</isActive>
                <label>Voice Mail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(Contact__r.Email != null, Contact__r.Email, Contact__r.Email_2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Next_Call__c.field-meta.xml
<CustomField>
    <fullName>Next_Call__c</fullName>
    <label>Next Call</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Reassign_to_new_AE__c.field-meta.xml
<CustomField>
    <fullName>Reassign_to_new_AE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reassign to new AE</label>
    <referenceTo>Account_Executive__c</referenceTo>
    <relationshipLabel>Cook Books (Reassign to new AE)</relationshipLabel>
    <relationshipName>Cook_Books1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Scheduled_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Time__c</fullName>
    <label>Scheduled Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/X2nd_Phone__c.field-meta.xml
<CustomField>
    <fullName>X2nd_Phone__c</fullName>
    <label>2nd Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CookBookTriggerTest.cls
@isTest
public class CookBookTriggerTest {

    static testmethod void testRescheduleCookBookCall() {

        Test.StartTest();
            
        Account accountTest = new Account();
        accountTest.Name = 'Test Name';
        insert accountTest;
        
        Contact conTest = new Contact();
        conTest.AccountId = accountTest.Id;
        conTest.FirstName = 'TestFname';
        conTest.LastName = 'TestLname';
        conTest.Email = 'david@bookingninjas.com';
        contest.MobilePhone = '+19176002345';
        contest.Phone = '+19176002345';
        contest.X2nd_Phone_Number__c = '+19176002345';
        insert conTest;
        
        Account_Executive__c ae1 = new Account_Executive__c();
        ae1.Name = 'David Harroch';
        ae1.Email__c = 'david@bookigninjas.com';
        insert ae1;
        
        Account_Executive__c ae2 = new Account_Executive__c();
        ae2.Name = 'Danrien Lagman';
        ae2.Email__c = 'danrienl@bookigninjas.com';
        insert ae2;
        
        DateTime dt = System.today();
        
        // insert first cook book record
        Cook_Book__c cb1 = new Cook_Book__c();
        cb1.Name = 'Test Appointment 1';
        cb1.Contact__c = conTest.Id;
        cb1.Mobile__c = conTest.MobilePhone;
        cb1.Phone__c = conTest.Phone;
        cb1.X2nd_Phone__c = conTest.X2nd_Phone_Number__c;
        cb1.Account_Executive__c = ae1.Id;
        cb1.Scheduled_Date__c = Date.Today().addDays(1);
        cb1.Scheduled_Time__c = Time.newInstance(dt.hour(), dt.minute(), 0, 0);
        cb1.Call_Result__c = 'Appointments';
        insert cb1;
        
        // update cook book record 1, then set next call and reassign to AE
        Cook_Book__c cb2 = [SELECT Id, Contact__c, Mobile__c, Phone__c, X2nd_Phone__c, Account_Executive__c, Scheduled_Date__c, Scheduled_Time__c, Next_Call__c, Reassign_to_new_AE__c FROM Cook_Book__c WHERE Id = :cb1.Id];
        cb2.Next_Call__c = DateTime.newInstance(dt.Year(), dt.Month(), dt.Day(), dt.Hour(), dt.Minute(), 0);
        cb2.Reassign_to_new_AE__c = ae2.id;
        update cb2;
        
        // insert call log
        Call_Log__c cl = new Call_Log__c();
        cl.Cook_Book__c = cb1.Id;
        cl.Call_Result__c = 'Contacted';
        insert cl;
        
        Test.StopTest();
        
        //System.assertEquals(cl.Call_Result__c, cb1.Call_Result__c);

    }
    
}