force-app/main/default/objects/Account_Executive__c/Account_Executive__c.object-meta.xml
<CustomObject>
    <label>Account Executive</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Executives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/Cook_Book__c.object-meta.xml
<CustomObject>
    <label>Cook Book</label>
    <nameField>
        <label>Cook Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cook Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <referenceTo>Account_Executive__c</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/AccountLookup__c.field-meta.xml
<CustomField>
    <fullName>AccountLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Call_Result__c.field-meta.xml
<CustomField>
    <fullName>Call_Result__c</fullName>
    <label>Call Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appointments</fullName>
            </value>
            <value>
                <fullName>Call Backs</fullName>
            </value>
            <value>
                <fullName>Demo/Trial</fullName>
                <label>ReEngage</label>
            </value>
            <value>
                <fullName>Follow up_Warm up</fullName>
                <label>Follow up/Warm up</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>2nd Meetings</fullName>
                <isActive>false</isActive>
                <label>2nd Meetings</label>
            </value>
            <value>
                <fullName>Voice Mail</fullName>
                <isActive>false</isActive>
                <label>Voice Mail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(Contact__r.Email != null, Contact__r.Email, Contact__r.Email_2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Interest_Level__c.field-meta.xml
<CustomField>
    <fullName>Interest_Level__c</fullName>
    <label>Interest Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Linkedin__c.field-meta.xml
<CustomField>
    <fullName>Linkedin__c</fullName>
    <formula>HYPERLINK(Contact__r.LinkedIN__c , Contact__r.LinkedIN__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linkedin</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Scheduled_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Time__c</fullName>
    <label>Scheduled Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Calls</fullName>
            </value>
            <value>
                <fullName>Linkedin Requests</fullName>
            </value>
            <value>
                <fullName>Emails</fullName>
            </value>
            <value>
                <fullName>Drips</fullName>
            </value>
            <value>
                <fullName>Touch Calls</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/X2nd_Phone__c.field-meta.xml
<CustomField>
    <fullName>X2nd_Phone__c</fullName>
    <label>2nd Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CookBookLWCController.cls
public with sharing class CookBookLWCController {

    private static final String AND_CLAUSE = ' AND ';
    private static final String WHERE_CLAUSE = ' WHERE ';
    private static final List<String> callResultsRestriction = new List<String>{
        'Appointments',
        'Call Backs',
        'Contacted',
        'Voice Mail'
    };

    @AuraEnabled(cacheable=true)
    public static List<Account_Executive__c> getAccountExecutives() {
        return [
            SELECT Id, Name, Email__c 
            FROM Account_Executive__c 
            WITH SECURITY_ENFORCED 
            ORDER BY Name DESC
        ];
    }

    @AuraEnabled(cacheable=true)
    public static String search(String searchJson) {

        SearchWrapper sw = (SearchWrapper) JSON.deserialize(searchJson, SearchWrapper.class);
        
        String query = 'SELECT  Id, ' +
                               'Contact__c, ' +
                               'Contact__r.Name, ' +
                               'Contact__r.LinkedIN__c, ' +
                               'Contact__r.Title, ' +
                               'Scheduled_Date__c, ' +
                               'Scheduled_Time__c, ' +
                               'Notes__c, ' +
                               'Type__c, ' +
                               'Account_Executive__c, ' +
                               'Account_Executive__r.Name, ' +
                               'AccountLookup__c, ' +
                               'AccountLookup__r.Name, ' +
                               'AccountLookup__r.Linkedin_Company_URL__c, ' +
                               'Call_Result__c, ' +
                               'Interest_Level__c ' +
                        'FROM Cook_Book__c' + WHERE_CLAUSE; 
        query += '(Call_Result__c IN :callResultsRestriction)' + AND_CLAUSE;

        if(!String.isEmpty(sw.userId)) {
            Id userId = sw.userId;
            query += 'Account_Executive__c = :userId' + AND_CLAUSE;
        }
        if(sw.startDate != null) {
            Date startDate = sw.startDate;
            query += 'Scheduled_Date__c >= :startDate' + AND_CLAUSE;
        }
        if(sw.endDate != null) {
            Date endDate = sw.endDate;
            query += 'Scheduled_Date__c <= :endDate' + AND_CLAUSE;
        }
        if(!String.isEmpty(sw.interestLevel)) {
            String interestLevel = sw.interestLevel;
            query += 'Interest_Level__c = :interestLevel' + AND_CLAUSE;
        }
        if(!String.isEmpty(sw.callResult)) {
            String callResult = sw.callResult;
            query += 'Call_Result__c = :callResult' + AND_CLAUSE;
        }
        if(!String.isEmpty(sw.continent)) {
            String continent = sw.continent;
            query += 'Contact__r.Account.Continent__c = :continent' + AND_CLAUSE;
        }

        if(sw.hasPhone) {
            query += '(Mobile__c <> null OR Phone__c <> null OR X2nd_Phone__c <> null)' + AND_CLAUSE;
        }

        if(sw.linkedinConnect) {
            String acceptedStr = 'Accepted';
            query += 'Contact__r.Linkedin_Activity__c = :acceptedStr' + AND_CLAUSE;
        }

        if(sw.hasAccount) {
            query += '(AccountLookup__c <> null OR Contact__r.AccountId <> null)' + AND_CLAUSE;
        }

        if(query.contains(AND_CLAUSE)) {
            query = query.removeEnd(AND_CLAUSE);
        }
        else {
            query = query.remove(WHERE_CLAUSE);
        }
        query += ' ORDER BY Scheduled_Time__c';
        
        
        List<Cook_Book__c> cookBookList = Database.query(String.escapeSingleQuotes(query));

        List<CookBookWrapper> cookBookWrapperList = new List<CookBookWrapper>();
        for (Cook_Book__c cb : cookBookList) {
            cookBookWrapperList.add(new CookBookWrapper(
                cb.Contact__r.Name,
                cb.AccountLookup__r.Name,
                cb.Contact__r.Title,
                cb.Scheduled_Date__c,
                cb.Interest_Level__c != null ? Integer.valueOf(cb.Interest_Level__c) : null,
                cb.Call_Result__c,
                cb.Contact__r.LinkedIN__c,
                cb.AccountLookup__r.Linkedin_Company_URL__c,
                cb.Account_Executive__r.Name,
                cb.Contact__c,
                cb.Id,
                cb.AccountLookup__c,
                cb.Notes__c
            ));
        }

        Map<String, Object> responseObj = new Map<String, Object>();
        responseObj.put('count', cookBookList.size());
        responseObj.put('searchResult', cookBookWrapperList);

        return JSON.Serialize(responseObj);
    }


    public class SearchWrapper {
        String userId;
        Date startDate;
        Date endDate;
        String interestLevel;
        String continent;
        String callResult;
        Boolean hasPhone;
        Boolean hasAccount;
        Boolean linkedinConnect;

        public SearchWrapper(String userId, Date startDate, Date endDate, String interestLevel, String continent, String callResult, Boolean hasPhone, Boolean hasAccount, Boolean linkedinConnect) {
            this.userId = userId;
            this.startDate = startDate;
            this.endDate = endDate;
            this.interestLevel = interestLevel;
            this.continent = continent;
            this.callResult = callResult;
            this.hasPhone = hasPhone;
            this.hasAccount = hasAccount;
            this.linkedinConnect = linkedinConnect;
        }
    }

    public class CookBookWrapper {
        String contactName;
        String accountName;
        String contactTitle;
        Date scheduledDate;
        Integer interestLevel;
        String callResult;
        String contactLinkedIn;
        String contactLinkedInAccount;
        String accountExecutiveNameAssignedTo;
        String navigateToContactRecordPage;
        String navigateToAccountRecordPage;
        String navigateToCookBookRecordPage;
        String cookBookNotes;

        public CookBookWrapper(
            String contactName,
            String accountName,
            String contactTitle,
            Date scheduledDate,
            Integer interestLevel,
            String callResult,
            String contactLinkedIn,
            String contactLinkedInAccount,
            String accountExecutiveNameAssignedTo,
            String contactId,
            String cookBookId,
            String accountId,
            String cookBookNotes)
        {
            this.contactName = contactName != null ? contactName : '-';
            this.accountName = accountName != null ? accountName : '-';
            this.contactTitle = contactTitle != null ? contactTitle : '-';
            this.scheduledDate = scheduledDate;
            this.interestLevel = interestLevel;
            this.callResult = callResult;
            this.contactLinkedIn = contactLinkedIn != null ? contactLinkedIn : contactLinkedInAccount;
            this.accountExecutiveNameAssignedTo = accountExecutiveNameAssignedTo;
            this.navigateToContactRecordPage = contactId != null ? '/' + contactId : '';
            this.navigateToCookBookRecordPage = cookBookId != null ? '/' + cookBookId : '';
            this.navigateToAccountRecordPage = accountId != null ? '/' + accountId : '';
            this.cookBookNotes = cookBookNotes != null ? cookBookNotes : '-';
        }
    }

}