force-app/main/default/objects/Account_Executive__c/Account_Executive__c.object-meta.xml
<CustomObject>
    <label>Account Executive</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Executives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/Cook_Book__c.object-meta.xml
<CustomObject>
    <label>Cook Book</label>
    <nameField>
        <label>Cook Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cook Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <referenceTo>Account_Executive__c</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Call_Result__c.field-meta.xml
<CustomField>
    <fullName>Call_Result__c</fullName>
    <label>Call Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appointments</fullName>
            </value>
            <value>
                <fullName>Call Backs</fullName>
            </value>
            <value>
                <fullName>Demo/Trial</fullName>
                <label>ReEngage</label>
            </value>
            <value>
                <fullName>Follow up_Warm up</fullName>
                <label>Follow up/Warm up</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>2nd Meetings</fullName>
                <isActive>false</isActive>
                <label>2nd Meetings</label>
            </value>
            <value>
                <fullName>Voice Mail</fullName>
                <isActive>false</isActive>
                <label>Voice Mail</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(Contact__r.Email != null, Contact__r.Email, Contact__r.Email_2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/NewActivity__c.object-meta.xml
<CustomObject>
    <label>NewActivity</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NewActivities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NewActivity__c/fields/Campaign_Date__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Date__c</fullName>
    <label>Campaign Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>NewActivities</relationshipLabel>
    <relationshipName>NewActivities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Super Warms</fullName>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Total_Click__c.field-meta.xml
<CustomField>
    <fullName>Total_Click__c</fullName>
    <label>Total Click</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Total_Open__c.field-meta.xml
<CustomField>
    <fullName>Total_Open__c</fullName>
    <label>Total Open</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Unsubscribed__c.field-meta.xml
<CustomField>
    <fullName>Unsubscribed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unsubscribed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Unsubscribed_Date__c.field-meta.xml
<CustomField>
    <fullName>Unsubscribed_Date__c</fullName>
    <label>Unsubscribed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NewActivity__c/fields/Unsubscribed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Unsubscribed_Reason__c</fullName>
    <label>Unsubscribed Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchKirimCookBookTest.cls
@istest
class BatchKirimCookBookTest {

    @testSetup 
    static void setup() {
        Account account = new Account(name='Teguh Prayoga');
        insert account;
        
        Contact contact = new Contact(
            Lastname = 'Prayoga',
            Email = 'teguh1@live.com',
            AccountId = account.Id
        );
        insert contact;

        Account_Executive__c aex = new Account_Executive__c(Name='David Harroch',Email__c='david@bookingninjas.com');
        insert aex;
    }
    
    static testmethod void testActivityScheduler() {
        // schedule time
        //String cronExpr = '0 0 0 15 3 ? 2022';
		String cronExpr = '0 0 * * * ?';
        
        Test.startTest();
        BatchKirimCookBook opps = new BatchKirimCookBook();
        String jobId = System.schedule('BatchKirimCookBook', cronExpr, opps);
        Test.stopTest();

        Integer executedJobs = [
            SELECT count() FROM AsyncApexJob
            WHERE JobType = 'BatchApex'
            AND ApexClass.Name = 'BatchKirimCookBook'
        ];
        system.assertEquals(1, executedJobs, 'The job should be scheduled');
    }

    static testmethod void testCookBooks() {
        Contact contact = [SELECT Id FROM Contact LIMIT 1];
        NewActivity__c aktivitas = new NewActivity__c(
            Name = 'Test Campaign',
            Campaign_Date__c = Date.today(),
            Contact__c = contact.Id,
            Total_Open__c = 6,
            Total_Click__c = 1,
            Unsubscribed__c = false,
            Unsubscribed_Reason__c = null,
            Unsubscribed_Date__c = null,
            Status__c = 'Hot'
        );
        insert aktivitas;

        Test.startTest();
        BatchKirimCookBook opps = new BatchKirimCookBook();
        Id batchId = Database.executeBatch(opps);
        Test.stopTest();

        // after the testing stops, assert records were updated properly
        System.assertEquals(1, [select count() from Cook_Book__c]);
        System.assertEquals(1, [select count() from Cook_Book__c where Call_Result__c = 'Appointments']);
    }

    static testmethod void testNoCookBook() {
        Test.startTest();
        BatchKirimCookBook opps = new BatchKirimCookBook();
        Id batchId = Database.executeBatch(opps);
        Test.stopTest();

        // after the testing stops, assert records were updated properly
        System.assertEquals(0, [select count() from Cook_Book__c]);
        System.assertEquals(0, [select count() from Cook_Book__c where Call_Result__c = 'Appointments']);
    }

}