force-app/main/default/objects/Account_Executive__c/Account_Executive__c.object-meta.xml
<CustomObject>
    <label>Account Executive</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Executives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/Cook_Book__c.object-meta.xml
<CustomObject>
    <label>Cook Book</label>
    <nameField>
        <label>Cook Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cook Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cook_Book__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <referenceTo>Account_Executive__c</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cook Books</relationshipLabel>
    <relationshipName>Cook_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(Contact__r.Email != null, Contact__r.Email, Contact__r.Email_2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cook_Book__c/fields/Scheduled_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Time__c</fullName>
    <label>Scheduled Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/ScheduleCallBatchService.cls
public class ScheduleCallBatchService {

    public static final String ORG_WIDE_ADDRESS = 'noreply@bookingninjas.com';
   
    public void process(List<Cook_Book__c> cbList) {
        Set<Id> cbIds = new Set<Id>();
        for(Cook_Book__c cb : cbList){
            cbIds.add(cb.Id);
        }
        
        OrgWideEmailAddress orgAddress = [SELECT Id FROM OrgWideEmailAddress WHERE Address = :ORG_WIDE_ADDRESS LIMIT 1];
            
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        
        for(Cook_Book__c cb : cbList){
        
            String ae_email = [SELECT Email__c FROM Account_Executive__c WHERE Id = :cb.Account_Executive__c].Email__c;
            String contact_name = [SELECT Name FROM Contact WHERE Id = :cb.Contact__c].Name;
            string formattedTime = cb.Scheduled_Time__c.Hour() + ':' + cb.Scheduled_Time__c.Minute();
            
            Messaging.SingleEmailMessage email = getEmailMessage(contact_name, ae_email, formattedTime, orgAddress);
            emailList.add(email);
        }
        
        if(emailList.size() > 0) {
            Messaging.SendEmailResult[] results = Messaging.sendEmail(emailList, false);
        } 
    }
    
    private Messaging.SingleEmailMessage getEmailMessage(String name, String recipient, String formattedTime, OrgWideEmailAddress orgAddress){
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(new String[]{ recipient });
        email.setSubject('Call Assigned | Follow up');
        email.setHTMLBody('Upcoming scheduled call with ' + name + ' today at ' + formattedTime + '!<br/><br/>Lets change the world one account at a time!!!');
        email.setOrgWideEmailAddressId(orgAddress.Id);
        
        return email;      
    }
}