force-app/main/default/objects/CustomerStories__c/CustomerStories__c.object-meta.xml
<CustomObject>
    <label>Customer Stories</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerStories__c/fields/About__c.field-meta.xml
<CustomField>
    <fullName>About__c</fullName>
    <label>About</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CustomerStories__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>controller if the Customer story will or will not show on the webpage.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerStories__c/fields/LongDescription__c.field-meta.xml
<CustomField>
    <fullName>LongDescription__c</fullName>
    <label>Long Description</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CustomerStories__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CustomerStoriesDetailControllerTest.cls
@isTest
private with sharing class CustomerStoriesDetailControllerTest {

    @isTest
    static void tester() {
        List<CustomerStories__c> listCs = new List<CustomerStories__c>();
        for(integer i=0; i<3; i++){
            CustomerStories__c cs = new CustomerStories__c();
            cs.Name = 'Company '+i;
            cs.About__c = 'About the campany '+i;
            cs.Industry__c = 'Hospital ';
            cs.Location__c = 'Country '+i;
            cs.LongDescription__c = 'lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum ';
            cs.Quote__c = 'lorem ipsumlorem  ';
            cs.IsActive__c = true;

            listCs.add(cs);
        }

        insert listCs;
        
        Test.startTest();

        CustomerStories__c cs1 = [SELECT Id, Name, About__c FROM CustomerStories__c WHERE Name = 'Company 0' LIMIT 1];

        PageReference pageRef = Page.BN_CustomerStories_Detail;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', cs1.Id);

        CustomerStoriesDetailController contr = new CustomerStoriesDetailController();
        Test.stopTest();

        System.assert(contr.story?.Location__c == 'Country 0');
    }
}