force-app/main/default/objects/CustomerStories__c/CustomerStories__c.object-meta.xml
<CustomObject>
    <label>Customer Stories</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerStories__c/fields/About__c.field-meta.xml
<CustomField>
    <fullName>About__c</fullName>
    <label>About</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CustomerStories__c/fields/ClientSince__c.field-meta.xml
<CustomField>
    <fullName>ClientSince__c</fullName>
    <label>Client Since</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomerStories__c/fields/LongDescription__c.field-meta.xml
<CustomField>
    <fullName>LongDescription__c</fullName>
    <label>Long Description</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CustomerStories__c/fields/MainImage__c.field-meta.xml
<CustomField>
    <fullName>MainImage__c</fullName>
    <label>Main Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CustomerStories__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CustomerStoriesDetailController.cls
public class CustomerStoriesDetailController {

    public CustomerStories__c story {get; set;}

    public CustomerStoriesDetailController(){
        this.story = [SELECT Id, Name, About__c, ClientSince__c, MainImage__c, Description__c,
                      Industry__c, Location__c, Logo__c, LongDescription__c, Quote__c
                      FROM CustomerStories__c
                      WHERE Id =: ApexPages.currentPage().getParameters().get('id')
                    ];
    }
    
}